---
title: "microscopy Data Clean"
author: "Juan P Barraza"
date: "7/8/2020"
output: html_document
editor_options: 
  chunk_output_type: console
---
```{r setup}
library(pixmap)
library(rtiff)
library(reshape2)
library(gplots)
library(dplyr)
library(gdata)
library(ggplot2)
library(cowplot)
library(magrittr)
library(tidyr)
library(purrr)
library(plotrix)#this is for std.error function
library(scales)#for negative log

PA14wt<- c('3-13-19', '3-19-19', '4-17-19')
PA14mut<- c('4-24-19', '4-25-19', '5-8-19')
PA01wt<- c('3-26-19','4-18-19')
PA01mut<- c('4-23-19')
names3<-c('rep1','rep2','rep3')
names2<-c('rep1','rep2')
names1<-c('rep1')

GetNumber<-function(idx){
  if (idx<10){
    idx = paste0(0,idx)
  }
  return (idx)
}
```

```{r Pa Growth curves from RedSubtracted Images}
#This will give us a sense on how much of the Pa data was erased because it overlapped with the Sa data.
ReadResultsFile<-function(file, position, timepoint){#reads the results file and outputs data
  datos <-read.csv(file, header = FALSE)
  colnames(datos)<-c('Red', 'Green', 'Slice')
  datos<-datos %>% mutate(Position = position)
  datos<-datos %>% mutate(TimePoint = timepoint)
  return(datos)
}
GetResults<-function(sample, samplename){#points to folder with files. Folder is hardcoded, unfortunately
  #folder<- paste0('/Users/jupabago/Documents/Whiteley/PROJECTS/PaSaProject/Spatial paper Data/Microscopy Data/RedSubtractedImages/',sample,'/resultsSubtractRed1')#for pa co only
  folder<- paste0('/Users/jupabago/Documents/Whiteley/PROJECTS/PaSaProject/Spatial paper Data/Microscopy Data/Other Data1/',sample,'/results')
  fileList<-list.files(path = folder, full.names = TRUE)
  growthDf<-data.frame()
  #for (position in 2:3){
  #  currentPosition<-fileList[grep(paste0("p",position,"."),fileList)]
  currentPosition<-fileList[grep(paste0("p2."),fileList)]#only running p2, which in this case 
    for (timepoint in 0:6){
      currentTimePoint<-currentPosition[grep(paste0("t",GetNumber(timepoint),"_"),currentPosition)]
      growthDf<-rbind(growthDf,ReadResultsFile(currentTimePoint, 2, timepoint))
      #growthDf<-rbind(growthDf,ReadResultsFile(currentTimePoint, position, timepoint))
      }
    #}
  growthDf<-growthDf %>% mutate(Sample = samplename)
return(growthDf)
} 
MapResults<- function(listSamples, reps){
  blah <-deparse(substitute(listSamples))
  mappedData<-map2(listSamples, reps, GetResults)
  boundData<-bind_rows(mappedData)
  boundData<-boundData %>% mutate(Strain = blah)
  boundData<-gather(boundData,"Color","Value",-Slice,-Position,-Sample,-TimePoint,-Strain) %>% mutate(LogValue=ifelse(Value>0,log10(Value),0))
  boundData<-boundData %>% mutate(Condition = recode(Position, "0" = "Sa Mono", "1" = "Pa Mono", "2" = "Pa:Sa 1:1", "3" = "Pa:Sa 10:1", "4" = "Pa:Sa 1:100", "5" = "Pa:Sa 1:10" )) %>% mutate(Species = recode(Color, "Red" = "Sa", "Green" = "Pa")) %>% mutate(ZDistance = Slice *0.44)
  boundData$Condition<-as.factor(boundData$Condition)
  boundData$Condition<-factor(boundData$Condition, levels = c("Sa Mono", "Pa Mono", "Pa:Sa 1:1", "Pa:Sa 1:10", "Pa:Sa 1:100","Pa:Sa 10:1"))
  boundData$Species<-as.factor(boundData$Species)
  boundData$Strain<-as.factor(boundData$Strain)
  return(boundData)
  }
ProcessResults <-function(){
  wt<-MapResults(PA14wt, names3)
  mut<-MapResults(PA14mut, names3)
  #combine them:
  results<-rbind(wt,mut)
  #Add up all the data on each slice and then get the log of that total
  resultsSum<-results %>% group_by(TimePoint,Sample,Strain,Condition,Species)%>% 
    summarise(Totals = sum (Value))%>%
    mutate(LogTotals = ifelse(Totals>0, log10(Totals), 0))
  #get stats between replicates
  resultsStats<-resultsSum %>% group_by(TimePoint,Strain,Condition,Species) %>% 
    summarise(MeanTotals = mean(Totals), SDTotals = sd(Totals), MeanLogTotals = mean(LogTotals), SDLogTotals = sd(LogTotals)) %>% 
    mutate(MeanLogTotalsRevd = 10^MeanLogTotals, SDLogTotalsRevd =10^(SDLogTotals))
  results <- list(resultsSum,resultsStats)
  return(results)
} 

redSubtractedData<-ProcessResults()#test function
redSubtractedDataSummary<-redSubtractedData[[1]]
paRedSubtractResults<-redSubtractedDataSummary%>% filter(Species == "Pa")
saRedSubtractResults<-redSubtractedDataSummary%>% filter(Species == "Sa")

nonSubtractedData<-ProcessResults()
nonSubtractedDataSummary<-nonSubtractedData[[1]]#%>% filter(Condition == "Pa:Sa 1:1"& Strain %in% c("PA14wt", "PA14mut"))#this may be used later
paNonSubtractResults<-nonSubtractedData[[1]]%>% filter(Species == "Pa") 
saNonSubtractResults<-nonSubtractedData[[1]]%>% filter(Species == "Sa") 

```

```{r biomass data exploration for Sa}
#comparing the data from red subtracted 
ggplot()+
  geom_line(data=redSubtractedData[[1]]%>% filter(Species == "Pa") %>% filter(Condition == "Pa:Sa 1:1"& Strain %in% c("PA14wt", "PA14mut")), aes(x=TimePoint, y=LogTotals),color = "red", size=.2)+
  geom_line(data=nonSubtractedData[[1]]%>% filter(Species == "Pa") %>% filter(Condition == "Pa:Sa 1:1"& Strain %in% c("PA14wt", "PA14mut")), aes(x=TimePoint, y=LogTotals),color ="blue", size=.2)+
  facet_grid(Strain~Sample)+
  theme_cowplot(12)
#the numbers for Pa after subracting Sa dont really change, so it should be fine.

ggplot()+#this is a summary of Pa Data for all replicates
  geom_line(data=redSubtractedData[[2]]%>% filter(Species == "Pa") %>% 
              filter(Condition == "Pa:Sa 1:1"& Strain %in% c("PA14wt", "PA14mut")), aes(x=TimePoint, y=MeanLogTotals,color = Strain), size=2)+
  theme_cowplot(12)

#Compare biomass of Staph wt vs mutant from replicates
saRedSubtractResults1<-saRedSubtractResults %>% ungroup() %>% group_by(Sample, TimePoint) %>% 
  mutate (mutantAbsDifference = (abs(Totals -Totals[Strain == "PA14mut"])/Totals )) %>% 
  mutate (mutantRatio = (Totals[Strain == "PA14mut"])/Totals ) %>% ungroup() %>% 
  group_by(Strain, TimePoint) %>% mutate (repDifference1.2 = (abs(Totals[Sample == "rep1"] -Totals[Sample == "rep2"]))/Totals[Sample == "rep2"]) %>% 
  mutate (repDifference2.3 = (abs(Totals[Sample == "rep2"] -Totals[Sample == "rep3"]))/Totals[Sample == "rep3"] ) %>% 
  mutate (repDifference1.3 = (abs(Totals[Sample == "rep1"] -Totals[Sample == "rep3"]))/Totals[Sample == "rep3"] ) %>% ungroup()
  
tidysaRedSubtractResults1<-saRedSubtractResults1 %>% gather(Comparison, Difference, -TimePoint, -Sample, -Strain, -Condition, -Species, -Totals, -LogTotals) %>% filter(!Difference == 0)

ggplot()+#plotting the absolute difference between replicates and strains
  geom_point(data = tidysaRedSubtractResults1 %>% filter(!Comparison=="mutantRatio"),
              aes(x=TimePoint,y=Difference, color = Comparison, shape = Strain),size=3, height = 0, width = .2)+
  labs(title ="Variance comparison between strains and replicates")+
  scale_y_log10(breaks = scales::trans_breaks("log10", function(x) 10^x), labels = scales::trans_format("log10", scales::math_format(10^.x)))+
  theme_cowplot()+
  theme(plot.title = element_text(hjust = 0.5))

ggplot()+#plotting the absolute difference between strains only
  geom_jitter(data = tidysaRedSubtractResults1 %>% filter(Comparison=="mutantRatio") %>% filter(!Difference == 1),
              aes(x=TimePoint,y=Difference, color = Comparison, shape = Sample),size=3, height = 0, width = .2)+
  labs(title ="Variance comparison mutant/wt")+
  scale_y_log10(breaks = c(0.5,.25,1,2.5,5,10))+#breaks = scales::trans_breaks("log10", function(x) 10^x), labels = scales::trans_format("log10", scales::math_format(10^.x)))+
  theme_cowplot()+
  theme(plot.title = element_text(hjust = 0.5))
```
#Reading aggregate data
```{r new threshold images aggregates functions and data collection}
ReadAggregateFile<-function(file, position, timepoint){#This function outputs total number of pixels in the csv file from matlab 
  datos <-read.csv(file, header = TRUE) 
  colnames(datos)<-c('Size', 'Species')
  datos<-datos %>% mutate(Position = position)
  datos<-datos %>% mutate(TimePoint = timepoint)
  return(datos)
}
 
#!!! two versions of the following function, one is for red subtract and the other one for the rest.
GetAggregates<-function(sample, samplename){#iterate through files in folder
  folder<- paste0('/Users/jupabago/Documents/Whiteley/PROJECTS/PaSaProject/Spatial paper Data/Microscopy Data/Other Data1/', sample, '/aggregateSizes1')
  fileList<-list.files(path = folder, full.names = TRUE)
  growthDf<-data.frame()
  for (position in 0:2){#only positions that are used
    currentPosition<-fileList[grep(paste0("p_",position,"."),fileList)]
    for (timepoint in 0:6){#only important time points
      currentTimePoint<-currentPosition[grep(paste0("t_",GetNumber(timepoint),"p_"),currentPosition)]
      growthDf<-rbind(growthDf,ReadAggregateFile(currentTimePoint, position, timepoint))
      }
  }
  growthDf<-growthDf %>% mutate(Sample = samplename)
return(growthDf)
}

MapAggregates<- function(listSamples, reps){#run it for all the samples
  mappedData<-map2(listSamples, reps, GetAggregates) 
  boundData<-bind_rows(mappedData) 
  blah <-deparse(substitute(listSamples)) 
  boundData<-boundData %>% mutate(Strain = blah)#needs to be two lines, it doesnt work if you do it directly
  return(boundData)
  } 

wtAggregates1<-MapAggregates(PA14wt, names3)
mutAggregates1<-MapAggregates(PA14mut, names3)
allAggregates<-bind_rows(wtAggregates1,mutAggregates1)
allAggregatesClean<-allAggregates %>% filter(!Size<0.5) %>% filter(!(Position==1 & Species=="Sa")) %>% filter(!(Position==0 & Species=="Pa"))%>% filter(!Species =="")#for some reason there are a bunch of "aggregates with no species, it may be a way in which the files are being handled.

#allAggregatesClean1<-allAggregates %>% filter(!Species =="")%>% filter(!(Position==1 & Species=="Sa")) %>% filter(!(Position==0 & Species=="Pa"))#this is only to check for smaller aggregates biomass

#quick evaluation of how much biomass is lost when you remove aggregates smaller than 0.5 um3:
biomassInAllAggs<-allAggregatesClean1 %>% group_by(Species, Position, TimePoint, Strain) %>% summarise(Biomass = sum(Size))
biomassIn0.5Aggs<-allAggregatesClean %>% group_by(Species, Position, TimePoint, Strain) %>% summarise(Biomass = sum(Size))
biomassAggsComparison<-combine(biomassInAllAggs,biomassIn0.5Aggs)
ggplot()+
  geom_point(data = biomassAggsComparison,aes(x=TimePoint,y=Biomass, color = source, shape =Strain ),size=4)+
  facet_grid(~Species)+
  scale_y_log10(breaks = scales::trans_breaks("log10", function(x) 10^x), labels = scales::trans_format("log10", scales::math_format(10^.x)))+
  theme_cowplot()+
  theme(plot.title = element_text(hjust = 0.5))
#so only a modest change in biomass, so it shouldnt be a problem.

#now make them all factors
allAggregatesClean$Strain<-as.factor(allAggregatesClean$Strain)
allAggregatesClean$Species<-as.factor(allAggregatesClean$Species)
allAggregatesClean$Sample<-as.factor(allAggregatesClean$Sample)
allAggregatesClean$TimePoint<-as.factor(allAggregatesClean$TimePoint)
allAggregatesClean$Position<-as.factor(allAggregatesClean$Position)
allAggregatesClean<-allAggregatesClean %>% mutate(Condition = recode(Position, "0" = "Sa Mono", "1" = "Pa Mono", "2" = "Pa:Sa 1:1", "3" = "Pa:Sa 10:1", "4" = "Pa:Sa 1:100", "5" = "Pa:Sa 1:10" ))

#redSubtract aggregates you have to change the "getAggregates function
#!!! this is the second version of the function
GetAggregates<-function(sample, samplename){#iterate through files in folder
  folder<- paste0('/Users/jupabago/Documents/Whiteley/PROJECTS/PaSaProject/Spatial paper Data/Microscopy Data/Other Data1/', sample, '/aggregateSizesRedSubtract')
  fileList<-list.files(path = folder, full.names = TRUE)
  growthDf<-data.frame()
  position =2#red subtract only
    currentPosition<-fileList[grep(paste0("p2"),fileList)]#only for red subtract
    for (timepoint in 0:6){#only important time points
      currentTimePoint<-currentPosition[grep(paste0("t",GetNumber(timepoint),"_p2"),currentPosition)]#this is for pa red subtract only
      growthDf<-rbind(growthDf,ReadAggregateFile(currentTimePoint, position, timepoint))
  }
  growthDf<-growthDf %>% mutate(Sample = samplename)
return(growthDf)
}

wtAggregates<-MapAggregates(PA14wt, names3)
mutAggregates<-MapAggregates(PA14mut, names3)
allAggregatesredSubtract<-bind_rows(wtAggregates,mutAggregates)
allAggregatesredSubtractClean<-allAggregatesredSubtract %>% filter(!Size<0.5) %>% filter(!(Position==1 & Species=="Sa")) %>% filter(!(Position==0 & Species=="Pa"))%>% filter(!Species =="")#for some reason there are a bunch of "aggregates with no species, it may be a way in which the files are being handled.

#also for the redsubtract
allAggregatesredSubtractClean$Strain<-as.factor(allAggregatesredSubtractClean$Strain)
allAggregatesredSubtractClean$Species<-as.factor(allAggregatesredSubtractClean$Species)
allAggregatesredSubtractClean$Sample<-as.factor(allAggregatesredSubtractClean$Sample)
allAggregatesredSubtractClean$TimePoint<-as.factor(allAggregatesredSubtractClean$TimePoint)
allAggregatesredSubtractClean$Position<-as.factor(allAggregatesredSubtractClean$Position)
allAggregatesredSubtractClean<-allAggregatesredSubtractClean %>% mutate(Condition = recode(Position, "0" = "Sa Mono", "1" = "Pa Mono", "2" = "Pa:Sa 1:1", "3" = "Pa:Sa 10:1", "4" = "Pa:Sa 1:100", "5" = "Pa:Sa 1:10" ))
```
At this point I have 2 dataframes with aggregate data: allAggregatesredSubtractClean and allAggregatesClean, so now I have to merge them properly.
```{r agggregates stats and plots, include=FALSE}
removeNonRedSubtractData<- allAggregatesClean %>% filter(!Condition == "Pa:Sa 1:1")#remove Pa:Sa 1:1 condition
combinedRedSubtractData<-bind_rows(removeNonRedSubtractData,allAggregatesredSubtractClean)

combinedRedSubtractData$Condition<-as.factor(combinedRedSubtractData$Condition)
combinedRedSubtractData$Species<-as.factor(combinedRedSubtractData$Species)
combinedRedSubtractData$Position<-as.factor(combinedRedSubtractData$Position)
#I have to do this because the data frames had different number of factors on those columns...

#get some stats on aggregates
allAggregateDataSummary<-combinedRedSubtractData %>% group_by(Species,Condition, TimePoint, Sample, Strain) %>% summarise(Aggs = n(), biomass = sum(Size), meanAggSize = mean(Size), seAggSize = std.error(Size), maxSize = max(Size), minSize = min(Size)) %>% ungroup() %>% mutate(RatioMaxTotal = maxSize/biomass ) %>% mutate(ConditionNew = recode(Condition, "Sa Mono" = "Mono", "Pa Mono" = "Mono","Pa:Sa 1:1" = "Co"))

#Summary figure for total aggregate numbers
ggplot()+
  geom_jitter(data = allAggregateDataSummary, aes(x = TimePoint, y= Aggs, color = Species, shape = Strain), width = 0, height = 0)+
  geom_smooth(data = allAggregateDataSummary, aes(x = TimePoint, y= Aggs, color = Species, linetype = Strain, group = interaction(Species, Strain)))+
  facet_wrap(.~Condition)+
  scale_y_continuous(limits= c(0,1e4))+
  ggtitle('Number of aggregates per experiment')+
  labs(x = "Time (hours)",y = "Number of Aggregates")+
  theme_cowplot()+
  theme(plot.title = element_text(hjust = 0.5))

#now we filter for only the time point that we care, which is hour 5:
aggregatesDataTime5wt<- allAggregateDataSummary %>% filter (TimePoint == 5) %>% filter(Strain=="PA14wt")
aggregatesDataTime5mut<- allAggregateDataSummary %>% filter (TimePoint == 5) %>% filter(Strain=="PA14mut")

#this is a decent outline of the aggregates data
ggplot()+#for wt
  geom_point(data = aggregatesDataTime5wt, aes(x = ConditionNew, y= meanAggSize, color = Species,shape = "MeanSize"))+
  geom_point(data = aggregatesDataTime5wt, aes(x = ConditionNew, y= maxSize, color = Species, shape = "MaxSize"))+
  geom_point(data = aggregatesDataTime5wt, aes(x = ConditionNew, y= biomass, color = Species, shape = "TotalBiomass"))+  
  facet_wrap(Species~.)+
  scale_y_log10( breaks = scales::trans_breaks("log10", function(x) 10^x), labels = scales::trans_format("log10", scales::math_format(10^.x)))+
  ggtitle('Aggregates: Mean, largest and total biomass (wild type)')+
  labs(x = "",y = "Aggregate size (um3)")+
  scale_shape_manual(name="Metric",values=c(MeanSize=1, MaxSize=2, TotalBiomass=17))+
  theme_cowplot()+
  theme(plot.title = element_text(hjust = 0.5))

ggplot()+#for mutant
  geom_point(data = aggregatesDataTime5mut, aes(x = ConditionNew, y= meanAggSize, color = Species,shape = "MeanSize"))+
  geom_point(data = aggregatesDataTime5mut, aes(x = ConditionNew, y= maxSize, color = Species, shape = "MaxSize"))+
  geom_point(data = aggregatesDataTime5mut, aes(x = ConditionNew, y= biomass, color = Species, shape = "TotalBiomass"))+  
  facet_wrap(Species~.)+
  scale_y_log10( breaks = scales::trans_breaks("log10", function(x) 10^x), labels = scales::trans_format("log10", scales::math_format(10^.x)))+
  ggtitle('Aggregates: Mean, largest and total biomass (pqsL mutant)')+
  labs(x = "",y = "um3")+
  scale_shape_manual(name="Metric",values=c(MeanSize=1, MaxSize=2, TotalBiomass=17))+
  theme_cowplot()+
  theme(plot.title = element_text(hjust = 0.5))


#now do only average aggregate size:
#wild type
ggplot()+
  geom_point(data = aggregatesDataTime5wt, aes(x = ConditionNew, y= meanAggSize, shape = Sample))+
  geom_errorbar(data = aggregatesDataTime5wt, aes(x = ConditionNew, ymin= meanAggSize-seAggSize,ymax= meanAggSize+seAggSize))+
  facet_grid(~Species, space = "free")+
  scale_y_log10( breaks = scales::trans_breaks("log10", function(x) 10^x), labels = scales::trans_format("log10", scales::math_format(10^.x)))+
  ggtitle('Mean Aggregate size per sample (wt)')+
  labs(x = "",y = "Aggregate size (um3)")+
  theme_cowplot()+
  theme(plot.title = element_text(hjust = 0.5))
#mutant
ggplot()+
  geom_point(data = aggregatesDataTime5mut, aes(x = ConditionNew, y= meanAggSize, shape = Sample))+
  geom_errorbar(data = aggregatesDataTime5mut, aes(x = ConditionNew, ymin= meanAggSize-seAggSize,ymax= meanAggSize+seAggSize))+
  facet_grid(~Species, space = "free")+
  scale_y_log10( breaks = scales::trans_breaks("log10", function(x) 10^x), labels = scales::trans_format("log10", scales::math_format(10^.x)))+
  ggtitle('Mean Aggregate size per sample (pqsL)')+
  labs(x = "",y = "um3")+
  theme_cowplot()+
  theme(plot.title = element_text(hjust = 0.5))

#very interesting...now do stats

aggregatesDataTime5mutStats<-aggregatesDataTime5mut %>% group_by (Species,ConditionNew, Strain) %>% 
  summarise(MeanAggs = mean(Aggs), SEAggs = std.error(Aggs), 
            MeanBiomass = mean(biomass),SEBiomass = std.error(biomass), 
            MeanAggSize = mean(meanAggSize), SEAggSize = std.error(meanAggSize))

aggregatesDataTime5wtStats<-aggregatesDataTime5wt %>% group_by (Species,ConditionNew, Strain) %>% 
  summarise(MeanAggs = mean(Aggs), SEAggs = std.error(Aggs), 
            MeanBiomass = mean(biomass),SEBiomass = std.error(biomass), 
            MeanAggSize = mean(meanAggSize), SEAggSize = std.error(meanAggSize))
```
#Mean Agregate size figure
```{r aggregate mean volume final figures}
#final figures potentially for paper

MeanAggSizeWtPlot<-ggplot()+
  geom_jitter(data = aggregatesDataTime5wt, aes(x = ConditionNew, y= meanAggSize), size = 1, height = 0, width = .3, shape = 1)+
  geom_point(data = aggregatesDataTime5wtStats, aes(x = ConditionNew, y= MeanAggSize), size = 3, shape = 16)+
  geom_errorbar(data = aggregatesDataTime5wtStats, aes(x = ConditionNew, ymin= MeanAggSize-SEAggSize,ymax= MeanAggSize+SEAggSize), width = .5)+
  facet_grid(~Species, space = "free")+
  scale_y_log10( limits = c(1e0,1e2))+
  ggtitle('Aggregate size (wild type)')+
  labs(x = "",y = bquote(paste("Aggregate Volume (", mu*"m"^3*")")))+
  theme_cowplot()+
  theme(plot.title = element_text(hjust = 0.5))

MeanAggSizeMutPlot<-ggplot()+
  geom_jitter(data = aggregatesDataTime5mut, aes(x = ConditionNew, y= meanAggSize), size = 1, height = 0, width = .3, shape = 1)+
  geom_point(data = aggregatesDataTime5mutStats, aes(x = ConditionNew, y= MeanAggSize), size = 3, shape = 16)+
  geom_errorbar(data = aggregatesDataTime5mutStats, aes(x = ConditionNew, ymin= MeanAggSize-SEAggSize,ymax= MeanAggSize+SEAggSize), width = .5)+
  facet_grid(~Species, space = "free")+
  #scale_y_log10( breaks = scales::trans_breaks("log10", function(x) 10^x), labels = scales::trans_format("log10", scales::math_format(10^.x)), limits = c(1e0,1e2))+
  scale_y_log10( limits = c(1e0,1e2))+
  ggtitle('Aggregate size (pqsL mutant)')+
  labs(x = "",y = bquote(paste("Aggregate Volume (", mu*"m"^3*")")))+
  theme_cowplot()+
  theme(plot.title = element_text(hjust = 0.5))
```

```{r aggregates extra metrics calculated}

#this led me to introduce another metric: ratio of largest aggregate to total biomass
allDataSummary<-allDataSummary %>% mutate(RatioMaxTotal = maxSize/biomass )

ggplot()+
  geom_jitter(data = allDataSummary, aes(x = TimePoint, y= RatioMaxTotal, color = Species, shape = Strain), width = 0, height = 0)+
  geom_hline(yintercept=1, linetype = "dashed")+
  geom_smooth(data = allDataSummary, aes(x = TimePoint, y= RatioMaxTotal, color = Species, linetype = Strain, group = interaction(Species, Strain)))+
  facet_wrap(.~Condition)+
  ggtitle('Ratio of largest aggregate to total biomass')+
  labs(x = "Time (hours)",y = "Proportion of largest aggregate to total biomass")
#this seems to have a lot of noise, how does that compare to actual biomass?
ggplot()+
  geom_jitter(data = allDataSummary, aes(x = TimePoint, y= biomass, color = Species, shape = Strain), width = 0, height = 0)+
  geom_smooth(data = allDataSummary, aes(x = TimePoint, y= biomass, color = Species, linetype = Strain, group = interaction(Species, Strain)))+
  scale_y_log10( breaks = scales::trans_breaks("log10", function(x) 10^x), labels = scales::trans_format("log10", scales::math_format(10^.x)))+
  facet_wrap(.~Condition)+
  ggtitle("Total biomass")+
  labs(x = "Time (hours)",y = "Total biomass")
```

#Aggregate histograms
```{r Aggregate histograms functions}
FancyHistogram<-function(df, sec){#my own way of doing histograms which includes the sum and mean of values whitin each bin
  results<-data.frame()
  for( i in 1:(length(sec)-1)){ 
    df %>% filter(Size > sec[i] &Size<=sec[i+1])%>%summarise(frequency = n(), avg = mean(Size),suma = sum(Size)) %>% mutate(bin = i, min = sec[i],max = sec[i+1])->blah
    if(blah$frequency>0){ 
    results<-rbind(results, blah)} 
  }
  return(results) 
  }
TotalFancyHistogram<-function(df,binsize){
  totalbiomass<-sum(df$Size)#total biomass per sample
  totalfrequency<-length(df$Size)#total number of objects
  upperLim<-max(df$Size)+binsize-(max(df$Size)%%binsize)#largest bin size based in largest object
  breaksSequence<-seq(0,upperLim,binsize)#this makes breaks every "binsize" 
  histogram<-FancyHistogram(df,breaksSequence)#apply "fancy histogram" to get distributions
  histogram%>%mutate(BiomassBin=suma/totalbiomass)->histogram#add column with proportion of biomas per bin
  histogram%>%mutate(Density=frequency/totalfrequency)->histogram#add column with proportion of counts per bin
  histogram%>%mutate(Species=df$Species[1])->histogram#add column maintaining sample and so on...
  histogram%>%mutate(Condition=df$Condition[1])->histogram
  histogram%>%mutate(TimePoint=df$TimePoint[1])->histogram
  histogram%>%mutate(Sample=df$Sample[1])->histogram
  histogram%>%mutate(Strain=df$Strain[1])->histogram
  return(histogram)
}
TotalHistogram<-function(df){
  biomass<-df$Size
  totalbiomass<-sum(biomass)
  upperLim<-max(biomass)+5-mod(max(biomass),5)
  breaksSequence<-seq(0,upperLim,5)#this makes breaks every 100 pixels
  histogram<-data.frame()
  currentHist<-hist(biomass, plot = F, breaks = breaksSequence)
  histogram<-data.frame(currentHist$counts,currentHist$mids)
  colnames(histogram)<-c("Counts", "Midpoint")
  histogram<-histogram[!(histogram$Counts==0),]#remove zeros
  histogram%>%mutate(BiomassBin=Counts*Midpoint)->histogram
  histogram%>%mutate(NormBiomassBin=BiomassBin/totalbiomass)->histogram
  return(histogram)
}

##This is done just once, afterwards I just pull them up from the csv file since it takes some time to get them.
#group them to get histograms for each experimental condition
allData<-allAggregates1 %>% group_by(Species, Condition, TimePoint, Sample, Strain)#first do the correct grouping
aggregatesList<- group_split(allData)#create list of dataframes
allDataHistograms.5<-map2(aggregatesList, 5,TotalFancyHistogram)#apply histogram function to all items in the list
allDataHistograms.10<-map2(aggregatesList, 10,TotalFancyHistogram)#apply histogram function to all items in the list
allDataHistograms.50<-map2(aggregatesList, 50,TotalFancyHistogram)#apply histogram function to all items in the list
allDataHistograms.100<-map2(aggregatesList, 100,TotalFancyHistogram)#apply histogram function to all items in the list

allDataHistograms.5df<- bind_rows(allDataHistograms.5)
allDataHistograms.10df<- bind_rows(allDataHistograms.10)
allDataHistograms.50df<- bind_rows(allDataHistograms.50)
allDataHistograms.100df<- bind_rows(allDataHistograms.100)

write.csv(allDataHistograms.5df, file = '/Users/jupabago/Documents/Whiteley/PROJECTS/Spatial paper Data/Microscopy Data/Histograms1/histograms5.csv')
write.csv(allDataHistograms.10df,file = '/Users/jupabago/Documents/Whiteley/PROJECTS/Spatial paper Data/Microscopy Data/Histograms1/histograms10.csv')
write.csv(allDataHistograms.50df,file = '/Users/jupabago/Documents/Whiteley/PROJECTS/Spatial paper Data/Microscopy Data/Histograms1/histograms50.csv')
write.csv(allDataHistograms.100df,file = '/Users/jupabago/Documents/Whiteley/PROJECTS/Spatial paper Data/Microscopy Data/Histograms1/histograms100.csv')
```

```{r Aggregate histograms plots}
allDataHistograms.5df<-read.csv(file='/Users/jupabago/Documents/Whiteley/PROJECTS/PaSaProject/Spatial paper Data/Microscopy Data/Histograms1/histograms5.csv',header=T)
allDataHistograms.10df<-read.csv(file='/Users/jupabago/Documents/Whiteley/PROJECTS/PaSaProject/Spatial paper Data/Microscopy Data/Histograms1/histograms10.csv',header=T)
allDataHistograms.50df<-read.csv(file='/Users/jupabago/Documents/Whiteley/PROJECTS/PaSaProject/Spatial paper Data/Microscopy Data/Histograms1/histograms50.csv',header=T)
allDataHistograms.100df<-read.csv(file='/Users/jupabago/Documents/Whiteley/PROJECTS/PaSaProject/Spatial paper Data/Microscopy Data/Histograms1/histograms100.csv',header=T)

hist.100<-allDataHistograms.100df %>% filter(TimePoint== 5) %>% filter( Condition %in% c("Sa Mono", "Pa Mono", "Pa:Sa 1:1")) %>% mutate(ConditionNew = recode(Condition, "Sa Mono" = "Mono", "Pa Mono" = "Mono", "Pa:Sa 1:1" = "Co"))
hist.5 <- allDataHistograms.5df %>% filter(TimePoint== 5) %>% filter( Condition %in% c("Sa Mono", "Pa Mono", "Pa:Sa 1:1")) %>% mutate(ConditionNew = recode(Condition, "Sa Mono" = "Mono", "Pa Mono" = "Mono", "Pa:Sa 1:1" = "Co"))

#ok so I am going to try to do this...I can't do bar graphs because the width of the bars is too thin to be able to be seen by the viewer, so I am doing points
#I also want to do mono and co pointing to opposite sides, but I haven't been able to do it with recode, so I'll manually do it.
cleanHist.5<-hist.5 %>% group_by(max, Species, ConditionNew, Strain) %>% summarise(Frequency = sum(frequency))#Combine aggregates from all 3 samples
meancleanHist.5<-hist.5 %>% group_by(max, Species, ConditionNew, Strain) %>% summarise(MeanFrequency = mean(frequency))#mean aggregates from all 3 samples
cleanHist.100<-hist.100 %>% group_by(max, Species, ConditionNew, Strain) %>% summarise(Frequency = sum(frequency))
meancleanHist.100<-hist.100 %>% group_by(max, Species, ConditionNew, Strain) %>% summarise(MeanFrequency = mean(frequency))
#However, one thing I want to try is to have different aggregate cutoffs... have 5 um bins up to 100um and then have the rest of the bins at 100 um3, so..
only5Hist<- cleanHist.5 %>% filter (max<=100)
only100Hist<- cleanHist.100 %>% filter (max>100)
bin5and100Hist<-bind_rows(only5Hist,only100Hist)

meanOnly5Hist<- meancleanHist.5 %>% filter (max<=100)
meanOnly100Hist<- meancleanHist.100 %>% filter (max>100)
meanBin5and100Hist<-bind_rows(meanOnly5Hist,meanOnly100Hist)


#function for negative log
reverselog_trans <- function(base = exp(1)) {#dont know exactly how this works, but it does... 
    trans <- function(x) -log(x, base)
    inv <- function(x) base^(-x)
    trans_new(paste0("reverselog-", format(base)), trans, inv, 
              log_breaks(base = base), 
              domain = c(1e-100, Inf))
}

plotButterfly<-function (species, strain){
monoPlot<-ggplot()+
  geom_point(data = bin5and100Hist %>% filter(ConditionNew == "Mono"& Strain == strain & Species == species),
             aes(x = max, y= Frequency), size = 2, shape = 1)+
  scale_y_continuous(trans=reverselog_trans(base=10),
                     labels=trans_format("log10", scales::math_format(10^.x)))+
  scale_x_log10(breaks = scales::trans_breaks("log10", function(x) 10^x), labels = scales::trans_format("log10", scales::math_format(10^.x)),limits = c(1e0,2e5), position = "top")+
  coord_flip()+
  xlab("")+
  ylab("Frequency")+
  theme_cowplot()+
  theme(plot.title = element_text(hjust = 0.5))

coPlot<-ggplot()+
  geom_point(data = bin5and100Hist %>% filter(ConditionNew == "Co"& Strain == strain & Species == species),
             aes(x = max, y= Frequency),shape = 1, size = 2)+
  scale_y_log10(breaks = scales::trans_breaks("log10", function(x) 10^x), labels = scales::trans_format("log10", scales::math_format(10^.x)),limits = c(1e0,2e4))+
  scale_x_log10(breaks = scales::trans_breaks("log10", function(x) 10^x), labels = scales::trans_format("log10", scales::math_format(10^.x)),limits = c(1e0,2e5))+
  coord_flip()+
  xlab("")+
  ylab("Frequency")+
  theme_cowplot()+
  theme(plot.title = element_text(hjust = 0.5), axis.text.y=element_blank())

plot_grid(monoPlot+ theme(plot.margin = unit(c(1, -1.1, 0, 0), "cm")),coPlot+ theme(plot.margin = unit(c(1, 2, 0, 0), "cm")), align='vh', axis = "l",labels = c("Mono-culture", "Co-culture"),hjust = c(-1, -1.8),nrow = 1)
}
plotButterfly("Sa", "PA14wt")
plotButterfly("Sa", "PA14mut")
plotButterfly("Pa", "PA14wt")
plotButterfly("Pa", "PA14mut")

#showed this to Dan, and he didnt like them =( so I'll just do them the boring old way)
plotNonButterfly<-function (df,species, strain){
monoPlot<-ggplot()+
  geom_point(data = df %>% filter(ConditionNew == "Mono"& Strain == strain & Species == species),
             aes(x = max, y= Frequency), size = 2, shape = 1)+
  #scale_y_log10(breaks = scales::trans_breaks("log10", function(x) 10^x), labels = scales::trans_format("log10", scales::math_format(10^.x)),limits = c(1e0,2e4))+
  scale_y_log10(breaks = c(1, 10, 100, 1000, 10000), labels = c("1", "10", "100", "1,000", "10,000"),limits = c(1e0,2e4))+
  scale_x_log10(breaks = scales::trans_breaks("log10", function(x) 10^x), labels = scales::trans_format("log10", scales::math_format(10^.x)),limits = c(1e0,2e5))+
  labs(y = "Frequency",x = bquote(paste("Aggregate Volume (", mu*"m"^3*")")))+
  theme_cowplot()+
  theme(plot.title = element_text(hjust = 0.5))

coPlot<-ggplot()+
  geom_point(data = df %>% filter(ConditionNew == "Co"& Strain == strain & Species == species),
             aes(x = max, y= Frequency),shape = 1, size = 2)+
  #scale_y_log10(breaks = scales::trans_breaks("log10", function(x) 10^x), labels = scales::trans_format("log10", scales::math_format(10^.x)),limits = c(1e0,2e4))+
  scale_y_log10(breaks = c(1, 10, 100, 1000, 10000), labels = c("1", "10", "100", "1,000", "10,000"),limits = c(1e0,2e4))+
  scale_x_log10(breaks = scales::trans_breaks("log10", function(x) 10^x), labels = scales::trans_format("log10", scales::math_format(10^.x)),limits = c(1e0,2e5))+
  labs(y = "",x = bquote(paste("Aggregate Volume (", mu*"m"^3*")")))+
  theme_cowplot()+
  theme(plot.title = element_text(hjust = 0.5))

plot_grid(monoPlot+ theme(plot.margin = unit(c(1, 0, 0, 0), "cm")),coPlot+ theme(plot.margin = unit(c(1, 1, 0, 0), "cm")), align='vh', axis = "l",labels = c("Mono-culture", "Co-culture"),hjust = c(-1.4, -1.9),nrow = 1)
}
plotNonButterfly(only5Hist,"Sa", "PA14wt")
plotNonButterfly(only5Hist,"Sa", "PA14mut")
plotNonButterfly(only5Hist,"Pa", "PA14wt")
plotNonButterfly(only5Hist, "Pa", "PA14mut")

plotNonButterfly(bin5and100Hist,"Sa", "PA14wt")
plotNonButterfly(bin5and100Hist,"Sa", "PA14mut")
plotNonButterfly(bin5and100Hist,"Pa", "PA14wt")
plotNonButterfly(bin5and100Hist, "Pa", "PA14mut")
```
```{r Aggregate histograms planktonic vs aggregte}

#this is the summary beacuse I dont like further analyzing data after summarizing shit, so mutate at the top follows 
hist.plank.Agg.Sumary<-hist.5 %>%  group_by(Species, Sample,Condition,Strain)%>% 
  mutate(Aggregation = case_when(max == 5 ~ "Planktonic",
                        max>5 ~ "Aggregate")) %>% ungroup() %>% group_by(Species,Sample,Condition,ConditionNew, Strain,Aggregation) %>% summarize(FrequencyAggregation = sum(frequency), BiomassAggregation = sum(BiomassBin), DensityAggregation = sum(Density))


#now I have to do some t-tests, since I used the same cultures for mono and co for each replicate, paired t-tests are allowed.
##### 
#I know this sucks, but it's 1 AM so idgaf
SaMonoWtAggSum<-hist.plank.Agg.Sumary %>%filter(Condition == "Sa Mono", Strain == "PA14wt",Aggregation == "Aggregate") %>% pull(BiomassAggregation)
SaMonoWtPlankSum<-hist.plank.Agg.Sumary %>%filter(Condition == "Sa Mono", Strain == "PA14wt",Aggregation == "Planktonic") %>% pull(BiomassAggregation)
SaMonoMutAggSum<-hist.plank.Agg.Sumary %>%filter(Condition == "Sa Mono", Strain == "PA14mut",Aggregation == "Aggregate") %>% pull(BiomassAggregation)
SaMonoMutPlankSum<-hist.plank.Agg.Sumary %>%filter(Condition == "Sa Mono", Strain == "PA14mut",Aggregation == "Planktonic") %>% pull(BiomassAggregation)

SaCoWtAggSum<-hist.plank.Agg.Sumary %>%filter(Species =="Sa", ConditionNew == "Co", Strain == "PA14wt",Aggregation == "Aggregate") %>% pull(BiomassAggregation)
SaCoWtPlankSum<-hist.plank.Agg.Sumary %>%filter(Species =="Sa", ConditionNew == "Co", Strain == "PA14wt",Aggregation == "Planktonic") %>% pull(BiomassAggregation)
SaCoMutAggSum<-hist.plank.Agg.Sumary %>%filter(Species == "Sa", ConditionNew == "Co", Strain == "PA14mut",Aggregation == "Aggregate") %>% pull(BiomassAggregation)
SaCoMutPlankSum<-hist.plank.Agg.Sumary %>%filter(Species == "Sa", ConditionNew == "Co", Strain == "PA14mut",Aggregation == "Planktonic") %>% pull(BiomassAggregation)

#mono vs Co
SaWtAggTest<-t.test(x = SaMonoWtAggSum, y = SaCoWtAggSum, paired = T)#wt
SaMutAggTest<-t.test(x = SaMonoMutAggSum, y = SaCoMutAggSum, paired = T)#mutant
#Plank vs Agg
SaMonoWtAggVsPlankTest<-t.test(x = SaMonoWtAggSum, y = SaMonoWtPlankSum, paired = T)#wt
SaMonoMutAggVsPlankTest<-t.test(x = SaMonoMutAggSum, y = SaMonoMutPlankSum, paired = T)#mutant
SaCoWtAggVsPlankTest<-t.test(x = SaCoWtAggSum, y = SaCoWtPlankSum, paired = T)#wt
SaCoMutAggVsPlankTest<-t.test(x = SaCoMutAggSum, y = SaCoMutPlankSum, paired = T)#mutant
#wt vs mutant
SaMonoWtVsMutAggTest<-t.test(x = SaMonoWtAggSum, y = SaMonoMutAggSum, paired = F)
SaCoWtVsMutAggTest<-t.test(x = SaCoWtAggSum, y = SaCoMutAggSum, paired = F)


PaMonoWtAggSum<-hist.plank.Agg.Sumary %>%filter(Condition == "Pa Mono", Strain == "PA14wt",Aggregation == "Aggregate") %>% pull(BiomassAggregation)
PaCoWtAggSum<-hist.plank.Agg.Sumary %>%filter(Species == "Pa", ConditionNew == "Co", Strain == "PA14wt",Aggregation == "Aggregate") %>% pull(BiomassAggregation)
PaMonoMutAggSum<-hist.plank.Agg.Sumary %>%filter(Condition == "Pa Mono", Strain == "PA14mut",Aggregation == "Aggregate") %>% pull(BiomassAggregation)
PaCoMutAggSum<-hist.plank.Agg.Sumary %>%filter(Species == "Pa", ConditionNew == "Co", Strain == "PA14mut",Aggregation == "Aggregate") %>% pull(BiomassAggregation)

PaMonoWtPlankSum<-hist.plank.Agg.Sumary %>%filter(Condition == "Pa Mono", Strain == "PA14wt",Aggregation == "Planktonic") %>% pull(BiomassAggregation)
PaCoWtPlankSum<-hist.plank.Agg.Sumary %>%filter(Species == "Pa", ConditionNew == "Co", Strain == "PA14wt",Aggregation == "Planktonic") %>% pull(BiomassAggregation)
PaMonoMutPlankSum<-hist.plank.Agg.Sumary %>%filter(Condition == "Pa Mono", Strain == "PA14mut",Aggregation == "Planktonic") %>% pull(BiomassAggregation)
PaCoMutPlankSum<-hist.plank.Agg.Sumary %>%filter(Species == "Pa", ConditionNew == "Co", Strain == "PA14mut",Aggregation == "Planktonic") %>% pull(BiomassAggregation)

PaWtAggTest<-t.test(x = PaMonoWtAggSum, y = PaCoWtAggSum, paired = T)
PaMutAggTest<-t.test(x = PaMonoMutAggSum, y = PaCoMutAggSum, paired = T)
PaMonoWtVsMutAggTest<-t.test(x = PaMonoWtAggSum, y = PaMonoMutAggSum, paired = F)
PaCoWtVsMutAggTest<-t.test(x = PaCoWtAggSum, y = PaCoMutAggSum, paired = F)

PaMonoWtAggVsPlankTest<-t.test(x = PaMonoWtAggSum, y = PaMonoWtPlankSum, paired = T)
PaCoWtAggVsPlankTest<-t.test(x = PaCoWtAggSum, y = PaCoWtPlankSum, paired = T)
PaMonoMutAggVsPlankTest<-t.test(x = PaMonoMutAggSum, y = PaMonoMutPlankSum, paired = T)
PaCoMutAggVsPlankTest<-t.test(x = PaCoMutAggSum, y = PaCoMutPlankSum, paired = T)



tTestDataAggvsPlank<-list(SaWtAggTest,SaMutAggTest,SaMonoWtAggVsPlankTest,SaMonoMutAggVsPlankTest,
                          SaCoWtAggVsPlankTest,SaCoMutAggVsPlankTest,SaMonoWtVsMutAggTest,SaCoWtVsMutAggTest,
                          PaWtAggTest,PaMutAggTest,PaMonoWtAggVsPlankTest,PaMonoMutAggVsPlankTest,
                          PaCoWtAggVsPlankTest,PaCoMutAggVsPlankTest,PaMonoWtVsMutAggTest,PaCoWtVsMutAggTest)
TtestTable<-name <- function(dataPoint) {
  data <-data.frame(dataPoint$data.name, dataPoint$p.value)
}
tTestDataTable<-bind_rows(map(tTestDataAggvsPlank, TtestTable))
#so, it turns out I only had to do either agg or plank since the variance is the same. COOL...

#####
#this is using mutate which is the same as above

hist.plank.Agg.Stats<-hist.plank.Agg.Sumary %>% group_by(Species,Condition, ConditionNew,Strain,Aggregation) %>%
  summarise(MeanFreq = mean(FrequencyAggregation), SEFreq = std.error(FrequencyAggregation), MeanBiomass = mean(BiomassAggregation), SEBiomass = std.error(BiomassAggregation),MeanDensity = mean(DensityAggregation), SEDensity = std.error(DensityAggregation) )


PlotAggsPlank<- function(strain, titulo){
ggplot()+
  geom_col(data = hist.plank.Agg.Stats %>% filter(Strain == strain),aes(x=ConditionNew,y=MeanBiomass, fill = Aggregation),size=3,position = position_dodge( width = .9))+
  geom_errorbar(data = hist.plank.Agg.Stats%>% filter(Strain == strain),aes(x=ConditionNew,ymin=MeanBiomass-SEBiomass, ymax = MeanBiomass+SEBiomass),size=.5,position = position_dodge2( width = .6))+
  facet_grid(.~Species)+
  labs(title = titulo, x = "", y = "Biomass contribution")+
  theme_cowplot()+
  theme(plot.title = element_text(hjust = 0.5))
}
PlotAggsPlank("PA14wt", "wt")
PlotAggsPlank("PA14mut", "pqsL")

```

```{r Aggregate histograms logarithmic bins, Figures 3 and 6}
#Now I need to do histograms with bins in a log scale, but for this I want to use the raw data that includes biomass per bin and density.
#let's start by revisiting the original data set and just filter one sample to simplify things:
#####
hist.5.rep1<-hist.5 %>% filter(Sample == "rep1"&Condition == "Pa Mono"&Strain=="PA14mut") 
hist.5.rep1.logBins<-hist.5.rep1 %>% 
  mutate(LogBin = case_when(max <= 10 ~ 10, 
                        max<= 100    ~ 100,
                        max<= 1000   ~ 1000,
                        max<= 10000  ~ 10000,
                        max<= 100000 ~ 100000,
                        max > 100000 ~ 1000000)) %>% 
  group_by(LogBin) %>% mutate(FrequencyLogBin = sum(frequency), BiomassLogBin = sum(BiomassBin), DensityLogBin = sum(Density))
#Now this is the real case
hist.5.LogBin<-hist.5 %>%  group_by(Species, Sample,Condition,Strain)%>% 
  mutate(LogBin = case_when(max <= 10 ~ 10,
                        max<= 100    ~ 100,
                        max<= 1000   ~ 1000,
                        max<= 10000  ~ 10000,
                        max<= 100000 ~ 100000,
                        max > 100000 ~ 1000000)) %>% ungroup() %>% 
  group_by(Species, Sample,Condition,Strain,LogBin) %>% mutate(FrequencyLogBin = sum(frequency), BiomassLogBin = sum(BiomassBin), DensityLogBin = sum(Density))

#this is easier to put in bar graphs
hist.5.LogBinSummarize<-hist.5 %>% filter(!max == 5)%>%  group_by(Sample,Species,Condition,Strain)%>% 
  mutate(LogBin = case_when(max <= 10 ~ 10,
                        max<= 100    ~ 100,
                        max<= 1000   ~ 1000,
                        max<= 10000  ~ 10000,
                        max<= 100000 ~ 100000,
                        max > 100000 ~ 1000000)) %>% ungroup() %>% 
  group_by(Species, Sample,Condition,ConditionNew,Strain,LogBin) %>% summarise(FrequencyLogBin = sum(frequency), BiomassLogBin = sum(BiomassBin), DensityLogBin = sum(Density))
 
PlotFreqLogBin<-function(strain, species,titulo){
  df <-hist.5.LogBinSummarize%>% filter(Strain == strain & Species == species)
  ggplot()+
    geom_col(data = df,aes(x=as.factor(LogBin),y=FrequencyLogBin,  fill =Sample ),size=4)+
    #geom_point(data = df,aes(x=as.factor(LogBin),y=FrequencyLogBin,  shape =Sample ),size=4)+
    geom_label(data = df %>% filter(Sample == "rep1"),aes(x=as.factor(LogBin),y=1, label =round(BiomassLogBin[Sample=="rep1"]*100,digits=1), color = "rep1"),size=4)+
    geom_label(data = df%>% filter(Sample == "rep2"),aes(x=as.factor(LogBin),y=.325, label =round(BiomassLogBin[Sample=="rep2"]*100,digits=1), color = "rep2"),size=4)+
    geom_label(data = df%>% filter(Sample == "rep3"),aes(x=as.factor(LogBin),y=.1, label =round(BiomassLogBin[Sample=="rep3"]*100,digits=1), color = "rep3"),size=4)+
    labs(title = titulo)+
    scale_y_log10(breaks = scales::trans_breaks("log10", function(x) 10^x), labels = scales::trans_format("log10", scales::math_format(10^.x)))+
    #scale_x_log10(breaks = scales::trans_breaks("log10", function(x) 10^x), labels = scales::trans_format("log10", scales::math_format(10^.x)))+
    facet_grid(.~ConditionNew)+
    labs(y = "Frequency",x = bquote(paste("Aggregate Volume (", mu*"m"^3*")")))+
    guides(color = FALSE)+
    theme_cowplot()+
    theme(plot.title = element_text(hjust = 0.5))
}
 #old stuff
#####

#New code as of 8-5-20: report mean frequencies and density across samples, instead of per sample.
hist.5.LogBinSummarize<-hist.5 %>% filter(!max == 5)%>%  group_by(Sample,Species,Condition,Strain)%>% 
  mutate(LogBin = case_when(max <= 10 ~ "(5, 10]",
                        max<= 100    ~ "(10, 100]",
                        max > 100 ~ paste0("(100, ",bquote("\U221E"), ")"))) %>% ungroup() %>% 
  group_by(Species, Sample,Condition,ConditionNew,Strain,LogBin) %>% summarise(FrequencyLogBin = sum(frequency), BiomassLogBin = sum(BiomassBin), DensityLogBin = sum(Density)) %>% 
  ungroup() %>% group_by(Species, Condition,ConditionNew,Strain,LogBin) %>% summarise(MeanFrequencyLogBin = mean(FrequencyLogBin),SEFrequencyLogBin = std.error(FrequencyLogBin),
                                                                                      MeanBiomassLogBin = mean(BiomassLogBin), SEBiomassLogBin = std.error(BiomassLogBin),
                                                                                      MeanDensityLogBin = mean(DensityLogBin),SEDensityLogBin = std.error(DensityLogBin)) 
hist.5.LogBinSummarize$LogBin<-as.factor(hist.5.LogBinSummarize$LogBin)
hist.5.LogBinSummarize$LogBin <- factor(hist.5.LogBinSummarize$LogBin, levels = c("(5, 10]","(10, 100]",paste0("(100, ",bquote("\U221E"), ")")))
hist.5.LogBinSummarize$Species <- factor(hist.5.LogBinSummarize$Species, levels = c("Pa", "Sa"),
                  labels = c('P. aeruginosa','S. aureus'))

PlotFreqLogBin<-function(strain,titulo){
  df <-hist.5.LogBinSummarize%>% filter(Strain == strain)
  ggplot()+
    geom_col(data = df, aes(x=LogBin,y=MeanFrequencyLogBin,  fill =ConditionNew ),size=4,position = position_dodge( width = .9))+
    geom_errorbar(data = df,aes(x=LogBin,ymin=MeanFrequencyLogBin-SEFrequencyLogBin, ymax = MeanFrequencyLogBin+SEFrequencyLogBin, group =ConditionNew ),size=.5,position = position_dodge2( width = .6))+
    #labs(title = titulo)+
    #scale_y_log10(breaks = scales::trans_breaks("log10", function(x) 10^x), labels = scales::trans_format("log10", scales::math_format(10^.x)))+
    facet_grid(.~Species)+
    labs(fill = "Condition",y = "Mean number of aggregates per Bin",x = bquote(paste("Aggregate Volume (", mu*"m"^3*")")))+
    guides(color = FALSE)+
    scale_fill_grey()+
    theme_cowplot(12)+
    theme(plot.title = element_text(hjust = 0.5),strip.text = element_text(face = "italic"))
}

PlotFreqLogBin("PA14wt", "WT")
PlotFreqLogBin("PA14mut", "pqsL")

PlotDensityLogBin<-function(strain,titulo){
  df <-hist.5.LogBinSummarize%>% filter(Strain == strain)
  ggplot()+
    geom_col(data = df, aes(x=LogBin,y=MeanBiomassLogBin*100, fill =ConditionNew),size=4,position = position_dodge( width = .9))+
    geom_errorbar(data = df,aes(x=LogBin,ymin=(MeanBiomassLogBin-SEBiomassLogBin)*100, ymax = (MeanBiomassLogBin+SEBiomassLogBin)*100, group =ConditionNew ),size=.5,position = position_dodge2( width = .6))+
    #labs(title = titulo)+
    #scale_y_log10(breaks = scales::trans_breaks("log10", function(x) 10^x), labels = scales::trans_format("log10", scales::math_format(10^.x)))+
    facet_grid(.~Species)+
    labs(fill = "Condition",y = "% biomass contribution per bin",x = bquote(paste("Aggregate Volume (", mu*"m"^3*")")))+
    guides(color = FALSE)+
    scale_fill_grey()+
    theme_cowplot(12)+
    theme(plot.title = element_text(hjust = 0.5),strip.text = element_text(face = "italic"))
}
PlotDensityLogBin("PA14wt", "WT")
PlotDensityLogBin("PA14mut", "pqsL")
```


```{r extra stuff}
plotHist3DBiomassCountsLog<-function(df1, title){
  ggplot()+
    geom_point(data=df1,aes(y=max, x=frequency, color = ConditionNew, shape = Strain))+
    scale_y_log10(breaks = scales::trans_breaks("log10", function(x) 10^x), labels = scales::trans_format("log10", scales::math_format(10^.x)))+
    scale_x_log10(breaks = scales::trans_breaks("log10", function(x) 10^x), labels = scales::trans_format("log10", scales::math_format(10^.x)))+
    ylab('Biomass (um^3)')+
    xlab('Frequency')+
    #facet_wrap(~Sample, ncol=3)+
    ggtitle(paste0(title," Raw biomass Distribution (bin size = 100 um)"))+
    theme_cowplot()+
    theme(plot.title = element_text(hjust = 0.5))
}


#This shows that the Sa biomass that gets eaten by Staph is from the largest aggregates, not from the small ones
plotHist3DBiomassCountsLog(hist.100 %>% filter(Species == "Sa"), "Sa co-culture vs mono")
plotHist3DBiomassCountsLog(hist.100 %>% filter(Species == "Pa"), "Pa co-culture vs mono")
plotHist3DBiomassCountsLog(hist.5 %>% filter(Species == "Sa"), "Sa co-culture vs mono")

plotHist3DBiomassCounts<-function(df1, title){
  ggplot()+
    geom_point(data=df1,aes(x=max, y=frequency, color = Strain, shape = Sample))+
    scale_y_log10(breaks = scales::trans_breaks("log10", function(x) 10^x), labels = scales::trans_format("log10", scales::math_format(10^.x)))+
    xlab('Biomass (um^3)')+
    ylab('Frequency')+
    ggtitle(paste0(title," Raw biomass Distribution (bin size = 5 um)"))+
    facet_wrap(~TimePoint, nrow=4)
}
#this shows how different ratios work to delay the dissapearance of large aggregates of staph in the samples
plotHist3DBiomassCounts(allDataHistograms.5df%>%filter(Species=="Sa") %>% filter(Condition == "Pa:Sa 1:100")%>% filter(max<101),"Sa in Pa:Sa 1:100 only")
plotHist3DBiomassCounts(allDataHistograms.5df%>%filter(Species =="Sa") %>% filter(Condition=="Pa:Sa 1:10")%>% filter(max<101),"Sa in Pa:Sa 1:10 only")
plotHist3DBiomassCounts(allDataHistograms.5df%>%filter(Species == "Sa") %>%filter(Condition=="Pa:Sa 10:1")%>% filter(max<101),"Sa in Pa:Sa 10:1 only")
#this shows how early or late large aggregates of pseudomonas appear according to the ratio
plotHist3DBiomassCounts(allDataHistograms.5df%>%filter(Species=="Pa") %>% filter(Condition == "Pa:Sa 1:100")%>% filter(max<101),"Pa in Pa:Sa 1:100 only")
plotHist3DBiomassCounts(allDataHistograms.5df%>%filter(Species =="Pa") %>% filter(Condition=="Pa:Sa 1:10")%>% filter(max<101),"Pa in Pa:Sa 1:10 only")
plotHist3DBiomassCounts(allDataHistograms.5df%>%filter(Species == "Pa") %>%filter(Condition=="Pa:Sa 10:1")%>% filter(max<101),"Pa in Pa:Sa 10:1 only")

#This plots how much biomass is on each bin, it should be exponential in y-axis, but I don't think it is super useful
plotHist3DBiomassBinBiomass<-function(df1, title, binSize){
  ggplot()+
    geom_point(data=df1,aes(x=max, y=suma, color = Strain, shape = Condition))+
    scale_y_log10(breaks = scales::trans_breaks("log10", function(x) 10^x), labels = scales::trans_format("log10", scales::math_format(10^.x)))+
    scale_x_log10(breaks = scales::trans_breaks("log10", function(x) 10^x), labels = scales::trans_format("log10", scales::math_format(10^.x)))+
    xlab('Bin size')+
    ylab('Biomass (um^3)')+
    ggtitle(paste0("Total Biomass per bin (bin size = ",binSize," um) ",title))+
    facet_wrap(~TimePoint, nrow=4)
}
plotHist3DBiomassBinBiomass(allDataHistograms.100df %>% filter(Species == "Sa") %>% filter (Coculture=="No"), "Sa co-culture vs mono", "100")

#This shows how much of the total biomass is on each bin. it should just go from 0 to one, so not a great idea to make it exponential.
plotHist3DBiomassNormBinBiomass<-function(df1, title, binSize){
  ggplot()+
    geom_point(data=df1,aes(x=max, y=BiomassBin, color = Strain, shape = Sample))+
    scale_y_log10(breaks = scales::trans_breaks("log10", function(x) 10^x), labels = scales::trans_format("log10", scales::math_format(10^.x)))+
    scale_x_log10(breaks = scales::trans_breaks("log10", function(x) 10^x), labels = scales::trans_format("log10", scales::math_format(10^.x)))+
    xlab('Bin size')+
    ylab('Contribution to total biomass')+
    ggtitle(paste0("Biomass contribution per bin (bin size = ",binSize," um) ",title))+
    facet_wrap(~TimePoint, nrow=4)
}
#binsize of 100
plotHist3DBiomassNormBinBiomass(allDataHistograms.100df %>% filter(Species == "Sa") %>% filter (Coculture=="No"), "Sa mono culture", "100")
plotHist3DBiomassNormBinBiomass(allDataHistograms.100df %>% filter(Species == "Pa") %>% filter (Coculture=="No"), "Pa mono culture", "100")

plotHist3DBiomassNormBinBiomass<-function(df1, title, binSize){
  ggplot()+
    geom_point(data=df1,aes(x=max, y=BiomassBin, color = Strain, shape = Condition))+
    scale_y_log10(breaks = scales::trans_breaks("log10", function(x) 10^x), labels = scales::trans_format("log10", scales::math_format(10^.x)))+
    scale_x_log10(breaks = scales::trans_breaks("log10", function(x) 10^x), labels = scales::trans_format("log10", scales::math_format(10^.x)))+
    xlab('Bin size')+
    ylab('Contribution to total biomass')+
    ggtitle(paste0("Biomass contribution per bin (bin size = ",binSize," um) ",title))+
    facet_wrap(~TimePoint, nrow=4)
}
plotHist3DBiomassNormBinBiomass(allDataHistograms.100df %>% filter(Species == "Sa") %>% filter (Coculture=="Yes"), "Sa co-cultures", "100")
plotHist3DBiomassNormBinBiomass(allDataHistograms.100df %>% filter(Species == "Pa") %>% filter (Coculture=="Yes"), "Pa co-cultures", "100")

#binsize of 5
plotHist3DBiomassNormBinBiomass(allDataHistograms.5df%>% filter(Species == "Sa") %>% filter (Coculture=="No")%>% filter(max<101), "Sa mono culture", "5")
plotHist3DBiomassNormBinBiomass(allDataHistograms.5df%>% filter(Species == "Pa") %>% filter (Coculture=="No")%>% filter(max<101), "Pa mono culture", "5")

```
#Mixed Aggregates Analysis
```{r mixed aggregates import data} 
ReadMixedAggregateFile<-function(sample, imageSource){#This function outputs total number of pixels in the csv file from matlab
  file<- paste0('/Users/jupabago/Documents/Whiteley/PROJECTS/PaSaProject/Spatial paper Data/Microscopy Data/MixedAggregates/', sample,imageSource, '.csv')
  datos <-read.csv(file, header = TRUE)
  colnames(datos)<-c('Size', 'Sa', 'Pa', 'Overlap', 'Slice')
  datos<-datos %>% mutate(Sample = sample)
  return(datos)
}
PA14wt<- c('3-13-19', '3-19-19', '4-17-19')
PA14mut<- c('4-24-19', '4-25-19', '5-8-19')
#wt data retrieval
mixedAggDataWtList<-map2(PA14wt,'RedSubtract', ReadMixedAggregateFile) 
mixedAggDataWt<-bind_rows(mixedAggDataWtList)
mixedAggDataWt<-mixedAggDataWt %>% mutate(Strain = "PA14wt")
#mut data retrieval
mixedAggDataMutList<-map2(PA14mut,'RedSubtract',ReadMixedAggregateFile) 
mixedAggDataMut<-bind_rows(mixedAggDataMutList)
mixedAggDataMut<-mixedAggDataMut %>% mutate(Strain = "PA14mut")

#This is the data for all objects
mixedAggDataAll<-bind_rows(mixedAggDataWt,mixedAggDataMut)

#this is only the biomass, which is the only thing I can actually compare since this is 2D
mixedAggDataAllSlim<-mixedAggDataAll%>% group_by(Sample, Strain) %>%
  summarise (Aggregates = n(), PaBiomass = sum(Pa), SaBiomass = sum(Sa), TotalBiomass = sum(Size)) 

#this includes all the other maybe relevant data
mixedAggDataAllStats<-mixedAggDataAll%>% group_by(Sample, Strain) %>%
  summarise (Aggregates = n(), PaBiomass = sum(Pa), SaBiomass = sum(Sa), TotalBiomass = sum(Size)) %>% mutate(MeanSizeSample =Aggregates/TotalBiomass) %>%
  ungroup() %>% group_by(Strain) %>% 
  mutate(PaBiomassStrain = sum(PaBiomass), SaBiomassStrain = sum(SaBiomass), TotalBiomassStrain = sum(TotalBiomass), AggregatesStrain = sum(Aggregates)) %>% mutate(MeanSizeStrain = AggregatesStrain/TotalBiomassStrain, Source = "All")

#This is the data for mixed-species aggregates only
mixedAggDataDual<-mixedAggDataAll %>% filter(Sa > 0 & Pa >0) 

#only biomass
mixedAggDataDualSlim<-mixedAggDataDual %>% group_by(Sample, Strain) %>% 
  summarise (AggregatesMixed = n(), PaBiomassMixed = sum(Pa), SaBiomassMixed = sum(Sa), TotalBiomassMixed = sum(Size))

#Compare all objects to dual-species objects
combinedMixedAggData<- merge(mixedAggDataAllSlim, mixedAggDataDualSlim, by = "Sample")

combinedMixedAggData<-combinedMixedAggData %>% 
  mutate(PercentAggs = AggregatesMixed/Aggregates*100, PercentPaBiomass =  PaBiomassMixed/PaBiomass*100, 
         PercentSaBiomass =  SaBiomassMixed/SaBiomass*100, PercentTotalBiomass = TotalBiomassMixed/TotalBiomass*100) %>% group_by(Strain.x) %>% 
  mutate(MeanAggs = mean (PercentAggs), SEAggs = std.error (PercentAggs), 
         MeanPaBiomass = mean(PercentPaBiomass),SEPaBiomass = std.error(PercentPaBiomass),
         MeanSaBiomass = mean(PercentSaBiomass),SESaBiomass = std.error(PercentSaBiomass), 
         MeanTotalBiomass = mean(PercentTotalBiomass), SETotalBiomass = std.error(PercentTotalBiomass))

combinedMixedAggData$Strain.x <- factor(combinedMixedAggData$Strain.x, levels = c("PA14wt", "PA14mut"))
### I think this is the final figure
MixedAggregateBiomassPlot<-ggplot()+
  geom_point(data = combinedMixedAggData,aes(x=Strain,y=PercentTotalBiomass ),size=1)+
  geom_point(data = combinedMixedAggData,aes(x=Strain,y=MeanTotalBiomass, shape = Strain),size=3)+
  geom_errorbar(data = combinedMixedAggData,aes(x=Strain,ymin=MeanTotalBiomass-SETotalBiomass, ymax =MeanTotalBiomass+SETotalBiomass),size=.2, width = .2)+
  #labs(title ="Proportion of mixed species biomass")+
  #scale_y_log10(breaks = scales::trans_breaks("log10", function(x) 10^x), labels = scales::trans_format("log10", scales::math_format(10^.x)))+
  scale_shape_manual(values = c(1,2),name = "", limits=c("PA14wt","PA14mut"))+
  scale_x_discrete(breaks=c("PA14wt","PA14mut"), 
                     labels = c(bquote(paste(" wild-type")),
                                bquote(paste(italic(Delta*"pqsL")))))+
  labs(y = "Percent mixed aggregates biomass", x = "")+
  theme_cowplot()+
  theme(plot.title = element_text(hjust = 0.5),legend.position="none")

#MixedAggregateFrequencyPlot<-
  ggplot()+
  geom_point(data = combinedMixedAggData,aes(x=Strain.x,y=PercentAggs ),size=1)+
  geom_point(data = combinedMixedAggData,aes(x=Strain.x,y=MeanAggs, shape = Strain.x),size=3)+
  geom_errorbar(data = combinedMixedAggData,aes(x=Strain.x,ymin=MeanAggs-SEAggs, ymax =MeanAggs+SEAggs),size=.2, width = .2)+
  #labs(title ="Proportion of mixed species biomass")+
  #scale_y_log10(breaks = scales::trans_breaks("log10", function(x) 10^x), labels = scales::trans_format("log10", scales::math_format(10^.x)))+
  scale_shape_manual(values = c(1,2),name = "", limits=c("PA14wt","PA14mut"))+
  scale_x_discrete(breaks=c("PA14wt","PA14mut"), 
                     labels = c(bquote(paste(" wild-type")),
                                bquote(paste(italic(Delta*"pqsL")))))+
  labs(y = "% mixed aggregates", x = "")+
  ylim(0,10)+
  theme_cowplot()+
  theme(plot.title = element_text(hjust = 0.5),legend.position="none")


#this includes all the other maybe relevant data but for dual-species aggregates only
mixedAggDataDualStats<-mixedAggDataDual %>% group_by(Sample, Strain) %>%
  summarise (Aggregates = n(), PaBiomass = sum(Pa), SaBiomass = sum(Sa), TotalBiomass = sum(Size)) %>% mutate(MeanSizeSample =Aggregates/TotalBiomass) %>%
  ungroup() %>% group_by(Strain) %>% 
  mutate(PaBiomassStrain = sum(PaBiomass), SaBiomassStrain = sum(SaBiomass), TotalBiomassStrain = sum(TotalBiomass), AggregatesStrain = sum(Aggregates)) %>% mutate(MeanSizeStrain = AggregatesStrain/TotalBiomassStrain, Source = "Mixed")

#T-tests

tTestMixBiomassWt<-combinedMixedAggData %>% filter(Strain.x == "PA14wt") %>% pull(PercentTotalBiomass)
tTestMixBiomassMut<-combinedMixedAggData %>% filter(Strain.x == "PA14mut") %>% pull(PercentTotalBiomass)
tTestMixBiomass<-t.test(x = tTestMixBiomassWt, y = tTestMixBiomassMut, paired = F)

tTestMixAggsWt<-combinedMixedAggData %>% filter(Strain.x == "PA14wt") %>% pull(PercentAggs)
tTestMixAggsMut<-combinedMixedAggData %>% filter(Strain.x == "PA14mut") %>% pull(PercentAggs)
tTestMixAggs<-t.test(x = tTestMixAggsWt, y = tTestMixAggsMut, paired = F)

```
# Combining all Spatial Data

```{r final figure}
#So, I need the mean aggregate size figure first
MeanAggSizeWtPlot
MeanAggSizeMutPlot

plotNonButterfly("Sa", "PA14wt")
plotNonButterfly("Sa", "PA14mut")
plotNonButterfly("Pa", "PA14wt")
plotNonButterfly("Pa", "PA14mut")



#Enrichment plot
sa.paPlot<-ggplot()+
  geom_point(data = enrichmentDataFinal %>% filter(Relation == "Sa->Pa"),aes(y=meanEnrichment, x = Strain, shape = Strain),size=4)+
  geom_errorbar(data = enrichmentDataFinal %>% filter(Relation == "Sa->Pa"),
                aes(ymin = meanEnrichment-sdEnrichment,ymax = meanEnrichment+sdEnrichment, x = Strain),size=.2, width = .1)+
  labs( y = bquote(paste("Distance ("*mu*"m)")), x = "" ) +
  scale_shape_manual(values = c(1,2),name = "", limits=c("wt","mut"),labels = c(bquote(paste(italic('P. aeruginosa'), " wild-type")),
                                bquote(paste(italic('P. aeruginosa '), Delta*"pqsL"))))+
  scale_x_discrete(name ="", breaks = c("wt","mut"), labels =c("wild-type",expression(""*Delta*"pqsL")))+
  ylim(1, 9)+
  theme_cowplot()

sa.saPlot<-ggplot()+
  geom_point(data = enrichmentDataFinal %>% filter(Relation == "Sa->Sa"),aes(y=meanEnrichment, x = Strain, shape = Strain),size=4)+
  geom_errorbar(data = enrichmentDataFinal %>% filter(Relation == "Sa->Sa"),
                aes(ymin = meanEnrichment-sdEnrichment,ymax = meanEnrichment+sdEnrichment, x = Strain),size=.2, width = .1)+
  labs( y = bquote(paste("Distance ("*mu*"m)")), x = "" ) +
  scale_shape_manual(values = c(1,2),name = "", limits=c("wt","mut"),labels = c(bquote(paste(italic('P. aeruginosa'), " wild-type")),
                                bquote(paste(italic('P. aeruginosa '), Delta*"pqsL"))))+
  scale_x_discrete(name ="", breaks = c("wt","mut"), labels =c("wild-type",expression(""*Delta*"pqsL")))+
  ylim(1, 9)+
  theme_cowplot()

legendFigure7 <- get_legend(sa.saPlot + theme(legend.box.margin = margin(0, 0, 0, -10)))
figure7 <- plot_grid(sa.saPlot+theme(legend.position="none"),sa.paPlot+theme(legend.position="none"),
                      align='vh',labels = c("B", "C"),hjust = -1,nrow = 1)
plot_grid(figure7,legendFigure7,rel_widths = c(4, 1.7))
#plot_grid(sa.saPlot,sa.paPlot,align='vh',labels = c("A", "B"),hjust = -1,nrow = 1)

```
