---
title: "Microscopy Data"
author: "Juan P Barraza"
date: "6/19/2019"
output: html_document
---

```{r setup, include=FALSE}
library(pixmap)
library(rtiff)
library(reshape2)
library(gplots)
library(dplyr)
library(gdata)
library(ggplot2)
library(cowplot)
library(magrittr)
library(tidyr)
library(purrr)


PA14wt<- c('3-13-19', '3-19-19', '4-17-19')
PA14mut<- c('4-24-19', '4-25-19', '5-8-19')
PA01wt<- c('3-26-19','4-18-19')
PA01mut<- c('4-23-19')
names3<-c('rep1','rep2','rep3')
names2<-c('rep1','rep2')

```


```{r thresholds}

testThresholdFile<-"/Users/jupabago/Documents/Whiteley/PROJECTS/Spatial paper Data/Microscopy Data/Other Data/3-13-19/threshold/threshold_p_0.csv"

wtThresholds<-MapThreshold(PA14wt, names3)
mutThresholds<-MapThreshold(PA14mut, names3)
Pa01Thresholds<-MapThreshold(PA01wt, names2)
Pa01mutThresholds<-MapThreshold(PA01mut, 'rep1')

MapThreshold<- function(listSamples, reps){
  mappedData<-map2(listSamples, reps, GetThresholds)
  boundData<-bind_rows(mappedData)
  return(boundData)
  }

GetThresholds<-function(sample, samplename){
  folder<- paste0('/Users/jupabago/Documents/Whiteley/PROJECTS/Spatial paper Data/Microscopy Data/Other Data/',sample,'/threshold')
  fileList<-list.files(path = folder, full.names = TRUE)
  growthDf<-data.frame()
  for (position in 0:5){
    currentPosition<-fileList[grep(paste0("p_",position,"."),fileList)]
    growthDf<-rbind(growthDf,ReadThresholdFile(currentPosition, position))}
  growthDf<-growthDf %>% mutate(Sample = samplename)
return(growthDf)
}

ReadThresholdFile<-function(file, position ){#This function outputs total number of pixels in the csv file from matlab
  datos <-read.csv(file, header = FALSE)
  colnames(datos)<-c('Red', 'Green')
  datos<-datos %>% mutate(Position = position)
  datos<-datos %>% mutate(TimePoint = row_number()-1)
  return(datos)
}

```

```{r biomass}

wtResults<-MapResults(PA14wt, names3)
mutResults<-MapResults(PA14mut, names3)
Pa01Results<-MapResults(PA01wt, names2)
Pa01mutResults<-MapResults(PA01mut, 'rep1')

MapResults<- function(listSamples, reps){
  blah <-deparse(substitute(listSamples))
  mappedData<-map2(listSamples, reps, GetResults)
  boundData<-bind_rows(mappedData)
  boundData<-boundData %>% mutate(Strain = blah)
  return(boundData)
  }

GetResults<-function(sample, samplename){
  folder<- paste0('/Users/jupabago/Documents/Whiteley/PROJECTS/Spatial paper Data/Microscopy Data/Other Data/',sample,'/results')
  fileList<-list.files(path = folder, full.names = TRUE)
  growthDf<-data.frame()
  for (position in 0:5){
    currentPosition<-fileList[grep(paste0("p",position,"."),fileList)]
    for (timepoint in 0:17){
      currentTimePoint<-currentPosition[grep(paste0("t",GetNumber(timepoint),"_"),currentPosition)]
      growthDf<-rbind(growthDf,ReadResultsFile(currentTimePoint, position, timepoint))}}
  growthDf<-growthDf %>% mutate(Sample = samplename)
return(growthDf)
}

ReadResultsFile<-function(file, position, timepoint){
  datos <-read.csv(file, header = FALSE)
  colnames(datos)<-c('Red', 'Green', 'Slice')
  datos<-datos %>% mutate(Position = position)
  datos<-datos %>% mutate(TimePoint = timepoint)
  return(datos)
}


```

## Including Plots
```{r aggregates}

wtAggregates<-MapAggregates(PA14wt, names3)
mutAggregates<-MapAggregates(PA14mut, names3)
Pa01Results<-MapAggregates(PA01wt, names2)
Pa01mutResults<-MapAggregates(PA01mut, 'rep1')

MapAggregates<- function(listSamples, reps){
  mappedData<-map2(listSamples, reps, GetAggregates)
  boundData<-bind_rows(mappedData)
  blah <-deparse(substitute(listSamples))
  boundData<-boundData %>% mutate(Strain = blah)#needs to be two lines, it doesnt work if you do it directly
  return(boundData)
  }

GetAggregates<-function(sample, samplename){
  folder<- paste0('/Users/jupabago/Documents/Whiteley/PROJECTS/Spatial paper Data/Microscopy Data/Other Data/',sample,'/aggregateSizes')
  fileList<-list.files(path = folder, full.names = TRUE)
  growthDf<-data.frame()
  for (position in 0:5){
    currentPosition<-fileList[grep(paste0("p_",position,"."),fileList)]
    for (timepoint in 0:17){
      currentTimePoint<-currentPosition[grep(paste0("t_",GetNumber(timepoint),"p_"),currentPosition)]
      growthDf<-rbind(growthDf,ReadAggregateFile(currentTimePoint, position, timepoint))
      }
  }
  growthDf<-growthDf %>% mutate(Sample = samplename)
return(growthDf)
}

ReadAggregateFile<-function(file, position, timepoint){#This function outputs total number of pixels in the csv file from matlab
  datos <-read.csv(file, header = TRUE)
  colnames(datos)<-c('Size', 'Species')
  datos<-datos %>% mutate(Position = position)
  datos<-datos %>% mutate(TimePoint = timepoint)
  return(datos)
}


```
You can also embed plots, for example:

```{r support functions, echo=FALSE}

GetNumber<-function(idx){
  if (idx<10){
    idx = paste0(0,idx)
  }
  return (idx)
}
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
