---
title: "Sa TOB Report"
author: "Juan P Barraza"
date: "2/14/2020"
output: html_document
editor_options: 
  chunk_output_type: console
---
```{r setup, include=FALSE}
library(rdist)
library(pixmap)
library(rtiff)
library(reshape2)
library(gplots)
library(dplyr)
library(gdata)
library(ggplot2)
library(cowplot)
library(magrittr)
library(scales)
library(purrr)
library(plotrix)#for std.error
library(ggpubr)#for p-values
```
# Good data
Shown below is the data using the new SCFM2 with extra lipids

```{r reading data functions , echo=FALSE, warning=FALSE,fig.width=9, fig.height=7}
#these are the list with the spreadsheets of experiments under different conditions
GetTobReplicate<- function (sample){
  bugCounts<-read.csv(paste0("/Users/jupabago/Documents/Whiteley/PROJECTS/PaSaProject/Spatial paper Data/TOB/", sample, ".csv"),header = TRUE)
  bugCounts<- na.omit(bugCounts)
  bugCounts<-bugCounts %>% mutate(logTranformed = log10(CFU))
  bugCounts$sample<-sample
  return(bugCounts)
}
GetTOBcondition<-function(datalist, conditionName){
  mappedData<-map(datalist, GetTobReplicate)#this line reads all the files on the list
  boundData<-bind_rows(mappedData)
  boundData$condition<-conditionName
  return(boundData)
}
mutLib128 = c('2-21-19','2-19-19','2-14-19')
cleanDelScfm128 = c('5-10-19','5-11-19')
cleanDelScfm64 = c('5-15-19','5-16-19')
cleanDelEndpoint<-c("1-25-20A","1-25-20B","1-28-20","1-29-20")
```

```{r reading data, echo=FALSE, warning=FALSE,fig.width=9, fig.height=7}
mutLib128Data<-GetTOBcondition(mutLib128, "mutLib128")
cleanDelScfm64Data<-GetTOBcondition(cleanDelScfm64, "cleanDelScfm64")
cleanDelScfm128Data<-GetTOBcondition(cleanDelScfm128, "cleanDelScfm128")
cleanDelEndpointData<-GetTOBcondition(cleanDelEndpoint,"cleanDelEndpoint")

newSCFMData<-rbind(mutLib128Data,cleanDelScfm128Data,cleanDelScfm64Data,cleanDelEndpointData)#combine all conditions
newSCFMData<-newSCFMData %>% mutate(strain = ifelse(condition == "mutLib128", "Tn", "Clean"))

#I have to remove one replicate from 5-16-19 TOB 3 HRS because I lost the mono data :(
removable <- newSCFMData %>% filter(antibiotic == "TOB" & bug == "Sa" & sample == "5-16-19" & timePoint == 3 )
newSCFMDataComparison <- anti_join(newSCFMData, removable)

newSCFMDataSaComparison<-newSCFMDataComparison%>%filter(bug == "Sa") %>%  group_by(antibiotic, bug, timePoint, sample, condition) %>% mutate(ratioCFU = CFU / CFU[culture =="mono"])%>% mutate(ratiolog = logTranformed / logTranformed[culture =="mono"])%>%  ungroup()

#this is to average the two technical replicates
techReps<-newSCFMDataSaComparison %>% filter(sample %in% c("1-25-20A", "1-25-20B")) %>% group_by(culture,bug,timePoint, antibiotic, condition, strain) %>% summarise(CFU = mean(CFU)) %>% mutate(sample = "1-25-20")
```

```{r calculating mean and ratios}
cleanDelEndpointData <-cleanDelEndpointData %>% group_by(timePoint,antibiotic,sample) %>% mutate(ratioMono = CFU/CFU[culture=="mono"],ratioMonoLog = logTranformed/logTranformed[culture=="mono"]) %>% ungroup()

cleanDelEndpointData <-cleanDelEndpointData %>%  group_by(timePoint,antibiotic,culture) %>% mutate( meanLog = mean(logTranformed),SDLog = sd(logTranformed), meanCFU = mean(CFU), SDCFU = sd(CFU), meanRatioLog = mean(ratioMonoLog), sdRatioMonoLog = sd(ratioMonoLog),meanRatio = mean(ratioMono), sdRatioMono = sd(ratioMono))%>% ungroup()
```

```{r graph end point numbers}
#This shows growth curves of all replicates
ggplot()+
  geom_jitter(data=cleanDelEndpointData , aes(x=timePoint, y=CFU, color = culture), height = 0, width = .2, size=4)+
  scale_y_log10(name=expression(paste('CFUs per mL' )), breaks = scales::trans_breaks("log10", function(x) 10^x), labels = scales::trans_format("log10", scales::math_format(10^.x)))+
  #geom_vline(xintercept=3, linetype = "dashed")+
  #annotate("text", x = 3, y = 10e6, label = "TOB added")+
  labs(title =expression(paste(italic("S. aureus"), " growth in mono or coculture in SCFM2 with 256 ug/mL TOB")), x = "Time (hours)",shape = "Culture condition", color = "Antiobiotic/Control") +
  facet_grid(sample~antibiotic)+
  theme_cowplot()+
  panel_border()+
  background_grid()

#CFU numbers with means
ggplot()+
  geom_jitter(data=cleanDelEndpointData , aes(x=timePoint, y=CFU, shape = culture, color = antibiotic), height = 0, width = .2, size=2)+
  geom_point(data=cleanDelEndpointData , aes(x=timePoint, y=meanCFU, shape = culture, color = antibiotic), size=4)+
  scale_y_log10(name=expression(paste('CFUs per mL' )), breaks = scales::trans_breaks("log10", function(x) 10^x), labels = scales::trans_format("log10", scales::math_format(10^.x)))+
  #geom_vline(xintercept=3, linetype = "dashed")+
  #annotate("text", x = 3, y = 10e6, label = "TOB added")+
  labs(title =expression(paste(italic("S. aureus"), " growth in mono or coculture in SCFM2 with 256 ug/mL TOB")), x = "Time (hours)",shape = "Culture condition", color = "Antiobiotic/Control") +
  theme_cowplot()+
  panel_border()+
  background_grid()

#Log numbers with log means
ggplot()+
  geom_jitter(data=cleanDelEndpointData , aes(x=timePoint, y=logTranformed, shape = culture, color = antibiotic), height = 0, width = .2, size=2)+
  geom_point(data=cleanDelEndpointData , aes(x=timePoint, y=meanLog, shape = culture, color = antibiotic), size=4)+
  #scale_y_log10(name=expression(paste('CFUs per mL' )), breaks = scales::trans_breaks("log10", function(x) 10^x), labels = scales::trans_format("log10", scales::math_format(10^.x)))+
  #geom_vline(xintercept=3, linetype = "dashed")+
  #annotate("text", x = 3, y = 10e6, label = "TOB added")+
  labs(title =expression(paste(italic("S. aureus"), " growth in mono or coculture in SCFM2 with 256 ug/mL TOB")), x = "Time (hours)",shape = "Culture condition", color = "Antiobiotic/Control") +
  theme_cowplot()+
  panel_border()+
  background_grid()

#ONLY ENDPOINTS CFU
ggplot()+
  geom_jitter(data=cleanDelEndpointData %>% filter(timePoint==5) , aes(x=culture, y=CFU,  color = antibiotic), height = 0, width = .2, size=2)+
  geom_errorbar(data=cleanDelEndpointData %>% filter(timePoint==5) , aes(x=culture, ymin=meanCFU-SDCFU,ymax = meanCFU+SDCFU,  color = antibiotic), height = 0, width = .2, size=2)+
  geom_point(data=cleanDelEndpointData %>% filter(timePoint==5), aes(x=culture, y=meanCFU, color = antibiotic), height = 0, width = .2, size=4)+
  scale_y_log10(name=expression(paste('CFUs per mL' )), breaks = scales::trans_breaks("log10", function(x) 10^x), labels = scales::trans_format("log10", scales::math_format(10^.x)))+
  #geom_vline(xintercept=3, linetype = "dashed")+
  #annotate("text", x = 3, y = 10e6, label = "TOB added")+
  labs(title =expression(paste(italic("S. aureus"), " growth in mono or coculture in SCFM2 with 256 ug/mL TOB")), x = "Time (hours)",shape = "Culture condition", color = "Antiobiotic/Control") +
  theme_cowplot()+
  panel_border()+
  background_grid()
#ONLY ENDPOINTS log
ggplot()+
  geom_jitter(data=cleanDelEndpointData %>% filter(timePoint==5) , aes(x=culture, y=logTranformed,  color = antibiotic), height = 0, width = .2, size=2)+
  geom_errorbar(data=cleanDelEndpointData %>% filter(timePoint==5) , aes(x=culture, ymin=meanLog-SDLog,ymax = meanLog+SDLog,  color = antibiotic), height = 0, width = .2, size=2)+
  geom_point(data=cleanDelEndpointData %>% filter(timePoint==5), aes(x=culture, y=meanLog, color = antibiotic),  size=4)+
  #scale_y_log10(name=expression(paste('CFUs per mL' )), breaks = scales::trans_breaks("log10", function(x) 10^x), labels = scales::trans_format("log10", scales::math_format(10^.x)))+
  #geom_vline(xintercept=3, linetype = "dashed")+
  #annotate("text", x = 3, y = 10e6, label = "TOB added")+
  labs(title =expression(paste(italic("S. aureus"), " growth in mono or coculture in SCFM2 with 256 ug/mL TOB")), x = "Time (hours)",shape = "Culture condition", color = "Antiobiotic/Control") +
  theme_cowplot()+
  panel_border()+
  background_grid()
#only endpoints ratio log
ggplot()+
  geom_jitter(data=cleanDelEndpointData %>% filter(timePoint==5) , aes(x=culture, y=ratioMonoLog,  color = antibiotic), height = 0, width = .2, size=2)+
  geom_errorbar(data=cleanDelEndpointData %>% filter(timePoint==5) , aes(x=culture, ymin=meanRatioLog-sdRatioMonoLog,ymax = meanRatioLog+sdRatioMonoLog,  color = antibiotic), height = 0, width = .2, size=2)+
  geom_point(data=cleanDelEndpointData %>% filter(timePoint==5), aes(x=culture, y=meanRatioLog, color = antibiotic), size=4)+
  #scale_y_log10(name=expression(paste('CFUs per mL' )), breaks = scales::trans_breaks("log10", function(x) 10^x), labels = scales::trans_format("log10", scales::math_format(10^.x)))+
  #geom_vline(xintercept=3, linetype = "dashed")+
  #annotate("text", x = 3, y = 10e6, label = "TOB added")+
  labs(title =expression(paste(italic("S. aureus"), " growth in mono or coculture in SCFM2 with 256 ug/mL TOB")), x = "Time (hours)",shape = "Culture condition", color = "Antiobiotic/Control") +
  theme_cowplot()+
  panel_border()+
  background_grid()
```


```{r graph end point ratios}
#ratio facets
ggplot()+
  geom_jitter(data=cleanDelEndpointData , aes(x=timePoint, y=ratioMono, color = culture), height = 0, width = .2, size=4)+
  scale_y_log10(name=expression(paste('CFUs per mL' )), breaks = scales::trans_breaks("log10", function(x) 10^x), labels = scales::trans_format("log10", scales::math_format(10^.x)))+
  #geom_vline(xintercept=3, linetype = "dashed")+
  #annotate("text", x = 3, y = 10e6, label = "TOB added")+
  labs(title =expression(paste(italic("S. aureus"), " growth ratio compared to Mono culture")), x = "Time (hours)",shape = "Culture condition", color = "Antiobiotic/Control") +
  facet_grid(sample~antibiotic)+
  theme_cowplot()+
  panel_border()+
  background_grid()

#ratio mono by shapes
ggplot()+
  geom_jitter(data=cleanDelEndpointData , aes(x=timePoint, y=ratioMono, shape = culture, color = antibiotic), height = 0, width = .2, size=4)+
  #geom_point(data=cleanDelEndpoint , aes(x=timePoint, y=meanLog, shape = culture, color = antibiotic), height = 0, width = .2, size=4)+
  scale_y_log10(name=expression(paste('CFUs per mL' )), breaks = scales::trans_breaks("log10", function(x) 10^x), labels = scales::trans_format("log10", scales::math_format(10^.x)))+
  #geom_vline(xintercept=3, linetype = "dashed")+
  #annotate("text", x = 3, y = 10e6, label = "TOB added")+
  labs(title =expression(paste(italic("S. aureus"), " growth in mono or coculture in SCFM2 with 256 ug/mL TOB")), x = "Time (hours)",shape = "Culture condition", color = "Antiobiotic/Control") +
  theme_cowplot()+
  panel_border()+
  background_grid()
#ratio mono log by shapes
ggplot()+
  geom_jitter(data=cleanDelEndpointData , aes(x=timePoint, y=ratioMonoLog, shape = culture, color = antibiotic), height = 0, width = .2, size=4)+
  #geom_point(data=cleanDelEndpoint , aes(x=timePoint, y=meanLog, shape = culture, color = antibiotic), height = 0, width = .2, size=4)+
  #scale_y_log10(name=expression(paste('CFUs per mL' )), breaks = scales::trans_breaks("log10", function(x) 10^x), labels = scales::trans_format("log10", scales::math_format(10^.x)))+
  #geom_vline(xintercept=3, linetype = "dashed")+
  #annotate("text", x = 3, y = 10e6, label = "TOB added")+
  labs(title =expression(paste(italic("S. aureus"), " growth in mono or coculture in SCFM2 with 256 ug/mL TOB")), x = "Time (hours)",shape = "Culture condition", color = "Antiobiotic/Control") +
  theme_cowplot()+
  panel_border()+
  background_grid()

#only endpoints ratio log
ggplot()+
  geom_jitter(data=cleanDelEndpointData %>% filter(timePoint==5) , aes(x=culture, y=ratioMono,  color = antibiotic), height = 0, width = .2, size=2)+
  geom_errorbar(data=cleanDelEndpointData %>% filter(timePoint==5) , aes(x=culture, ymin=meanRatio-sdRatioMono,ymax = meanRatio+sdRatioMono,  color = antibiotic), height = 0, width = .2, size=2)+
  geom_point(data=cleanDelEndpointData %>% filter(timePoint==5), aes(x=culture, y=meanRatio, color = antibiotic), height = 0, width = .2, size=4)+
  scale_y_log10(name=expression(paste('CFUs per mL' )), breaks = scales::trans_breaks("log10", function(x) 10^x), labels = scales::trans_format("log10", scales::math_format(10^.x)))+
  #geom_vline(xintercept=3, linetype = "dashed")+
  #annotate("text", x = 3, y = 10e6, label = "TOB added")+
  labs(title =expression(paste(italic("S. aureus"), " growth in mono or coculture in SCFM2 with 256 ug/mL TOB")), x = "Time (hours)",shape = "Culture condition", color = "Antiobiotic/Control") +
  theme_cowplot()+
  panel_border()+
  background_grid()
```

#now I think it would be better to pool all the data and see how it looks like:

```{r pooling data from january 2020 and feb 2019}
#Make both data sets have all the same columns an rows:
newSCFMDataEndpointOnly<-newSCFMData %>% select(CFU, culture, bug, timePoint, antibiotic, sample, condition, strain) %>% filter(timePoint %in% c(0,5))

cleanDelEndpointDataEndpointOnly<-newSCFMDataEndpointOnly %>% select(CFU,culture, bug, timePoint, antibiotic, sample, condition, strain)%>% filter(!sample %in% c("1-25-20A", "1-25-20B")) %>% bind_rows(techReps)

#here I will calculate mean and standard deviation, removing the TOB SO4 replicates and previous replicates of the clean deletion since they had different concentrations of TOB and were below the limit of detection.
percentChange<-cleanDelEndpointDataEndpointOnly%>%
  filter(!condition %in% c("cleanDelScfm128", "cleanDelScfm64"))%>%
  filter(!antibiotic == "TOB SO4")%>%
  filter(timePoint == 5 & bug == "Sa")%>%
  mutate(logTransform = log10(CFU))%>% 
  group_by(culture,sample)%>% mutate(LogKill = logTransform-logTransform[antibiotic=="TOB"]) %>% ungroup() 

percentChange <- percentChange %>% group_by(culture, antibiotic) %>% mutate(MeanLogKill = mean(LogKill), SeLogKill = std.error(LogKill)) %>% ungroup()
percentChange$culture <- factor(percentChange$culture, levels = c("mono", "wt", "mut"))
```

```{r graphing pooled data} 
#now lets graph to see the inoculum consistency:
ggplot()+ 
  geom_jitter(data=cleanDelEndpointDataEndpointOnly %>% filter(timePoint==0) , aes(x=sample, y=CFU, color =condition, shape = culture), height = 0, width = .2, size=4)+
  scale_y_log10(name=expression(paste('CFUs per mL' )), breaks = scales::trans_breaks("log10", function(x) 10^x), labels = scales::trans_format("log10", scales::math_format(10^.x)))+
  labs(title =expression(paste(italic("S. aureus"), " inoculum")), x = "Sample",color = "Culture condition") + 
  theme_cowplot()+
  panel_border()+
  background_grid()

#and control end point
ggplot()+
  geom_jitter(data=cleanDelEndpointDataEndpointOnly %>% filter(timePoint==5 & antibiotic == "Control") , aes(x=sample, y=CFU, color = condition, shape = culture), height = 0, width = .2, size=4)+
  scale_y_log10(name=expression(paste('CFUs per mL' )), breaks = scales::trans_breaks("log10", function(x) 10^x), labels = scales::trans_format("log10", scales::math_format(10^.x)))+
  labs(title =expression(paste(italic("S. aureus"), " end point")), x = "Sample",color = "Culture condition") +
  theme_cowplot()+
  panel_border()+
  background_grid()

#this is all the data
ggplot()+
  geom_jitter(data=cleanDelEndpointDataEndpointOnly %>% filter(timePoint==0) , aes(x=sample, y=CFU, shape =culture), height = 0, width = .2, size = 3, color = "black")+
  geom_jitter(data=cleanDelEndpointDataEndpointOnly %>% filter( timePoint==5) , aes(x=sample, y=CFU, color = antibiotic, shape =culture), height = 0, width = .2, size = 3)+
  scale_y_log10(name=expression(paste('CFUs per mL' )), breaks = scales::trans_breaks("log10", function(x) 10^x), labels = scales::trans_format("log10", scales::math_format(10^.x)))+
  labs(title =expression(paste(italic("S. aureus"), " inoculum and end point")), x = "Sample",shape = "Culture",color = "Condition") +
  facet_grid(.~condition,scales = "free", space = "free")+
  theme_cowplot()+
  panel_border()+
  background_grid()
```

```{r data wrangling with all data}
#this is the difference between wt and mutant logs
allDataNoControl <- cleanDelEndpointDataEndpointOnly %>% filter(timePoint == 5 & bug == "Sa") %>% filter(!antibiotic =="Control") %>% mutate(logTransform = log10(CFU))

allDataNoControlCoComparison <- cleanDelEndpointDataEndpointOnly %>% filter(timePoint == 5 & bug == "Sa") %>% filter(!culture == "mono") %>% filter(!antibiotic =="Control") %>% mutate(logTransform = log10(CFU))%>% group_by(sample,bug,timePoint,antibiotic)%>% mutate(difCoC =logTransform[culture=="wt"]-logTransform[culture=="mut"])
#this is the difference between mono and wt logs
allDataNoControlMonoWtComparison <- cleanDelEndpointDataEndpointOnly %>% filter(timePoint == 5 & bug == "Sa") %>% filter(!culture == "mut") %>% filter(!antibiotic =="Control") %>% mutate(logTransform = log10(CFU))%>% group_by(sample,bug,timePoint,antibiotic)%>% mutate(difCoC =logTransform[culture=="mono"]-logTransform[culture=="wt"]) 
#this is the difference between mono and mut logs
allDataNoControlMonoMutComparison <- cleanDelEndpointDataEndpointOnly %>% filter(timePoint == 5 & bug == "Sa") %>% filter(!culture == "wt") %>% filter(!antibiotic =="Control") %>% mutate(logTransform = log10(CFU))%>% group_by(sample,bug,timePoint,antibiotic)%>% mutate(difCoC =logTransform[culture=="mono"]-logTransform[culture=="mut"]) 

differenceLog<-bind_rows(allDataNoControlMonoWtComparison%>% filter(culture=="wt"),allDataNoControlCoComparison%>% filter(culture=="mut"),allDataNoControlMonoMutComparison%>% filter(culture=="mono") )
#here I will calculate mean and standard deviation, removing the TOB SO4 replicates and previous replicates of the clean deletion since they had different concentrations of TOB and were below the limit of detection.
differenceLog<-differenceLog %>%filter (!condition %in% c("cleanDelScfm128", "cleanDelScfm64")) %>% filter(!antibiotic == "TOB SO4") %>% group_by(culture) %>% mutate(meanDifference = mean(difCoC), sdDifference = sd(difCoC), seDifference = std.error(difCoC)) %>% ungroup()

```

```{r graphing wrangled data}
#This is all the data without any stats
ggplot()+
  geom_point(data=differenceLog , aes(x=sample, y=difCoC, color = culture),size=4)+
  #scale_y_log10(name=expression(paste('CFUs per mL' )), breaks = scales::trans_breaks("log10", function(x) 10^x), labels = scales::trans_format("log10", scales::math_format(10^.x)))+
  labs(title =expression(paste(italic("S. aureus"), " end point")), x = "Sample",color = "Culture condition") +
  theme_cowplot()+
  panel_border()+
  background_grid()

#Adding stats
ggplot()+
  geom_jitter(data=differenceLog , aes(x=culture, y=difCoC, color = culture),height = 0, width = .2,shape = 1, size=2)+
  geom_point(data=differenceLog , aes(x=culture, y=meanDifference, color = culture),size=4)+
  geom_errorbar(data=differenceLog , aes(x=culture, ymax=meanDifference+sdDifference,ymin=meanDifference-sdDifference, color = culture),size=1,width = .5)+
  geom_errorbar(data=differenceLog , aes(x=culture, ymax=meanDifference+(2*sdDifference),ymin=meanDifference-(2*sdDifference), color = culture),linetype = "dashed", size=.5,width = .5)+
  geom_errorbar(data=differenceLog , aes(x=culture, ymax=meanDifference+(3*sdDifference),ymin=meanDifference-(3*sdDifference), color = culture),linetype = "dotted", size=.5,width = .5)+
  labs(title =expression(paste(italic("S. aureus"), " end point log differences between conditions (SD)")),y = "Log10 Difference", x = "Sample",color = "Culture condition") +
  scale_color_discrete(labels=c("mono-culture vs w/Mutant","co-culture w/Mutant vs w/Wt","mono-culture vs co-culture w/Wt"))+
  theme_cowplot()+
  panel_border()+
  background_grid()

ggplot()+
  geom_jitter(data=differenceLog , aes(x=culture, y=difCoC, color = culture),height = 0, width = .2,shape = 1, size=2)+
  geom_point(data=differenceLog , aes(x=culture, y=meanDifference, color = culture),size=4)+
  geom_errorbar(data=differenceLog , aes(x=culture, ymax=meanDifference+seDifference,ymin=meanDifference-seDifference, color = culture),size=1,width = .5)+
  labs(title =expression(paste(italic("S. aureus"), " end point log differences between conditions (SE)")),y = "Log10 Difference", x = "Sample",color = "Culture condition") +
  scale_color_discrete(labels=c("mono-culture vs w/Mutant","co-culture w/Mutant vs w/Wt","mono-culture vs co-culture w/Wt"))+
  theme_cowplot()+
  panel_border()+
  background_grid()

#find trends between the killing of TOB   

```

```{r exploring the wilcoxon.test function}
#first try magnitude
wilcox.test(c(1,2,3,  2,3,4) ~ c(1, 1, 1, 2, 2, 2))#this ties and p = .3687
wilcox.test(c(1,2,3,  4,3,2) ~ c(1, 1, 1, 2, 2, 2))#this ties and p = .3687 #this shows that this is not paired

wilcox.test(c(1,2,3,  2,3,4) ~ c(1, 1, 1, 2, 2, 2), paired = T)#this ties and p = .1489
wilcox.test(c(3,2,1,  2,3,4) ~ c(1, 1, 1, 2, 2, 2), paired = T)#this ties and p = .5862
wilcox.test(c(1,2,3,  4,3,2) ~ c(1, 1, 1, 2, 2, 2), paired = T)#this ties and p = .5862 #this shows that this is paired and order matters
#Does magnitude matter?
wilcox.test(c(1,2,3,  2,3,4) ~ c(1, 1, 1, 2, 2, 2), paired = T)#this ties and p = .1489
wilcox.test(c(1,2,3,  3,4,5) ~ c(1, 1, 1, 2, 2, 2), paired = T)#this ties and p = .1489 #Nope! Magnitude doesnt matter
wilcox.test(c(1,2,3,  300,400,500) ~ c(1, 1, 1, 2, 2, 2), paired = T)#this ties and p = .25 #yeah, it does, but idk how
wilcox.test(c(1,2,3,  300,301,302) ~ c(1, 1, 1, 2, 2, 2), paired = T)#this ties and p = .1489 #what seems to matter is the difference between them
wilcox.test(c(1,2,3,  5,5,5) ~ c(1, 1, 1, 2, 2, 2), paired = T)#this doesn't tie and p = .25 #wtf???
#so the tie seems to be the difference between the vectors, not the repeated numbers, and it just throws them out
wilcox.test(c(1,2,3,  5,5,6) ~ c(1, 1, 1, 2, 2, 2), paired = T)#this ties and p = .1736, here there's only one tie...
#and if there are no ties, 3 replicates per condition and all by a different number, then the p-value will be .25
wilcox.test(c(1,2,3,  6,6,6) ~ c(1, 1, 1, 2, 2, 2), paired = T)#this doesn't tie and p = .25 again
#so... what if I have more replicates?
wilcox.test(c(1,1,1,1,  6,6,6,6) ~ c(1, 1, 1, 1, 2, 2, 2,2), paired = T)#this ties and p = .07186
wilcox.test(c(1,2,3,4,  6,6,6,6) ~ c(1, 1, 1, 1, 2, 2, 2,2), paired = T)#this doesn't tie and p = .125
wilcox.test(c(1,2,3,4,5,  6,6,6,6,6) ~ c(1, 1, 1, 1,1,2, 2, 2, 2,2), paired = T)#this doesn't tie and p = .0625
wilcox.test(c(1,2,3,4,5,6,  7,7,7,7,7,7) ~ c(1, 1, 1, 1,1,1,2,2, 2, 2, 2,2), paired = T)#this doesn't tie and p = .03125
#what is weird is that if the difference between them is the same, aka there's a tie, then p-value goes down..
wilcox.test(c(1,2,3,4,5,6,  7,7,7,7,6,7) ~ c(1, 1, 1, 1,1,1,2,2, 2, 2, 2,2), paired = T)#this ties and p = .03552, now this is weird, one tie increases the metric
wilcox.test(c(1,2,3,4,5,6,  7,7,7,5,6,7) ~ c(1, 1, 1, 1,1,1,2,2, 2, 2, 2,2), paired = T)#this ties and p = .03401, 2 ties...
wilcox.test(c(1,2,3,4,5,6,  7,7,4,5,6,7) ~ c(1, 1, 1, 1,1,1,2,2, 2, 2, 2,2), paired = T)#this ties and p = .03103, 3 ties...
wilcox.test(c(1,2,3,4,5,6,  7,3,4,5,6,7) ~ c(1, 1, 1, 1,1,1,2,2, 2, 2, 2,2), paired = T)#this ties and p = .02627, 4 ties...
wilcox.test(c(1,2,3,4,5,6,  2,3,4,5,6,7) ~ c(1, 1, 1, 1,1,1,2,2, 2, 2, 2,2), paired = T)#this ties and p = .01966, these are all ties
#so I think I should have my answer now... I need 6 samples for it to be significant, and in this case I can just use both the mutant and the clean deletion replicates


```

```{r Wilcoxon Tests}
#Wilcoxon test:
#it works better with log CFUs than CFUs, so I'll stick to it...

wtMonoWilcoxonLogAll<- wilcox.test(allDataEndPointAll %>% filter(culture == "mono"& antibiotic == "TOB") %>% pull(logTransform),
                    allDataEndPointAll %>% filter(culture == "wt"& antibiotic == "TOB") %>% pull(logTransform),paired = T)

mutWtWilcoxonLogAll<- wilcox.test(allDataEndPointAll %>% filter(culture == "wt" & antibiotic == "TOB") %>% pull(logTransform),
                    allDataEndPointAll %>% filter(culture == "mut"& antibiotic == "TOB") %>% pull(logTransform),paired = T, exact = T)

mutMonoWilcoxonLogAll<- wilcox.test(allDataEndPointAll %>% filter(culture == "mono"& antibiotic == "TOB") %>% pull(CFU),
                                    allDataEndPointAll %>% filter(culture == "mut"& antibiotic == "TOB") %>% pull(CFU),paired = T)

mutMonoWilcoxonLog<- wilcox.test(allDataEndPointAll %>% filter(culture == "mono" & antibiotic == "TOB" &condition %in% c("cleanDelEndpoint", "mutLib128")) %>% pull(logTransform),
                                 allDataEndPointAll %>% filter(culture == "mut"& antibiotic == "TOB"&condition%in% c("cleanDelEndpoint", "mutLib128")) %>% pull(logTransform),paired = T)

wtMonoWilcoxonLog<- wilcox.test(allDataEndPointAll %>% filter(culture == "mono" & antibiotic == "TOB" &condition %in% c("cleanDelEndpoint", "mutLib128")) %>% pull(logTransform),
                                allDataEndPointAll %>% filter(culture == "wt"& antibiotic == "TOB"&condition%in% c("cleanDelEndpoint", "mutLib128")) %>% pull(logTransform),paired = T)

mutWtWilcoxonLog<- wilcox.test(allDataEndPointAll %>% filter(culture == "wt" & antibiotic == "TOB" &condition %in% c("cleanDelEndpoint", "mutLib128")) %>% pull(logTransform),
                               allDataEndPointAll %>% filter(culture == "mut"& antibiotic == "TOB"&condition%in% c("cleanDelEndpoint", "mutLib128")) %>% pull(logTransform),paired = T)

wilcoxDataAll<- allDataEndPoint%>% filter(timePoint == 5 & bug == "Sa") %>% filter(!antibiotic == "TOB SO4") %>% mutate(logTransform = log10(CFU))


```

```{r What is the wilcoxon test comparing?}
wilcoxDataAll<- cleanDelEndpointDataEndpointOnly%>% filter(timePoint == 5 & bug == "Sa") %>% filter(!antibiotic == "TOB SO4") %>% mutate(logTransform = log10(CFU)) %>% group_by(culture, antibiotic)%>%  mutate(meanLog = mean (logTransform), sdLog = sd(logTransform), seLog = std.error(logTransform))
wilcoxDataAll$culture <- factor(wilcoxDataAll$culture, levels = c("mono", "wt", "mut"))

wilcoxDataGood<-cleanDelEndpointDataEndpointOnly%>% filter(timePoint == 5 & bug == "Sa") %>%  filter(!antibiotic == "TOB SO4") %>% filter(condition %in% c("cleanDelEndpoint", "mutLib128"))%>% mutate(logTransform = log10(CFU)) %>% group_by(culture, antibiotic) %>% mutate(meanLog = mean (logTransform), sdLog = sd(logTransform), seLog = std.error(logTransform))
wilcoxDataGood$culture <- factor(wilcoxDataGood$culture, levels = c("mono", "wt", "mut"))

ggplot()+
  geom_jitter(data=wilcoxDataAll , aes(x=culture, y=logTransform),height = 0, width = .2,shape = 1, size=2)+
  geom_point(data=wilcoxDataAll , aes(x=culture, y=meanLog),size=4)+
  geom_errorbar(data=wilcoxDataAll , aes(x=culture, ymax=meanLog+sdLog,ymin=meanLog-sdLog),size=1,width = .5)+
  labs(title =expression(paste(italic("S. aureus"), " end point log differences between conditions")),y = "Log10 Difference", x = "Sample",color = "Culture condition") +
  scale_color_discrete(labels=c("co-culture w/Mutant vs w/Wt ","mono-culture vs co-culture w/Wt "))+
  #facet_grid(.~condition,scales = "free", space = "free")+
  theme_cowplot()+
  panel_border()+
  background_grid()

ggplot()+
  geom_jitter(data=wilcoxDataGood , aes(x=culture, y=logTransform),height = 0, width = .2,shape = 1, size=2)+
  geom_point(data=wilcoxDataGood , aes(x=culture, y=meanLog),size=4)+
  geom_errorbar(data=wilcoxDataGood , aes(x=culture, ymax=meanLog+sdLog,ymin=meanLog-sdLog),size=1,width = .5)+
  labs(title =expression(paste(italic("S. aureus"), " end point Tobramycin")),y = "Log10 CFUs", x = "Sample",color = "Culture condition") +
  scale_color_discrete(labels=c("co-culture w/Mutant vs w/Wt ","mono-culture vs co-culture w/Wt "))+
  #facet_grid(.~condition,scales = "free", space = "free")+
  theme_cowplot()+
  panel_border()+
  background_grid()

ggplot() +
  geom_col(data = wilcoxDataAll, aes (x = culture, y = meanLog, fill = antibiotic, group = antibiotic), position = position_dodge( ))+
  geom_linerange(data = wilcoxDataAll, aes(x = culture, ymin = meanLog - sdLog, ymax = meanLog + sdLog,group = antibiotic),position = position_dodge(width = .9))+
  scale_y_continuous(expand = expand_scale(mult = c(0, 0.05)))+
  labs(title =expression(paste(italic("S. aureus"), " growth at 5 hours (all data)")),y = "Log10 CFUs", x = "Culture condition") +
  scale_fill_grey()+
  theme_cowplot()+
  theme_half_open()+
  background_grid()
ggsave("plotEndPointAllData.eps", dpi = "print", width = 8, height = 6)

ggplot() +
  geom_col(data = wilcoxDataGood, aes (x = culture, y = meanLog, fill = antibiotic, group = antibiotic), position = position_dodge( ))+
  geom_linerange(data = wilcoxDataGood, aes(x = culture, ymin = meanLog - seLog, ymax = meanLog + seLog,group = antibiotic),position = position_dodge(width = .9))+
  scale_y_continuous(expand = expand_scale(mult = c(0, 0.05)))+
  labs(title =expression(paste(italic("S. aureus"), " growth at 5 hours")),y = "Log10 CFUs", x = "Culture condition") +
  scale_fill_grey()+
  theme_cowplot()+
  theme_half_open()+
  background_grid()
ggsave("plotEndPointGoodData.eps", dpi = "print", width = 8, height = 6)
```

```{r paper figures}
#All data
ggplot()+
  geom_jitter(data=cleanDelEndpointDataEndpointOnly %>% filter(bug == "Sa") %>% filter(condition %in% c("mutLib128", "cleanDelEndpoint")) %>% filter(!antibiotic == "TOB SO4") , aes(x=timePoint, y=CFU, color = culture), height = 0, width = .2, size=4)+
  scale_y_log10(name=expression(paste('CFUs per mL' )), breaks = scales::trans_breaks("log10", function(x) 10^x), labels = scales::trans_format("log10", scales::math_format(10^.x)))+
  geom_vline(xintercept=3, linetype = "dashed")+
  annotate("text", x = 3, y = 10e6, label = "TOB added")+
  labs(title =expression(paste(italic("S. aureus"), " growth in mono or coculture in SCFM2 with 256 ug/mL TOB")), x = "Time (hours)",shape = "Culture condition", color = "Antiobiotic/Control") +
  facet_grid(sample~antibiotic)+
  theme_cowplot()+
  panel_border()+
  background_grid()

#Ratio between end point conditions with std error
ggplot()+
  geom_jitter(data=differenceLog , aes(x=culture, y=difCoC, color = culture),height = 0, width = .2,shape = 1, size=2)+
  geom_point(data=differenceLog , aes(x=culture, y=meanDifference, color = culture),size=4)+
  geom_errorbar(data=differenceLog , aes(x=culture, ymax=meanDifference+seDifference,ymin=meanDifference-seDifference, color = culture),size=1,width = .5)+
  labs(title =expression(paste(italic("S. aureus"), " end point log differences between conditions (SE)")),y = "Log10 Difference", x = "Sample",color = "Culture condition") +
  scale_color_discrete(labels=c("mono-culture vs w/Mutant","co-culture w/Mutant vs w/Wt","mono-culture vs co-culture w/Wt"))+
  theme_cowplot()+
  panel_border()+
  background_grid()

#End point bar graph with std error
tobCFUPlot<-ggplot() +
  geom_col(data = wilcoxDataGood, aes (x = culture, y = meanLog, fill = antibiotic, group = antibiotic), position = position_dodge( ))+
  geom_linerange(data = wilcoxDataGood, aes(x = culture, ymin = meanLog - seLog, ymax = meanLog + seLog,group = antibiotic),position = position_dodge(width = .9))+
  scale_y_continuous(expand = expand_scale(mult = c(0, 0.05)), breaks = c(0,2,4,6,8,10), labels =c(0,2,4,6,8,10))+
  scale_x_discrete(name ="", breaks = c("mono","wt","mut"), labels =c("mono","co w/wild-type",expression("co w/"*Delta*"pqsL")))+
  labs(y = expression(paste(Log[10], " CFU")), x = "", fill = "") +
  scale_fill_grey()+
  theme_cowplot()+
  theme_half_open()+
  background_grid()

tobPercentChangePlot<-ggplot() +
  geom_col(data = percentChange %>% filter(sample == "1-25-20"), aes (x = culture, y = MeanLogKill))+
  geom_linerange(data = percentChange, aes(x = culture, ymin = MeanLogKill - SeLogKill/2, ymax = MeanLogKill + SeLogKill/2))+
  scale_y_continuous(expand = expand_scale(mult = c(0, 0.05)))+
  scale_x_discrete(name ="", breaks = c("mono","wt","mut"), labels =c("mono","co w/wild-type",expression("co w/"*Delta*"pqsL")))+
  labs(y = expression(paste(Log[10], " CFU")), x = "") +
  scale_fill_grey()+
  theme_cowplot()+
  theme_half_open()+
  background_grid()

prow <- plot_grid(tobCFUPlot+theme(legend.position="none"),tobPercentChangePlot+theme(legend.position="none"),align='vh',labels = c("A", "B"),hjust = -1,nrow = 1)
legend <- get_legend(tobCFUPlot + theme(legend.box.margin = margin(0, 0, 0, -6)))
plot_grid(prow,legend,rel_widths = c(3, .4))
```