---
title: "Growth Curves Paper"
author: "Juan P Barraza"
date: "8/14/2019"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
library(pixmap)
library(rtiff)
library(reshape2)
library(gplots)
library(dplyr)
library(gdata)
library(ggplot2)
library(cowplot)
library(magrittr)
library(tidyr)
library(plotrix)
library(purrr)
library(moderndive)
```
```{r data gathering functions}
#Data gathering functions:
GetGrowthCurveReplicate<- function (sample){
  bugCounts<-read.csv(paste0("/Users/jupabago/Documents/Whiteley/PROJECTS/PaSaProject/Spatial paper Data/GrowthCurves/", sample, ".csv"),header = TRUE)
  bugCounts<- na.omit(bugCounts)
  bugCounts<-bugCounts %>% mutate(logCFU = log10(CFU))
  bugCounts$sample<-sample
  return(bugCounts)
}
GetGrowthCurveCondition<-function(datalist){
  mappedData<-map(datalist, GetGrowthCurveReplicate)#this line reads all the files on the list
  boundData<-bind_rows(mappedData)
  colnames(boundData)[5] <- "strain"
  colnames(boundData)[8] <- "condition"
  return(boundData)
}
```

```{r graphing functions}
#Graphing functions

##this one graphs the log values
GraphGrowthCurveLog<-function (rawData, statsData){
    staticPlot<-ggplot()+
      geom_line(data=statsData%>% filter(bug == "Sa"& condition == "Static"), aes(x=time, y=logCFUmean, linetype = strain), size=1)+
      geom_errorbar(data=statsData%>% filter(bug == "Sa"& condition == "Static"), aes(x = time, ymin = logCFUmean-logCFUse, ymax = logCFUmean+logCFUse), width = 0, size = 1)+
      scale_linetype_manual(values = c( "dotted","solid"), labels = c("- HQNO", "wild type"))+
      labs(x = "Time (hours)", y = "log CFU", linetype = "Pa strain")+
      scale_y_continuous(limits = c(4,9))+
      theme_cowplot(12)
    
    wellmixedPlot<-ggplot()+
      geom_line(data=statsData%>% filter(bug == "Sa" & condition == "Shaking"), aes(x=time, y=logCFUmean, linetype = strain), size=1)+
      geom_errorbar(data=statsData%>% filter(bug == "Sa"& condition == "Shaking"), aes(x = time, ymin = logCFUmean-logCFUse, ymax = logCFUmean+logCFUse), width = 0, size = 1)+
      scale_linetype_manual(values = c( "dotted", "solid"), labels = c("- HQNO","wild type"))+
      labs(x = "Time (hours)", y = "log CFU", linetype = "Pa strain")+
      scale_y_continuous(limits=c(4,9))+
      theme_cowplot(12)
    legend <- get_legend(staticPlot + theme(legend.box.margin = margin(0, 0, 0, 12)))
    prow <- plot_grid(wellmixedPlot+theme(legend.position="none"),staticPlot+theme(legend.position="none"),align='vh',labels = c("A", "B"),hjust = -1,nrow = 1)
    plot_grid(prow,legend,rel_widths = c(3, .4))
}
GraphGrowthCurveLog1<-function (rawData, statsData){
    wtPlot<-ggplot()+
      geom_line(data=statsData%>% filter(bug == "Sa"& strain == "wt"), aes(x=time, y=logCFUmean, linetype = condition), size=1)+
      geom_errorbar(data=statsData%>% filter(bug == "Sa"& strain == "wt"), aes(x = time, ymin = logCFUmean-logCFUse, ymax = logCFUmean+logCFUse), width = 0, size = 0.5)+
      scale_linetype_manual(values = c( "solid","dotted"), labels = c("well-mixed","static"))+
      labs(x = "Time (hours)", y = "log CFU", linetype = "Condition")+
      scale_y_continuous(limits = c(4,9.2))+
      scale_x_continuous(breaks = c(4,8,12,16))+
      theme_cowplot(12)
    
    hqnoPlot<-ggplot()+
      geom_line(data=statsData%>% filter(bug == "Sa" & strain == "mut"), aes(x=time, y=logCFUmean, linetype = condition), size=1)+
      geom_errorbar(data=statsData%>% filter(bug == "Sa"& strain == "mut"), aes(x = time, ymin = logCFUmean-logCFUse, ymax = logCFUmean+logCFUse), width = 0, size = 0.5)+
      scale_linetype_manual(values = c( "solid","dotted"), labels = c("well-mixed","static"))+
      labs(x = "Time (hours)", y = "log CFU", linetype = "Condition")+
      scale_y_continuous(limits=c(4,9.2))+
      scale_x_continuous(breaks = c(4,8,12,16))+
      theme_cowplot(12)
    legend <- get_legend(wtPlot + theme(legend.box.margin = margin(0, 0, 0, 12)))
    prow <- plot_grid(wtPlot+theme(legend.position="none"),hqnoPlot+theme(legend.position="none"),align='vh',labels = c("A", "B"),hjust = -1,nrow = 1)
    plot_grid(prow,legend,rel_widths = c(3, .4))
    }
##this one graphs the normal values
GraphGrowthCurve<-function (rawData, statsData){
    ggplot()+ 
    geom_point(data=rawData, aes(x=time, y=CFU,color = bug, shape = strain),   size=2)+
    geom_line(data=statsData, aes(x=time, y=CFUmean,  color = bug, linetype = strain), size=1)+
    geom_errorbar(data=statsData, aes(x = time, ymin = CFUmean-CFUsd, ymax = CFUmean+CFUsd, color = bug, linetype = strain), width = 0, size = 1)+
    labs(title =paste("Growth in SCFM2" ),  x = "Time (hours)",shape = "strain", color = "Species")+
    scale_y_log10(name=expression(paste('CFUs per mL' )), breaks = scales::trans_breaks("log10", function(x) 10^x), labels = scales::trans_format("log10", scales::math_format(10^.x)))+
    facet_grid(.~condition)
}

GetNumber<-function(idx){
  if (idx<10){
    idx = paste0(0,idx)
  }
  return (idx)
}
```

```{r CFU results}
#these are the list with the spreadsheets of experiments under different conditions
PA14 = c('2-11-19','2-7-19','2-5-19')
#get data
PA14Data<-GetGrowthCurveCondition(PA14)
PA14Data$strain <- factor(PA14Data$strain, levels = c("wt", "mut"))

#do stats
PA14DataStats<-PA14Data%>% group_by(condition, bug, time,strain) %>% summarise(CFUmean = mean (CFU), CFUsd = sd(CFU), CFUse = std.error(CFU), logCFUmean = mean (logCFU), logCFUsd = sd(logCFU),logCFUse = std.error(logCFU))
#Graph logs
GraphGrowthCurveLog(PA14Data,PA14DataStats)
GraphGrowthCurveLog1(PA14Data,PA14DataStats)
#Graph regular numbers
GraphGrowthCurve(PA14Data,PA14DataStats)
```

```{r Confocal data wrangling}
#first pull confocal data:
##functions to read data
MapResults<- function(listSamples, reps){
  blah <-deparse(substitute(listSamples))
  mappedData<-map2(listSamples, reps, GetResults)
  boundData<-bind_rows(mappedData)
  boundData<-boundData %>% mutate(Strain = blah)
  boundData<-gather(boundData,"Color","Value",-Slice,-Position,-Sample,-TimePoint,-Strain) %>% mutate(LogValue=ifelse(Value>0,log10(Value),0))
  boundData<-boundData %>% mutate(Condition = recode(Position, "0" = "Sa Mono", "1" = "Pa Mono", "2" = "Pa:Sa 1:1", "3" = "Pa:Sa 10:1", "4" = "Pa:Sa 1:100", "5" = "Pa:Sa 1:10" )) %>% mutate(Species = recode(Color, "Red" = "Sa", "Green" = "Pa")) %>% mutate(ZDistance = Slice *0.44)
  boundData$Condition<-as.factor(boundData$Condition)
  boundData$Condition<-factor(boundData$Condition, levels = c("Sa Mono", "Pa Mono", "Pa:Sa 1:1", "Pa:Sa 1:10", "Pa:Sa 1:100","Pa:Sa 10:1"))
  boundData$Species<-as.factor(boundData$Species)
  boundData$Strain<-as.factor(boundData$Strain)
  return(boundData)
  }
ReadResultsFile<-function(file, position, timepoint){
  datos <-read.csv(file, header = FALSE)
  colnames(datos)<-c('Red', 'Green', 'Slice')
  datos<-datos %>% mutate(Position = position)
  datos<-datos %>% mutate(TimePoint = timepoint)
  return(datos)
}
GetResults<-function(sample, samplename){
  folder<- paste0('/Users/jupabago/Documents/Whiteley/PROJECTS/PaSaProject/Spatial paper Data/Microscopy Data/Other Data1/',sample,'/results')#the path needs to be "Other Data1"
  fileList<-list.files(path = folder, full.names = TRUE)
  growthDf<-data.frame()
  for (position in 0:5){
    currentPosition<-fileList[grep(paste0("p",position,"."),fileList)]
    for (timepoint in 0:17){
      currentTimePoint<-currentPosition[grep(paste0("t",GetNumber(timepoint),"_"),currentPosition)]
      growthDf<-rbind(growthDf,ReadResultsFile(currentTimePoint, position, timepoint))}}
  growthDf<-growthDf %>% mutate(Sample = samplename)
return(growthDf)
}

PA14wt<- c('3-13-19', '3-19-19', '4-17-19')#sample names 
PA14mut<- c('4-24-19', '4-25-19', '5-8-19')
names3<-c('rep1','rep2','rep3')

wtConfocalResults<-MapResults(PA14wt, names3)
mutConfocalResults<-MapResults(PA14mut, names3)
#combine them:
allConfocalResults<-rbind(wtConfocalResults,mutConfocalResults)
#Get stats:
##this adds up all the data on each slice and then gets the log of that total
allConfocalResults<-allConfocalResults %>% group_by(TimePoint,Sample,Strain,Condition,Species) %>% summarise(Totals = sum (Value))%>% mutate(LogTotals = ifelse(Totals>0, log10(Totals), 0))

##this calculates mean and error
allConfocalResultsStats<-allConfocalResults %>% group_by(TimePoint,Strain,Condition,Species) %>% summarise(MeanTotals = mean(Totals), SDTotals = sd(Totals), MeanLogTotals = mean(LogTotals), SDLogTotals = sd(LogTotals)) 

##remove all the conditions I didn't do in the plate counts and fix time points:
DataComparisonScope<-allConfocalResultsStats %>% filter (Strain %in% c("PA14wt","PA14mut")) %>% filter(Condition == "Pa:Sa 1:1") %>%  filter(TimePoint %in% c(0,3,7,11,15)) %>% select(Condition,TimePoint, Strain, Species, MeanTotals, MeanLogTotals) %>% mutate(time = ifelse(TimePoint>0, TimePoint+1, 0)) #The timePoint thing is because I start imaging after one hour and I don't have a time zero on scope
```


```{r CFU data wrangling}

#GROWTH CURVES PLATE COUNTS DATA
##remove stirred condition I didn't do in the scope and fix strain names:
DataComparisonCFU<-PA14DataStats %>% filter (condition == "Static") %>% select(bug, strain, CFUmean, logCFUmean, condition, time)%>% as.data.frame() 
DataComparisonCFU<-DataComparisonCFU%>% mutate(Strain = recode(DataComparisonCFU$strain, wt = "PA14wt", mut = "PA14mut"))#add new column with proper name

#name columns so that they match with the columns in the other df
colnames(DataComparisonCFU)<- c("Species", "strain", "CFUs", "logCFUs","Static", "time", "Strain")

#merge data frames and fix numeric for time
comparisonDf <- merge(DataComparisonCFU,DataComparisonScope,by=c("Species","Strain", "time"))
comparisonDf$time<-as.numeric(as.character(comparisonDf$time))

#FOR SA I can also use the Tob data, but first isolate from the other plate counts data:
DataComparisonCFUSaGrowthCurves<-DataComparisonCFU %>% filter(Species == "Sa") %>% select(Species, strain, CFUs, logCFUs, time, Strain)

#TOB PLATE COUNTS DATA
#this is dataframe is in the "SaPa TOB grwoth curves.RMD" file
#first select relevant conditions and fix column names
DataComparisonCFUSa<-newSCFMDataSa%>%  filter(!culture == "mono") %>% filter(antibiotic == "Control") %>% select(CFU, culture, bug, timePoint, antibiotic, logTranformed,sample, condition) %>% group_by(bug, culture, timePoint) %>% summarise(meanCFU = mean(CFU), meanLogCFU = mean(logTranformed)) %>% ungroup()  

DataComparisonCFUSa<-DataComparisonCFUSa%>% mutate(Strain = recode(DataComparisonCFUSa$culture, wt = "PA14wt", mut = "PA14mut"))
colnames(DataComparisonCFUSa)<-c("Species", "strain", "time", "CFUs", "logCFUs", "Strain")

DataCFUAllSa<-bind_rows(DataComparisonCFUSa,DataComparisonCFUSaGrowthCurves)#combine growth curves and TOB
DataCFUAllSa<-DataCFUAllSa%>% group_by(Strain,time) %>% summarise(CFU = mean(CFUs), LogCFU = mean(logCFUs)) %>% ungroup()  

#then do the same for the scope data
DataComparisonScopeSa<-allConfocalResultsStats %>% filter(Species == "Sa")%>% filter (Strain %in% c("PA14wt","PA14mut")) %>% filter(Condition == "Pa:Sa 1:1") %>%  filter(TimePoint %in% c(0,2,3,4,7,11,15)) %>% select(Condition,TimePoint, Strain, Species, MeanTotals, MeanLogTotals) %>% mutate(time = ifelse(TimePoint>0, TimePoint+1, 0)) #The timePoint thing is because I start imaging after one hour and I don't have a time zero on scope
#merge them!
comparisonSaDf <- merge(DataCFUAllSa,DataComparisonScopeSa,by=c("time","Strain"))
comparisonSaDfTOB <- merge(DataComparisonCFUSa,DataComparisonScopeSa,by=c("time","Strain"))

```
```{r microscopy data from different thresholds}
linear1Stats<-linear1[[2]] %>% filter(Species == "Sa")%>% filter (Strain %in% c("PA14wt","PA14mut")) %>% filter(Condition == "Pa:Sa 1:1") %>%  filter(TimePoint %in% c(0,2,3,4,7,11,15)) %>% select(Condition,TimePoint, Strain, Species, MeanTotals, MeanLogTotals) %>% mutate(time = ifelse(TimePoint>0, TimePoint+1, 0))

linear2Stats<-linear2[[2]] %>% filter(Species == "Sa")%>% filter (Strain %in% c("PA14wt","PA14mut")) %>% filter(Condition == "Pa:Sa 1:1") %>%  filter(TimePoint %in% c(0,2,3,4,7,11,15)) %>% select(Condition,TimePoint, Strain, Species, MeanTotals, MeanLogTotals) %>% mutate(time = ifelse(TimePoint>0, TimePoint+1, 0))

linear4Stats<-linear4[[2]] %>% filter(Species == "Sa")%>% filter (Strain %in% c("PA14wt","PA14mut")) %>% filter(Condition == "Pa:Sa 1:1") %>%  filter(TimePoint %in% c(0,2,3,4,7,11,15)) %>% select(Condition,TimePoint, Strain, Species, MeanTotals, MeanLogTotals) %>% mutate(time = ifelse(TimePoint>0, TimePoint+1, 0))

linear5Stats<-linear5[[2]] %>% filter(Species == "Sa")%>% filter (Strain %in% c("PA14wt","PA14mut")) %>% filter(Condition == "Pa:Sa 1:1") %>%  filter(TimePoint %in% c(0,2,3,4,7,11,15)) %>% select(Condition,TimePoint, Strain, Species, MeanTotals, MeanLogTotals) %>% mutate(time = ifelse(TimePoint>0, TimePoint+1, 0))

linear6Stats<-linear6[[2]] %>% filter(Species == "Sa")%>% filter (Strain %in% c("PA14wt","PA14mut")) %>% filter(Condition == "Pa:Sa 1:1") %>%  filter(TimePoint %in% c(0,2,3,4,7,11,15)) %>% select(Condition,TimePoint, Strain, Species, MeanTotals, MeanLogTotals) %>% mutate(time = ifelse(TimePoint>0, TimePoint+1, 0))


#merging with the whole growth curve data, not only TOB
comparisonSaDflinear1 <- merge(DataCFUAllSa,linear1Stats,by=c("time","Strain"))
comparisonSaDflinear2 <- merge(DataCFUAllSa,linear2Stats,by=c("time","Strain"))
comparisonSaDflinear4 <- merge(DataCFUAllSa,linear4Stats,by=c("time","Strain"))
comparisonSaDflinear5 <- merge(DataCFUAllSa,linear5Stats,by=c("time","Strain"))
comparisonSaDflinear6 <- merge(DataCFUAllSa,linear6Stats,by=c("time","Strain"))


```


```{r graph CFU vs Confocal Pa}
#Graph both Pa and Sa
##Original data as input:
ggplot()+
    geom_point(data=comparisonDf, aes(x=CFUs, y=MeanTotals,color = Species, shape = Strain),   size=4)+
    scale_y_log10(breaks = scales::trans_breaks("log10", function(x) 10^x), labels = scales::trans_format("log10", scales::math_format(10^.x)))+
    scale_x_log10(breaks = scales::trans_breaks("log10", function(x) 10^x), labels = scales::trans_format("log10", scales::math_format(10^.x)))

##Log-tranformed data as input:
ggplot()+
    geom_point(data=comparisonDf, aes(x=logCFUs, y=MeanLogTotals, color = Species, shape = Strain),   size=4)

#Pa seems to be pretty straightforward, lets do linear regression:
Pa14LinearModel <- lm(MeanLogTotals ~logCFUs, data = comparisonDf %>% filter (Species == "Pa"))
coefficients(Pa14LinearModel)
get_regression_summaries(Pa14LinearModel, print = TRUE)

##Log-tranformed data as input for PA14 only:
ggplot()+
  geom_abline(intercept = 1.9623899, slope = 0.4639804, color = "red", size = 3 )+
  geom_point(data=comparisonDf%>% filter(Species == "Pa"), aes(x=logCFUs,y=MeanLogTotals,  color = Species, shape = Strain),   size=4)
#then fit it without the zero point since that was not even at the same time
Pa14LinearModel1 <- lm(MeanLogTotals ~logCFUs, data = comparisonDf %>% filter (Species == "Pa") %>% filter(!time == 0))
get_regression_summaries(Pa14LinearModel1, print = TRUE)
  ggplot()+
    geom_abline(intercept =-2.882887,slope = 1.006844, color = "red", size = 1, linetype = "dashed" )+
    geom_point(data=comparisonDf %>% filter(Species == "Pa"), aes(x=logCFUs,y=MeanLogTotals,  color = time, shape = Strain),size=4)+
    scale_color_gradient(low="blue", high="red")+
    annotate("text", x = 7.5, y = 6, label = expression(paste("y=1.007x-2.883  ", R^2, "= 0.9")), color = "red", size = 8)+
    labs(title =expression(paste(italic("P. aeruginosa"), " CFU vs Confocal Biomass")), x = "Log CFUs",y = "Biomass from Scope")

```

```{r graph CFU vs Confocal Sa}
  
  
#Now we go to Sa
#this is using only Growth cruves data
SaLinearModel <- lm(MeanLogTotals ~logCFUs, data = comparisonDf %>% filter (Species == "Sa")%>% filter(!time == 0))
coefficients(SaLinearModel)
get_regression_summaries(SaLinearModel, print = TRUE)

ggplot()+
  geom_point(data=comparisonDf %>% filter(Species == "Sa"), aes(x=logCFUs,y=MeanLogTotals,  color = time, shape = Strain),size=4)+
  geom_abline(intercept =25.73, slope = -2.44, color = "red", size = 1, linetype = "dashed" )+
  scale_color_gradient(low="blue", high="red")+
  annotate("text", x = 7.9, y = 4.5, label = expression(paste("y=-2.44x+25.73  ", R^2, "= 0.619")), color = "red", size = 8)+
  labs(title =expression(paste(italic("S. aureus"), " CFU vs Confocal Biomass")), x = "Log CFUs",y = "Biomass from CLSM")+
  theme_cowplot(12)
#adding TOB data only
SaLinearModelTOB <- lm(MeanLogTotals ~logCFUs, data = comparisonSaDfTOB%>% filter(!time == 0))
coefficients(SaLinearModelTOB)
get_regression_summaries(SaLinearModelTOB, print = TRUE)
ggplot()+
  geom_point(data=comparisonSaDf, aes(x=LogCFU,y=MeanLogTotals,  color = time, shape = Strain),size=4)+
  geom_abline(intercept =20.243855, slope = -1.810558, color = "red", size = 1, linetype = "dashed" )+
  scale_color_gradient(low="blue", high="red")+
  annotate("text", x = 7.9, y = 5.2, label = expression(paste("y=-1.810+20.243855 ", R^2, "= 0.631")), color = "red", size = 8)+
  labs(title =expression(paste(italic("S. aureus"), " CFU vs Confocal Biomass")), x = "Log CFUs",y = "Biomass from Scope")

#combining TOB and growth curves data
SaLinearModel2 <- lm(MeanLogTotals ~LogCFU, data = comparisonSaDf%>% filter(!time == 0))
coefficients(SaLinearModel2)
get_regression_summaries(SaLinearModel2, print = TRUE)
ggplot()+
  geom_point(data=comparisonSaDf, aes(x=LogCFU,y=MeanLogTotals,  color = time, shape = Strain),size=4)+
  geom_abline(intercept =20.243855, slope = -1.810558, color = "red", size = 1, linetype = "dashed" )+
  scale_color_gradient(low="blue", high="red")+
  annotate("text", x = 7.9, y = 5.2, label = expression(paste("y=-1.810+20.243855 ", R^2, "= 0.631")), color = "red", size = 8)+
  labs(title =expression(paste(italic("S. aureus"), " CFU vs Confocal Biomass")), x = "Log CFUs",y = "Biomass from Scope")

SaLinearModel3 <- lm(MeanLogTotals ~LogCFU, data = comparisonSaDf%>% filter(!time %in% c(0,16)))
coefficients(SaLinearModel3)
get_regression_summaries(SaLinearModel3, print = TRUE)

SaLinearModel4 <- lm(MeanLogTotals ~LogCFU, data = comparisonSaDf%>% filter(!time %in% c(0,12,16)))
coefficients(SaLinearModel4)
get_regression_summaries(SaLinearModel4, print = TRUE)

SaLinearModel5 <- lm(MeanLogTotals ~LogCFU, data = comparisonSaDf%>% filter(!time %in% c(0,8,12,16)))
coefficients(SaLinearModel5)
get_regression_summaries(SaLinearModel5, print = TRUE)
ggplot()+
  geom_point(data=comparisonSaDf, aes(x=LogCFU,y=MeanLogTotals,  color = time, shape = Strain),size=4)+
  geom_abline(intercept =-.982, slope = .7210531, color = "red", size = 1, linetype = "dashed" )+
  scale_color_gradient(low="blue", high="red")+
  annotate("text", x = 7.9, y = 5.2, label = expression(paste("y=-1.810+20.243855 ", R^2, "= 0.631")), color = "red", size = 8)+
  labs(title =expression(paste(italic("S. aureus"), " CFU vs Confocal Biomass")), x = "Log CFUs",y = "Biomass from Scope")

#Testing the images with different thresholds

SaLinearModelLinear1 <- lm(MeanLogTotals ~LogCFU, data = comparisonSaDflinear1%>% filter(!time %in% c(0,12,16)))
coefficients(SaLinearModelLinear1)

SaLinearModelLinear2 <- lm(MeanLogTotals ~LogCFU, data = comparisonSaDflinear2%>% filter(!time %in% c(0,12,16)))
coefficients(SaLinearModelLinear2)

SaLinearModelLinear4 <- lm(MeanLogTotals ~LogCFU, data = comparisonSaDflinear4%>% filter(!time %in% c(0,12,16)))
coefficients(SaLinearModelLinear4)

SaLinearModelLinear5 <- lm(MeanLogTotals ~LogCFU, data = comparisonSaDflinear5%>% filter(!time %in% c(0,8,12,16)))
coefficients(SaLinearModelLinear5)

SaLinearModelLinear6 <- lm(MeanLogTotals ~LogCFU, data = comparisonSaDflinear6%>% filter(!time %in% c(0,8,12,16)))
coefficients(SaLinearModelLinear6)


```

```{r using old Sa data instead? Nope, didnt work}
#Change the function so that it takes the old data
GetResults<-function(sample, samplename){
  folder<- paste0('/Users/jupabago/Documents/Whiteley/PROJECTS/Spatial paper Data/Microscopy Data/Other Data/',sample,'/results')#the path needs to be "Other Data"
  fileList<-list.files(path = folder, full.names = TRUE)
  growthDf<-data.frame()
  for (position in 0:5){
    currentPosition<-fileList[grep(paste0("p",position,"."),fileList)]
    for (timepoint in 0:17){
      currentTimePoint<-currentPosition[grep(paste0("t",GetNumber(timepoint),"_"),currentPosition)]
      growthDf<-rbind(growthDf,ReadResultsFile(currentTimePoint, position, timepoint))}}
  growthDf<-growthDf %>% mutate(Sample = samplename)
return(growthDf)
}
wtConfocalResults1<-MapResults(PA14wt, names3)
mutConfocalResults1<-MapResults(PA14mut, names3)
#combine them:
allConfocalResults1<-rbind(wtConfocalResults1,mutConfocalResults1)
#Get stats:
##this adds up all the data on each slice and then gets the log of that total
allConfocalResults1<-allConfocalResults1%>% group_by(TimePoint,Sample,Strain,Condition,Species) %>% summarise(Totals = sum (Value))%>% mutate(LogTotals = ifelse(Totals>0, log10(Totals), 0))

##this calculates mean and error
allConfocalResultsStats1<-allConfocalResults1%>% group_by(TimePoint,Strain,Condition,Species) %>% summarise(MeanTotals = mean(Totals), SDTotals = sd(Totals), MeanLogTotals = mean(LogTotals), SDLogTotals = sd(LogTotals)) 

##remove all the conditions I didn't do in the plate counts and fix time points:
DataComparisonScope1<-allConfocalResultsStats1 %>% filter (Strain %in% c("PA14wt","PA14mut")) %>% filter(Condition == "Pa:Sa 1:1") %>%  filter(TimePoint %in% c(0,3,7,11,15)) %>% select(Condition,TimePoint, Strain, Species, MeanTotals, MeanLogTotals) %>% mutate(time = ifelse(TimePoint>0, TimePoint+1, 0)) #The timePoint thing is because I start imaging after one hour and I don't have a time zero on scope

comparisonDf1 <- merge(DataComparisonCFU,DataComparisonScope1,by=c("Species","Strain", "time"))
comparisonDf1$time<-as.numeric(as.character(comparisonDf1$time))

ggplot()+
    geom_point(data=comparisonDf1 %>% filter(Species == "Sa"), aes(x=logCFUs, y=MeanLogTotals, color = time, shape = Strain),   size=4)+
  scale_color_gradient(low="blue", high="red")
```
