---
title: "Paper Figures and Data"
author: "Juan P Barraza"
date: "12/14/2019"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r code Figure 1ab and 2ab}
#Data gathering functions:
GetGrowthCurveReplicate<- function (sample){
  bugCounts<-read.csv(paste0("/Users/jupabago/Documents/Whiteley/PROJECTS/PaSaProject/Spatial paper Data/GrowthCurves/", sample, ".csv"),header = TRUE)
  bugCounts<- na.omit(bugCounts)
  bugCounts<-bugCounts %>% mutate(logCFU = log10(CFU))
  bugCounts$sample<-sample
  return(bugCounts)
}
GetGrowthCurveCondition<-function(datalist){
  mappedData<-map(datalist, GetGrowthCurveReplicate)#this line reads all the files on the list
  boundData<-bind_rows(mappedData)
  colnames(boundData)[5] <- "strain"
  colnames(boundData)[8] <- "condition"
  return(boundData)
}

PA14 = c('2-11-19','2-7-19','2-5-19')
#get data
PA14Data<-GetGrowthCurveCondition(PA14)
PA14Data$strain <- factor(PA14Data$strain, levels = c("wt", "mut"))

#do stats
PA14DataStats<-PA14Data%>% group_by(condition, bug, time,strain) %>% summarise(CFUmean = mean (CFU), CFUsd = sd(CFU), CFUse = std.error(CFU), logCFUmean = mean (logCFU), logCFUsd = sd(logCFU),logCFUse = std.error(logCFU))


GraphGrowthCurveLog1<-function (Strain){
  if(Strain == "wt"){etiqueta = bquote(paste(italic('P. aeruginosa')))}
  if(Strain == "mut"){etiqueta = bquote(paste(italic('P. aeruginosa '*Delta*"pqsL")))}
    shakingWtPlot<-ggplot()+
      geom_line(data=PA14DataStats%>% filter(condition == "Shaking" & strain == Strain), aes(x=time, y=logCFUmean, linetype = bug), size=.5)+
      geom_errorbar(data=PA14DataStats%>% filter(condition == "Shaking" & strain == Strain),aes(x = time, ymin = logCFUmean-logCFUse, ymax=logCFUmean+logCFUse), width = 0, size = 0.5)+
      geom_hline(yintercept=9.619, color='red', linetype = "solid") + #Pa stirred
      geom_hline(yintercept=9.13, color='red', linetype = "dashed") + #Sa stirred
      scale_linetype_manual(values = c( "solid","dashed"), labels = c(etiqueta,bquote(paste(italic('S. aureus')))))+
      labs(x = "Time (hours)", y = expression(paste(Log[10], " CFU")), linetype = "")+
      scale_y_continuous(limits = c(4,10))+
      scale_x_continuous(breaks = c(0,4,8,12,16))+
      theme_cowplot(12)+
      theme(plot.margin = unit(c(.5,0,0,.5), "cm"),
            axis.title.x = element_text(margin = margin(0,0,0,0),size=13),axis.text.x = element_text(margin = margin(1,0,2,0),size=11),
            axis.title.y = element_text(margin = margin(0,0,0,0),size=13),axis.text.y = element_text(margin = margin(0,0,2,0),size=11),
            legend.title = element_text(size=13),legend.text = element_text(size = 11))
    
    staticWtPlot<-ggplot()+
      geom_line(data=PA14DataStats%>% filter(condition == "Static" & strain == Strain), aes(x=time, y=logCFUmean, linetype = bug), size=.5)+
      geom_errorbar(data=PA14DataStats%>% filter(condition == "Static" & strain == Strain),aes(x = time,ymin=logCFUmean-logCFUse, ymax = logCFUmean+logCFUse), width = 0, size = 0.5)+
      scale_linetype_manual(values = c( "solid","dashed"), labels = c("stirred","static"))+
      geom_hline(yintercept=8.88, color='red', linetype = "dashed") +
      geom_hline(yintercept=9.07, color='red', linetype = "solid") +
      labs(x = "Time (hours)", y = expression(paste(Log[10], " CFU")), linetype = "")+
      scale_y_continuous(limits=c(4,10))+
      scale_x_continuous(breaks = c(0,4,8,12,16))+
      theme_cowplot(12)+
      theme(plot.margin = unit(c(.5,0,0,0), "cm"),
            axis.title.x = element_text(margin = margin(0,0,0,0),size=13 ),axis.text.x = element_text(margin = margin(1,0,2,0),size=11),
            axis.title.y = element_text(margin = margin(0,0,0,0),size=13),axis.text.y = element_text(margin = margin(0,0,0,0),size=11))
    
    legend <- get_legend(shakingWtPlot + theme(legend.box.margin = margin(0, 0, 0, 0)))
    prow <- plot_grid(shakingWtPlot+theme(legend.position="none"),staticWtPlot+theme(legend.position="none"),
                      align='v',labels = c("A", "B"),nrow = 1,label_size= 20, label_x = .02, label_y = 1)
    plot_grid(prow,legend,rel_widths = c(3,.6))
    }

#Graph logs
figure1AB<-GraphGrowthCurveLog1("wt")
figure2AB<-GraphGrowthCurveLog1("mut")
```
```{r Figures 1cd, and 2cd}
#data disk difussion
#####
diskFile<-"~/Documents/Whiteley/PROJECTS/PaSaProject/Staph killing assays/disk difussion assays.csv"
diskData <-read.csv(diskFile)
diskData$strain <- factor(diskData$strain, levels = c("wt", "pqsl"))
diskData <- diskData %>% mutate(val1 = value1-6,val2 = value2-6,average = (val1+val2)/2 )#this removes the diameter of the disks
diskDataStats<-diskData %>% group_by(strain, condition, bio.rep) %>% summarise(meanTech = mean(average)) %>% ungroup() %>%group_by(strain, condition) %>% summarise(meanBio = mean(meanTech), SDBio = std.error(meanTech))
diskDataStats$strain <- factor(diskDataStats$strain, levels = c("wt", "pqsl"))
diskDataStats1<-diskDataStats %>% mutate(
  CondStrain = case_when(
    condition == "shaking" & strain == "pqsl" ~ "pqsLShake",
    condition == "shaking" & strain == "wt"~ "wtShake",
    condition == "static" & strain == "pqsl"~ "pqsLStat",
    condition == "static" & strain == "wt"~ "wtStat"))
#####
#t-tests disk difussion
#####
diskWtShaking<-diskData %>% filter(strain == "wt" & condition == "shaking")
diskMutShaking<-diskData %>% filter(strain == "pqsl" & condition == "shaking")
diskWtStatic<-diskData %>% filter(strain == "wt" & condition == "static")
diskMutStatic<-diskData %>% filter(strain == "pqsl" & condition == "static")

#there is no rep 1 for mutant strain, so remove first one from wt to make paired t-test
diskWtStatic1<-diskData %>% filter(strain == "wt" & condition == "static") %>% filter(!bio.rep==1)
diskWtShaking1<-diskData %>% filter(strain == "wt" & condition == "shaking")%>% filter(!bio.rep==1)

#t-tests
diskWtTtest<-t.test(x = diskWtShaking$avg, y = diskWtStatic$avg, paired = T)
diskMutTtest<-t.test(x = diskMutShaking$avg, y = diskMutStatic$avg, paired = T)
diskShakingTtest<-t.test(x = diskWtShaking1$avg, y = diskMutShaking$avg, paired = T)
diskStaticTtest<-t.test(x = diskMutStatic$avg, y = diskWtStatic1$avg, paired = T)
diskWtStaticMutShakingTtest<-t.test(x = diskMutShaking$avg, y = diskWtStatic1$avg, paired = T)
diskMutStaticWtShakingTtest<-t.test(x = diskWtShaking1$avg, y = diskMutStatic$avg, paired = T)
tTestDataDiskDifussion<-list(diskWtTtest, diskMutTtest,diskShakingTtest, diskStaticTtest, diskWtStaticMutShakingTtest,diskMutStaticWtShakingTtest)
tTestDiskDifussionTable<-bind_rows(map(tTestDataDiskDifussion, TtestTable))
#####

#luminesscence data
#####
luminescenceFile<-"/Users/jupabago/Documents/Whiteley/PROJECTS/PaSaProject/Staph killing assays/summary.csv" 
luminescenceData <-read.csv(luminescenceFile) 
luminescenceData<-luminescenceData %>% group_by(TimePoint, Condition, Strain) %>% mutate(Mean = mean(Luminescence), SE =std.error(Luminescence)) %>% ungroup()
write.csv(luminescenceData1, "/Users/jupabago/Documents/Whiteley/PROJECTS/PaSaProject/Staph killing assays/summary2.csv")
luminescenceData1<-luminescenceData %>% mutate(
  CondStrain = case_when(
    Condition == "shaking" & Strain == "pqsL" ~ "pqsLShake",
    Condition == "shaking" & Strain == "wt"~ "wtShake",
    Condition == "static" & Strain == "pqsL"~ "pqsLStat",
    Condition == "static" & Strain == "wt"~ "wtStat"))
luminescenceData1<-luminescenceData1 %>%  mutate(LogTotals = ifelse(Luminescence>0, log10(Luminescence), 0), rep = (4*(TechReplicate-1))+BioReplicate)#this adds up all the data on each slice and then gets the log of that total
#####


#luminescence t-tests
#####
wtStatLuminescence<-luminescenceData1 %>% filter (CondStrain == "wtStat") %>% filter (TimePoint==10 &TechReplicate == 1)  %>% pull(LogTotals) 
wtMixedLuminescence<-luminescenceData1 %>% filter (CondStrain == "wtShake") %>% filter (TimePoint==10 &TechReplicate == 1) %>% pull(LogTotals)

mutStatLuminescence<-luminescenceData1 %>% filter (CondStrain == "pqsLStat") %>% filter (TimePoint==10 &TechReplicate == 1)%>% pull(LogTotals)
mutMixedLuminescence<-luminescenceData1 %>% filter (CondStrain == "pqsLShake") %>% filter (TimePoint==10 &TechReplicate == 1)%>% pull(LogTotals)

tTestWtLuminescence<-t.test(x = wtStatLuminescence, y = wtMixedLuminescence, paired = T)
tTestMutLuminescence<-t.test(x = mutStatLuminescence, y = mutMixedLuminescence, paired = T)

tTestStatLuminescence<-t.test(x = wtStatLuminescence, y = mutStatLuminescence, paired = T)
tTestMixedLuminescence<-t.test(x = wtMixedLuminescence, y = mutMixedLuminescence, paired = T)

tTestWtStatVSMutMixedLuminescence<-t.test(x = wtStatLuminescence, y = mutMixedLuminescence, paired = T)
tTestMutStatVSWtMixedLuminescence<-t.test(x = wtMixedLuminescence, y = mutStatLuminescence, paired = T)

tTestDataLuminescence<-list(tTestWtLuminescence,tTestMutLuminescence,tTestStatLuminescence,tTestMixedLuminescence,
                            tTestWtStatVSMutMixedLuminescence,tTestMutStatVSWtMixedLuminescence)
TtestTable<-name <- function(dataPoint) {
  data <-data.frame(dataPoint$data.name, dataPoint$p.value)
}
tTestLuminescenceTable<-bind_rows(map(tTestDataLuminescence, TtestTable))
#this is only comparing the last time point of the log transformed data

timePoints<-seq(1,10)

DoLm<-function(condstrain, bio){
  rep1Data<-luminescenceData1 %>% filter (CondStrain == condstrain, rep == bio) %>% filter(TimePoint > 1) %>% filter(TimePoint<8)
  #rep1Data<-luminescenceData1 %>% filter (CondStrain == condstrain, rep == bio) %>% filter(TimePoint<7) 
  timePoints<-unique(rep1Data$TimePoint)
  rep1lm<- lm(rep1Data$LogTotals ~ timePoints)
  return(as.numeric(rep1lm$coefficients[[2]]))}

wtStatLuminescenceSlope<- unlist(map2("wtStat", seq(1,8), DoLm))
wtMixedLuminescenceSlope<- unlist(map2("wtShake", seq(1,8), DoLm))
mutStatLuminescenceSlope<- unlist(map2("pqsLStat", seq(1,8), DoLm))
mutMixedLuminescenceSlope<- unlist(map2("pqsLShake", seq(1,8), DoLm))
#Anova
blah<-combine(wtStatLuminescenceSlope,wtMixedLuminescenceSlope,mutStatLuminescenceSlope,mutMixedLuminescenceSlope)
res.aov <- aov(data ~ source, data = blah)
# Summary of the analysis
summary(res.aov)
TukeyHSD(res.aov)

#t-tests
tTestWtLuminescenceSlope<-t.test(x = wtStatLuminescenceSlope, y = wtMixedLuminescenceSlope, paired = T)
tTestMutLuminescenceSlope<-t.test(x = mutStatLuminescenceSlope, y = mutMixedLuminescenceSlope, paired = T)

tTestStatLuminescenceSlope<-t.test(x = wtStatLuminescenceSlope, y = mutStatLuminescenceSlope, paired = T)
tTestMixedLuminescenceSlope<-t.test(x = wtMixedLuminescenceSlope, y = mutMixedLuminescenceSlope, paired = T)

tTestWtStatVSMutMixedLuminescenceSlope<-t.test(x = wtStatLuminescenceSlope, y = mutMixedLuminescenceSlope, paired = T)
tTestMutStatVSWtMixedLuminescenceSlope<-t.test(x = wtMixedLuminescenceSlope, y = mutStatLuminescenceSlope, paired = T)

tTestDataLuminescenceSlope<-list(tTestWtLuminescenceSlope,tTestMutLuminescenceSlope,tTestStatLuminescenceSlope,tTestMixedLuminescenceSlope,
                            tTestWtStatVSMutMixedLuminescenceSlope,tTestMutStatVSWtMixedLuminescenceSlope)

tTestLuminescenceTableLast<-bind_rows(map(tTestDataLuminescenceSlope, TtestTable))

tTestLuminescenceTableLast
#####

#plot disk difussion and luminescence 
#####
GraphStaphKilling<-function(Strain1,Strain2){ 
figure1C<-ggplot()+
      geom_errorbar(data=diskDataStats1 %>% filter (strain == Strain1), aes(x = condition, ymin = meanBio - SDBio, ymax = meanBio + SDBio),width = 0)+
      geom_point(data=diskDataStats1 %>% filter (strain == Strain1), aes(x=condition, y=meanBio), size=3)+
      #scale_shape_manual(values = c(1,2),limits=c("shaking","static"), labels = c(bquote(paste(italic('P. aeruginosa'), " mixed")),bquote(paste(italic('P. aeruginosa'), " static"))))+
  #scale_shape_manual(values = c(16,17),limits=c("static", "shaking"), 
      #               labels = c(bquote(paste(italic('P. aeruginosa '), Delta*"pqsL static")),
      #                          bquote(paste(italic('P. aeruginosa '), Delta*"pqsL mixed"))))+
      scale_x_discrete(name =expression(paste(italic('P. aeruginosa'), 'culture')), breaks = c("static","shaking"), labels =c("Static","Mixed"))+
    ylim(0,15.1)+
  labs( y = "Zone of inhibition (mm)", shape = "") +
      theme_cowplot(12)+
  
  theme(plot.margin = unit(c(.5,.5,0,.5), "cm"),
        axis.text.x  = element_text(margin = margin(0,0,0,0),size=13),
        axis.title.y = element_text(margin = margin(0,0,0,0),size=13),
        axis.text.y = element_text(margin = margin(0,0,2,0),size=11),
        legend.title = element_text(size=13),legend.text = element_text(size = 11))
        #legend.position = c(0.79, 0.60))

figure1D<-ggplot()+
      geom_line(data=luminescenceData1 %>% filter (Strain == Strain2) %>% filter (TimePoint<7), aes(x=TimePoint, y=Mean, group = Condition), size=.5, show.legend = FALSE)+
      geom_point(data=luminescenceData1%>% filter (Strain == Strain2) %>% filter (TimePoint<7), aes(x=TimePoint, y=Mean, shape = Condition), size=3)+
      geom_errorbar(data=luminescenceData1%>% filter (Strain == Strain2) %>% filter (TimePoint<7), aes(x=TimePoint, ymin=Mean-SE,ymax=Mean+SE), width = 0)+
      scale_y_log10(name=expression(paste(italic('S. aureus'), " luminescence (%)" )), limits = c(.1,121),labels = c(0.1,1, 10, 100),breaks = c(0.1,1, 10, 100))+
      labs( x = "Time (minutes)",shape = "") +
      scale_shape_manual(values = c(1,2),limits=c("shaking","static"))+
      theme_cowplot(12)+
      theme(legend.position="top",plot.margin = unit(c(0,0,0,0), "cm"),
            axis.title.x = element_text(margin = margin(0,0,0,0),size=13),axis.text.x = element_text(margin = margin(1,0,0,0),size=11),
            axis.title.y = element_text(margin = margin(0,0,0,0),size=13),axis.text.y = element_text(margin = margin(0,0,2,0),size=11))

legendFigure1C <- get_legend(figure1C + theme(legend.box.margin = margin(0, 0, 0, 0)))
#plotsFigure1cd <- plot_grid(figure1C+theme(legend.position="none"),figure1D+theme(legend.position="none"), align='vh',labels = c("C", "D"),hjust = -1,nrow = 1,label_size= 20)
##plotsFigure1c <- plot_grid(figure1C+theme(legend.position="none"),legendFigure1C, align='vh',labels = c("C"),rel_widths = c(1,.7),hjust = -1,nrow = 1,label_size= 20,label_x = 0, label_y = 1)
plotsFigure1c <- plot_grid(figure1C+theme(legend.position="none"),align='vh',labels = c("C"),hjust = -1,nrow = 1,label_size= 20,
                           label_x = 0, label_y = 1)
#plot_grid(plotsFigure1cd,legendFigure1C,rel_widths = c(1,.1))
}   
figure1CD<-GraphStaphKilling("wt","wt")
figure2CD<-GraphStaphKilling("pqsl", "pqsL")
#####
```

```{r code Figures 1ef and 2ef}
#get data biomass aggs vs planktonic
#####
allDataHistograms.5df<-read.csv(file='/Users/jupabago/Documents/Whiteley/PROJECTS/PaSaProject/Spatial paper Data/Microscopy Data/Histograms1/histograms5.csv',header=T)
allDataHistograms.100df<-read.csv(file='/Users/jupabago/Documents/Whiteley/PROJECTS/PaSaProject/Spatial paper Data/Microscopy Data/Histograms1/histograms100.csv',header=T)
hist.100<-allDataHistograms.100df %>% filter(TimePoint== 5) %>% filter( Condition %in% c("Sa Mono", "Pa Mono", "Pa:Sa 1:1")) %>% mutate(ConditionNew = recode(Condition, "Sa Mono" = "Mono", "Pa Mono" = "Mono", "Pa:Sa 1:1" = "Co"))
hist.5 <- allDataHistograms.5df %>% filter(TimePoint== 5) %>% filter( Condition %in% c("Sa Mono", "Pa Mono", "Pa:Sa 1:1")) %>% mutate(ConditionNew = recode(Condition, "Sa Mono" = "Mono", "Pa Mono" = "Mono", "Pa:Sa 1:1" = "Co"))

hist.plank.Agg.Sumary<-hist.5 %>%  group_by(Species, Sample,Condition,Strain)%>% 
  mutate(Aggregation = case_when(max == 5 ~ "Planktonic",
                        max>5 ~ "Aggregate")) %>% ungroup() %>% group_by(Species,Sample,Condition,ConditionNew, Strain,Aggregation) %>% summarize(FrequencyAggregation = sum(frequency), BiomassAggregation = sum(BiomassBin), DensityAggregation = sum(Density))

hist.plank.Agg.Stats<-hist.plank.Agg.Sumary %>% group_by(Species,Condition, ConditionNew,Strain,Aggregation) %>% 
  summarise(MeanFreq = mean(FrequencyAggregation), SEFreq = std.error(FrequencyAggregation), MeanBiomass = mean(BiomassAggregation), SEBiomass = std.error(BiomassAggregation),MeanDensity = mean(DensityAggregation), SEDensity = std.error(DensityAggregation) )
hist.plank.Agg.Stats$Species <- factor(hist.plank.Agg.Stats$Species, levels = c("Pa", "Sa"),
                  labels = c('P. aeruginosa','S. aureus'))
hist.plank.Agg.Stats$ConditionNew <- factor(hist.plank.Agg.Stats$ConditionNew, levels = c("Mono", "Co"))

#####
#t tests biomass aggs vs planktonic
##### 
#I know this sucks, but it's 1 AM so idgaf
SaMonoWtAggSum<-hist.plank.Agg.Sumary %>%filter(Condition == "Sa Mono", Strain == "PA14wt",Aggregation == "Aggregate") %>% pull(BiomassAggregation)
SaMonoWtPlankSum<-hist.plank.Agg.Sumary %>%filter(Condition == "Sa Mono", Strain == "PA14wt",Aggregation == "Planktonic") %>% pull(BiomassAggregation)
SaMonoMutAggSum<-hist.plank.Agg.Sumary %>%filter(Condition == "Sa Mono", Strain == "PA14mut",Aggregation == "Aggregate") %>% pull(BiomassAggregation)
SaMonoMutPlankSum<-hist.plank.Agg.Sumary %>%filter(Condition == "Sa Mono", Strain == "PA14mut",Aggregation == "Planktonic") %>% pull(BiomassAggregation)

SaCoWtAggSum<-hist.plank.Agg.Sumary %>%filter(Species =="Sa", ConditionNew == "Co", Strain == "PA14wt",Aggregation == "Aggregate") %>% pull(BiomassAggregation)
SaCoWtPlankSum<-hist.plank.Agg.Sumary %>%filter(Species =="Sa", ConditionNew == "Co", Strain == "PA14wt",Aggregation == "Planktonic") %>% pull(BiomassAggregation)
SaCoMutAggSum<-hist.plank.Agg.Sumary %>%filter(Species == "Sa", ConditionNew == "Co", Strain == "PA14mut",Aggregation == "Aggregate") %>% pull(BiomassAggregation)
SaCoMutPlankSum<-hist.plank.Agg.Sumary %>%filter(Species == "Sa", ConditionNew == "Co", Strain == "PA14mut",Aggregation == "Planktonic") %>% pull(BiomassAggregation)

#mono vs Co
SaWtAggTest<-t.test(x = SaMonoWtAggSum, y = SaCoWtAggSum, paired = T)#wt
SaMutAggTest<-t.test(x = SaMonoMutAggSum, y = SaCoMutAggSum, paired = T)#mutant
#Plank vs Agg
SaMonoWtAggVsPlankTest<-t.test(x = SaMonoWtAggSum, y = SaMonoWtPlankSum, paired = T)#wt
SaMonoMutAggVsPlankTest<-t.test(x = SaMonoMutAggSum, y = SaMonoMutPlankSum, paired = F)#mutant
SaCoWtAggVsPlankTest<-t.test(x = SaCoWtAggSum, y = SaCoWtPlankSum, paired = T)#wt
SaCoMutAggVsPlankTest<-t.test(x = SaCoMutAggSum, y = SaCoMutPlankSum, paired = T)#mutant
#wt vs mutant
SaMonoWtVsMutAggTest<-t.test(x = SaMonoWtAggSum, y = SaMonoMutAggSum, paired = F)
SaCoWtVsMutAggTest<-t.test(x = SaCoWtAggSum, y = SaCoMutAggSum, paired = F)


PaMonoWtAggSum<-hist.plank.Agg.Sumary %>%filter(Condition == "Pa Mono", Strain == "PA14wt",Aggregation == "Aggregate") %>% pull(BiomassAggregation)
PaCoWtAggSum<-hist.plank.Agg.Sumary %>%filter(Species == "Pa", ConditionNew == "Co", Strain == "PA14wt",Aggregation == "Aggregate") %>% pull(BiomassAggregation)
PaMonoMutAggSum<-hist.plank.Agg.Sumary %>%filter(Condition == "Pa Mono", Strain == "PA14mut",Aggregation == "Aggregate") %>% pull(BiomassAggregation)
PaCoMutAggSum<-hist.plank.Agg.Sumary %>%filter(Species == "Pa", ConditionNew == "Co", Strain == "PA14mut",Aggregation == "Aggregate") %>% pull(BiomassAggregation)

PaMonoWtPlankSum<-hist.plank.Agg.Sumary %>%filter(Condition == "Pa Mono", Strain == "PA14wt",Aggregation == "Planktonic") %>% pull(BiomassAggregation)
PaCoWtPlankSum<-hist.plank.Agg.Sumary %>%filter(Species == "Pa", ConditionNew == "Co", Strain == "PA14wt",Aggregation == "Planktonic") %>% pull(BiomassAggregation)
PaMonoMutPlankSum<-hist.plank.Agg.Sumary %>%filter(Condition == "Pa Mono", Strain == "PA14mut",Aggregation == "Planktonic") %>% pull(BiomassAggregation)
PaCoMutPlankSum<-hist.plank.Agg.Sumary %>%filter(Species == "Pa", ConditionNew == "Co", Strain == "PA14mut",Aggregation == "Planktonic") %>% pull(BiomassAggregation)

PaWtAggTest<-t.test(x = PaMonoWtAggSum, y = PaCoWtAggSum, paired = T)
PaMutAggTest<-t.test(x = PaMonoMutAggSum, y = PaCoMutAggSum, paired = T)
PaMonoWtVsMutAggTest<-t.test(x = PaMonoWtAggSum, y = PaMonoMutAggSum, paired = F)
PaCoWtVsMutAggTest<-t.test(x = PaCoWtAggSum, y = PaCoMutAggSum, paired = F)

PaMonoWtAggVsPlankTest<-t.test(x = PaMonoWtAggSum, y = PaMonoWtPlankSum, paired = T)
PaCoWtAggVsPlankTest<-t.test(x = PaCoWtAggSum, y = PaCoWtPlankSum, paired = T)
PaMonoMutAggVsPlankTest<-t.test(x = PaMonoMutAggSum, y = PaMonoMutPlankSum, paired = T)
PaCoMutAggVsPlankTest<-t.test(x = PaCoMutAggSum, y = PaCoMutPlankSum, paired = T)



tTestDataAggvsPlank<-list(SaWtAggTest,SaMutAggTest,SaMonoWtAggVsPlankTest,SaMonoMutAggVsPlankTest,
                          SaCoWtAggVsPlankTest,SaCoMutAggVsPlankTest,SaMonoWtVsMutAggTest,SaCoWtVsMutAggTest,
                          PaWtAggTest,PaMutAggTest,PaMonoWtAggVsPlankTest,PaMonoMutAggVsPlankTest,
                          PaCoWtAggVsPlankTest,PaCoMutAggVsPlankTest,PaMonoWtVsMutAggTest,PaCoWtVsMutAggTest)
TtestTable<-name <- function(dataPoint) {
  data <-data.frame(dataPoint$data.name, dataPoint$p.value)
}
tTestDataTable<-bind_rows(map(tTestDataAggvsPlank, TtestTable))
#so, it turns out I only had to do either agg or plank since the variance is the same. COOL...

#####
#plot biomass aggs vs planktonic
#####
PlotAggsPlank<- function(strain, titulo){
ggplot()+
  geom_col(data = hist.plank.Agg.Stats %>% filter(Strain == strain),aes(x=Aggregation,y=MeanBiomass*100, fill = ConditionNew),
           size=3,position = position_dodge( width = .9),show.legend = FALSE)+
  geom_errorbar(data = hist.plank.Agg.Stats%>% filter(Strain == strain),aes(x=Aggregation,ymin=(MeanBiomass-SEBiomass)*100, ymax = (MeanBiomass+SEBiomass)*100, group = ConditionNew),width = 0, size=.5,position = position_dodge(width = .9))+
  scale_y_continuous(expand = expand_scale(mult = c(0, 0.2)))+
  facet_grid(.~Species)+
  scale_fill_grey()+
  labs(title = '', x = "", y = "Biomass contribution (%)")+
  theme_cowplot()+
  theme(plot.title = element_text(hjust = 0.5),strip.text = element_text(size = 9, face = "italic",margin = margin(.1,0,.1,0, "cm")),
        strip.background = element_rect(color="black", fill="white", size=.5, linetype="solid"),
        axis.title.x = element_text(margin = margin(0,0,0,0),size=13),axis.text.x = element_text(margin = margin(1,0,0,0),size=13),
        axis.title.y = element_text(margin = margin(0,4,0,0),size=13),axis.text.y = element_text(margin = margin(0,0,2,0),size=11))
}
figure1E<-PlotAggsPlank("PA14wt", "wt")
figure2E<-PlotAggsPlank("PA14mut", "pqsL")
#####

#get data frequency bins THIS WAS substituted by counts percentage
#####
hist.5.LogBinData<-hist.5 %>% filter(!max == 5)%>%  group_by(Sample,Species,Condition,Strain)%>% 
  mutate(LogBin = case_when(max <= 10 ~ "(5, 10]",
                        max<= 100    ~ "(10, 100]",
                        max > 100 ~ paste0("(100, ",bquote("\U221E"), ")"))) %>% ungroup() %>% 
  group_by(Species, Sample,Condition,ConditionNew,Strain,LogBin) %>% summarise(FrequencyLogBin = sum(frequency), BiomassLogBin = sum(BiomassBin), DensityLogBin = sum(Density)) %>% ungroup() 



hist.5.LogBinSummarize<-hist.5.LogBinData%>% group_by(Species, Condition,ConditionNew,Strain,LogBin) %>%
  summarise(MeanFrequencyLogBin = mean(FrequencyLogBin),SEFrequencyLogBin = std.error(FrequencyLogBin),
            MeanBiomassLogBin = mean(BiomassLogBin), SEBiomassLogBin = std.error(BiomassLogBin),                                                              
            MeanDensityLogBin = mean(DensityLogBin),SEDensityLogBin = std.error(DensityLogBin)) 

hist.5.LogBinSummarize$LogBin<-as.factor(hist.5.LogBinSummarize$LogBin)
new.rowWt <- data.frame(Species = 'Sa', Condition = "Pa:Sa 1:1",ConditionNew = "Co",Strain = "PA14wt", LogBin =paste0("(100, ",bquote("\U221E"), ")"), MeanFrequencyLogBin = 0,SEFrequencyLogBin = 0)
new.rowMut <- data.frame(Species = 'Sa', Condition = "Pa:Sa 1:1",ConditionNew = "Co",Strain = "PA14mut", LogBin =paste0("(100, ",bquote("\U221E"), ")"), MeanFrequencyLogBin = 0,SEFrequencyLogBin = 0)
hist.5.LogBinSummarize<-rbind(hist.5.LogBinSummarize, new.rowWt)
hist.5.LogBinSummarize<-rbind(hist.5.LogBinSummarize, new.rowMut)

hist.5.LogBinSummarize$LogBin <- factor(hist.5.LogBinSummarize$LogBin, levels = c("(5, 10]","(10, 100]",paste0("(100, ",bquote("\U221E"), ")")))
hist.5.LogBinSummarize$Species <- factor(hist.5.LogBinSummarize$Species, levels = c("Pa", "Sa"),
                  labels = c('P. aeruginosa','S. aureus'))
hist.5.LogBinSummarize$ConditionNew <- factor(hist.5.LogBinSummarize$ConditionNew, levels = c("Mono", "Co"))
#####

#t tests frequency bins
#####
SaWtMono5<-hist.5.LogBinData %>%filter(Condition == "Sa Mono", Strain == "PA14wt",LogBin == "(5, 10]") %>% pull(FrequencyLogBin)
SaMutMono5<-hist.5.LogBinData %>%filter(Condition == "Sa Mono", Strain == "PA14mut",LogBin == "(5, 10]") %>% pull(FrequencyLogBin)
SaWtMono10<-hist.5.LogBinData %>%filter(Condition == "Sa Mono", Strain == "PA14wt",LogBin == "(10, 100]") %>% pull(FrequencyLogBin)
SaMutMono10<-hist.5.LogBinData %>%filter(Condition == "Sa Mono", Strain == "PA14mut",LogBin == "(10, 100]") %>% pull(FrequencyLogBin)

SaWtCo5<-hist.5.LogBinData %>%filter(Species =="Sa", ConditionNew == "Co", Strain == "PA14wt",LogBin == "(5, 10]") %>% pull(FrequencyLogBin)
SaMutCo5<-hist.5.LogBinData %>%filter(Species =="Sa", ConditionNew == "Co", Strain == "PA14mut",LogBin == "(5, 10]") %>% pull(FrequencyLogBin)
SaWtCo10<-hist.5.LogBinData %>%filter(Species =="Sa", ConditionNew == "Co", Strain == "PA14wt",LogBin == "(10, 100]") %>% pull(FrequencyLogBin)
SaMutCo10<-hist.5.LogBinData %>%filter(Species =="Sa", ConditionNew == "Co", Strain == "PA14mut",LogBin == "(10, 100]") %>% pull(FrequencyLogBin)
SaWtCo100<-hist.5.LogBinData %>%filter(Species =="Sa", ConditionNew == "Co", Strain=="PA14wt",LogBin == paste0("(100, ",bquote("\U221E"), ")")) %>% pull(FrequencyLogBin)
SaMutCo100<-hist.5.LogBinData %>%filter(Species =="Sa", ConditionNew == "Co", Strain=="PA14mut",LogBin == paste0("(100, ",bquote("\U221E"), ")")) %>% pull(FrequencyLogBin)

PaWtMono5<-hist.5.LogBinData %>%filter(Condition == "Pa Mono", Strain == "PA14wt",LogBin == "(5, 10]") %>% pull(FrequencyLogBin)
PaMutMono5<-hist.5.LogBinData %>%filter(Condition == "Pa Mono", Strain == "PA14mut",LogBin == "(5, 10]") %>% pull(FrequencyLogBin)
PaWtMono10<-hist.5.LogBinData %>%filter(Condition == "Pa Mono", Strain == "PA14wt",LogBin == "(10, 100]") %>% pull(FrequencyLogBin)
PaMutMono10<-hist.5.LogBinData %>%filter(Condition == "Pa Mono", Strain == "PA14mut",LogBin == "(10, 100]") %>% pull(FrequencyLogBin)
PaWtMono100<-hist.5.LogBinData %>%filter(Condition == "Pa Mono", Strain == "PA14wt",LogBin == paste0("(100, ",bquote("\U221E"), ")")) %>% pull(FrequencyLogBin)
PaMutMono100<-hist.5.LogBinData %>%filter(Condition == "Pa Mono", Strain == "PA14mut",LogBin == paste0("(100, ",bquote("\U221E"), ")")) %>% pull(FrequencyLogBin)

PaWtCo5<-hist.5.LogBinData %>%filter(Species =="Pa", ConditionNew == "Co", Strain == "PA14wt",LogBin == "(5, 10]") %>% pull(FrequencyLogBin)
PaMutCo5<-hist.5.LogBinData %>%filter(Species =="Pa", ConditionNew == "Co", Strain == "PA14mut",LogBin == "(5, 10]") %>% pull(FrequencyLogBin)
PaWtCo10<-hist.5.LogBinData %>%filter(Species =="Pa", ConditionNew == "Co", Strain == "PA14wt",LogBin == "(10, 100]") %>% pull(FrequencyLogBin)
PaMutCo10<-hist.5.LogBinData %>%filter(Species =="Pa", ConditionNew == "Co", Strain == "PA14mut",LogBin == "(10, 100]") %>% pull(FrequencyLogBin)
PaWtCo100<-hist.5.LogBinData %>%filter(Species =="Pa",ConditionNew=="Co",Strain == "PA14wt",LogBin == paste0("(100, ",bquote("\U221E"), ")")) %>% pull(FrequencyLogBin)
PaMutCo100<-hist.5.LogBinData %>%filter(Species =="Pa",ConditionNew=="Co",Strain == "PA14mut",LogBin==paste0("(100, ",bquote("\U221E"), ")")) %>% pull(FrequencyLogBin)

#mono vs Co
SaWt5<-t.test(x = SaWtMono5, y = SaWtCo5, paired = T)
SaWt10<-t.test(x = SaWtMono10, y = SaWtCo10, paired = T)
SaMut5<-t.test(x = SaMutMono5, y = SaMutCo5, paired = T)
SaMut10<-t.test(x = SaMutMono10, y = SaMutCo10, paired = T)

PaWt5<-t.test(x = PaWtMono5, y = PaWtCo5, paired = T)
PaWt10<-t.test(x = PaWtMono10, y = PaWtCo10, paired = T)
#PaWt100<-t.test(x = PaWtMono100, y = PaWtCo100, paired = T)
PaMut5<-t.test(x = PaMutMono5, y = PaMutCo5, paired = T)
PaMut10<-t.test(x = PaMutMono10, y = PaMutCo10, paired = T)
#PaMut100<-t.test(x = PaMutMono100, y = PaMutCo100, paired = T)

#Wt vs pqsL
SaWtMut5<-t.test(x = SaMutCo5, y = SaWtCo5, paired = F)
SaWtMut10<-t.test(x = SaMutCo10, y = SaWtCo10, paired = F)
#SaWtMut100<-t.test(x = SaMutCo100, y = SaWtCo100, paired = F)

PaMonoWtMut5<-t.test(x = PaMutMono5, y = PaWtMono5, paired = F)
PaMonoWtMut10<-t.test(x = PaMutMono10, y = PaWtMono10, paired = F)
PaMonoWtMut100<-t.test(x = PaMutMono100, y = PaWtMono100, paired = F)

PaCoWtMut5<-t.test(x = PaMutCo5, y = PaWtCo5, paired = F)
PaCoWtMut10<-t.test(x = PaMutCo10, y = PaWtCo10, paired = F)
PaCoWtMut100<-t.test(x = PaMutCo100, y = PaWtCo100, paired = F)
#t-tests table
tTestDatAggSizes<-list(SaWt5,SaWt10,SaMut5,SaMut10,PaWt5,PaWt10,PaMut5,PaMut10,SaWtMut5,SaWtMut10,
                       PaMonoWtMut5,PaMonoWtMut10,PaMonoWtMut100,PaCoWtMut5,PaCoWtMut10,PaCoWtMut100)
tTestAggSizesTable<-bind_rows(map(tTestDatAggSizes, TtestTable))

#####

#plot frequency bins
#####
PlotFreqLogBin<-function(strain, itulo){
  df <-hist.5.LogBinSummarize%>% filter(Strain == strain)
  ggplot()+
    geom_col(data = df, aes(x=LogBin,y=MeanFrequencyLogBin,  fill =ConditionNew ),size=4,position = position_dodge( width = .9))+
    geom_errorbar(data = df,aes(x=LogBin,ymin=MeanFrequencyLogBin-SEFrequencyLogBin, ymax = MeanFrequencyLogBin+SEFrequencyLogBin, group =ConditionNew ),width = 0, size= .5,position = position_dodge( width = .9))+
    facet_grid(.~Species)+
    labs(fill = "",y = "Aggregates per bin",x = bquote(paste("Aggregate Volume (", mu*"m"^3*")")))+
    guides(color = FALSE)+
    scale_y_continuous(expand = expand_scale(mult = c(0, 0.2)))+
    scale_fill_grey(labels = c("Mono-culture", "Co-culture"))+
    theme_half_open()+
    theme(plot.title = element_text(hjust = 0.5),
          strip.text = element_text(size = 9, face = "italic",margin = margin(.1,0,.1,0, "cm")),#this is for the facets
          strip.background = element_rect(color="black", fill="white", size=.5, linetype="solid"),
          plot.margin = unit(c(0,.5,0,.5), "cm"),
          axis.title.x = element_text(margin = margin(0,0,0,0),size=13),axis.text.x = element_text(margin = margin(1,0,0,0),size=11),
          axis.title.y = element_text(margin = margin(0,4,0,0),size=13),axis.text.y = element_text(margin = margin(0,2,2,0),size=11),
          legend.title = element_text(size=13),legend.text = element_text(size = 11),
          legend.position = c(0.79, 0.60))
}
figure1F<-PlotFreqLogBin("PA14wt", "WT")
figure2F<-PlotFreqLogBin("PA14mut", "pqsL")
#####

#get data frequency bins proportion
#####
tESThist.5.LogBinData<-hist.5 %>% filter(!max == 5)%>%  group_by(Sample,Species,Condition,Strain)%>% 
  mutate(LogBin = case_when(max <= 10 ~ "(5, 10]",
                            max<= 100    ~ "(10, 100]",
                            max > 100 ~ paste0("(100, ",bquote("\U221E"), ")")), AggOnlyBiomass = sum(suma), AggOnlyAggregates = sum(frequency)) %>% ungroup() 

test1<-tESThist.5.LogBinData%>% 
  group_by(Species, Sample,Condition,ConditionNew,Strain,LogBin) %>% 
  summarize(FrequencyLogBin = sum(frequency),DensityLogBin = (FrequencyLogBin)/AggOnlyAggregates) %>%  ungroup() %>%
  group_by(Species, Condition,ConditionNew,Strain,LogBin) %>%
mutate(MeanFrequencyLogBin = mean(FrequencyLogBin),SEFrequencyLogBin = std.error(FrequencyLogBin),
          MeanDensityLogBin = mean(DensityLogBin), SEDensityLogBin = std.error(DensityLogBin))
          
test1check<-test1 %>% filter(Species == "Sa", ConditionNew == "Mono", Strain == "PA14wt")
test1check1<-distinct(test1check) %>% group_by(Sample) %>% mutate(suma = sum(DensityLogBin))

test1Unique<-distinct(test1)
#rows below add 
new.rowWt.frequency <- data.frame(Species = 'Sa', Condition = "Pa:Sa 1:1",ConditionNew = "Co",Strain = "PA14wt", LogBin =paste0("(100, ",bquote("\U221E"), ")"), MeanDensityLogBin = 0,SEDensityLogBin = 0)
new.rowMut.frequency <- data.frame(Species = 'Sa', Condition = "Pa:Sa 1:1",ConditionNew = "Co",Strain = "PA14mut", LogBin =paste0("(100, ",bquote("\U221E"), ")"), MeanDensityLogBin = 0,SEDensityLogBin = 0)
test1Unique<-rbind(test1Unique, new.rowWt.frequency)
test1Unique<-rbind(test1Unique, new.rowMut.frequency)

test1Unique$LogBin <- factor(test1Unique$LogBin, levels = c("(5, 10]","(10, 100]",paste0("(100, ",bquote("\U221E"), ")")))

#####

#t-tests for frequency bins proportion
#####
SaWtMono5.proportion<-test1Unique %>%filter(Condition == "Sa Mono", Strain == "PA14wt",LogBin == "(5, 10]") %>% pull(DensityLogBin)
SaMutMono5.proportion<-test1Unique %>%filter(Condition == "Sa Mono", Strain == "PA14mut",LogBin == "(5, 10]") %>% pull(DensityLogBin)
SaWtMono10.proportion<-test1Unique %>%filter(Condition == "Sa Mono", Strain == "PA14wt",LogBin == "(10, 100]") %>% pull(DensityLogBin)
SaMutMono10.proportion<-test1Unique %>%filter(Condition == "Sa Mono", Strain == "PA14mut",LogBin == "(10, 100]") %>% pull(DensityLogBin)

SaWtCo5.proportion<-test1Unique %>%filter(Species =="Sa", ConditionNew == "Co", Strain == "PA14wt",LogBin == "(5, 10]") %>% pull(DensityLogBin)
SaMutCo5.proportion<-test1Unique %>%filter(Species =="Sa", ConditionNew == "Co", Strain == "PA14mut",LogBin == "(5, 10]") %>% pull(DensityLogBin)
SaWtCo10.proportion<-test1Unique %>%filter(Species =="Sa", ConditionNew == "Co", Strain == "PA14wt",LogBin == "(10, 100]") %>% pull(DensityLogBin)
SaMutCo10.proportion<-test1Unique %>%filter(Species =="Sa", ConditionNew == "Co", Strain == "PA14mut",LogBin == "(10, 100]") %>% pull(DensityLogBin)
SaWtCo100.proportion<-test1Unique %>%filter(Species =="Sa", ConditionNew == "Co", Strain=="PA14wt",LogBin == paste0("(100, ",bquote("\U221E"), ")")) %>% pull(DensityLogBin)
SaMutCo100.proportion<-test1Unique %>%filter(Species =="Sa", ConditionNew == "Co", Strain=="PA14mut",LogBin == paste0("(100, ",bquote("\U221E"), ")")) %>% pull(DensityLogBin)

PaWtMono5.proportion<-test1Unique %>%filter(Condition == "Pa Mono", Strain == "PA14wt",LogBin == "(5, 10]") %>% pull(DensityLogBin)
PaMutMono5.proportion<-test1Unique %>%filter(Condition == "Pa Mono", Strain == "PA14mut",LogBin == "(5, 10]") %>% pull(DensityLogBin)
PaWtMono10.proportion<-test1Unique %>%filter(Condition == "Pa Mono", Strain == "PA14wt",LogBin == "(10, 100]") %>% pull(DensityLogBin)
PaMutMono10.proportion<-test1Unique %>%filter(Condition == "Pa Mono", Strain == "PA14mut",LogBin == "(10, 100]") %>% pull(DensityLogBin)
PaWtMono100.proportion<-test1Unique %>%filter(Condition == "Pa Mono", Strain == "PA14wt",LogBin == paste0("(100, ",bquote("\U221E"), ")")) %>% pull(DensityLogBin)
PaMutMono100.proportion<-test1Unique %>%filter(Condition == "Pa Mono", Strain == "PA14mut",LogBin == paste0("(100, ",bquote("\U221E"), ")")) %>% pull(DensityLogBin)

PaWtCo5.proportion<-test1Unique %>%filter(Species =="Pa", ConditionNew == "Co", Strain == "PA14wt",LogBin == "(5, 10]") %>% pull(DensityLogBin)
PaMutCo5.proportion<-test1Unique %>%filter(Species =="Pa", ConditionNew == "Co", Strain == "PA14mut",LogBin == "(5, 10]") %>% pull(DensityLogBin)
PaWtCo10.proportion<-test1Unique %>%filter(Species =="Pa", ConditionNew == "Co", Strain == "PA14wt",LogBin == "(10, 100]") %>% pull(DensityLogBin)
PaMutCo10.proportion<-test1Unique %>%filter(Species =="Pa", ConditionNew == "Co", Strain == "PA14mut",LogBin == "(10, 100]") %>% pull(DensityLogBin)
PaWtCo100.proportion<-test1Unique %>%filter(Species =="Pa",ConditionNew=="Co",Strain == "PA14wt",LogBin == paste0("(100, ",bquote("\U221E"), ")")) %>% pull(DensityLogBin)
PaMutCo100.proportion<-test1Unique %>%filter(Species =="Pa",ConditionNew=="Co",Strain == "PA14mut",LogBin==paste0("(100, ",bquote("\U221E"), ")")) %>% pull(DensityLogBin)

#mono vs Co
SaWt5.proportion<-t.test(x = SaWtMono5.proportion, y = SaWtCo5.proportion, paired = T)
SaWt10.proportion<-t.test(x = SaWtMono10.proportion, y = SaWtCo10.proportion, paired = T)
SaMut5.proportion<-t.test(x = SaMutMono5.proportion, y = SaMutCo5.proportion, paired = T)
SaMut10.proportion<-t.test(x = SaMutMono10.proportion, y = SaMutCo10.proportion, paired = T)

PaWt5.proportion<-t.test(x = PaWtMono5.proportion, y = PaWtCo5.proportion, paired = T)
PaWt10.proportion<-t.test(x = PaWtMono10.proportion, y = PaWtCo10.proportion, paired = T)
#PaWt100<-t.test(x = PaWtMono100, y = PaWtCo100, paired = T)
PaMut5.proportion<-t.test(x = PaMutMono5.proportion, y = PaMutCo5.proportion, paired = T)
PaMut10.proportion<-t.test(x = PaMutMono10.proportion, y = PaMutCo10.proportion, paired = T)
#PaMut100<-t.test(x = PaMutMono100, y = PaMutCo100, paired = T)

#Wt vs pqsL
SaWtMut5.proportion<-t.test(x = SaMutCo5.proportion, y = SaWtCo5.proportion, paired = F)
SaWtMut10.proportion<-t.test(x = SaMutCo10.proportion, y = SaWtCo10.proportion, paired = F)
#SaWtMut100<-t.test(x = SaMutCo100, y = SaWtCo100, paired = F)

PaMonoWtMut5.proportion<-t.test(x = PaMutMono5.proportion, y = PaWtMono5.proportion, paired = F)
PaMonoWtMut10.proportion<-t.test(x = PaMutMono10.proportion, y = PaWtMono10.proportion, paired = F)
PaMonoWtMut100.proportion<-t.test(x = PaMutMono100.proportion, y = PaWtMono100.proportion, paired = F)

PaCoWtMut5.proportion<-t.test(x = PaMutCo5.proportion, y = PaWtCo5.proportion, paired = F)
PaCoWtMut10.proportion<-t.test(x = PaMutCo10.proportion, y = PaWtCo10.proportion, paired = F)
PaCoWtMut100.proportion<-t.test(x = PaMutCo100.proportion, y = PaWtCo100.proportion, paired = F)
#t-tests table
tTestDatAggSizes.proportion<-list(SaWt5.proportion,SaWt10.proportion,SaMut5.proportion,SaMut10.proportion,PaWt5.proportion,PaWt10.proportion,PaMut5.proportion,
                       PaMut10.proportion,SaWtMut5.proportion,SaWtMut10.proportion,PaMonoWtMut5.proportion,PaMonoWtMut10.proportion,PaMonoWtMut100.proportion,
                       PaCoWtMut5.proportion,PaCoWtMut10.proportion,PaCoWtMut100.proportion)
tTestAggSizesTable.proportion<-bind_rows(map(tTestDatAggSizes.proportion, TtestTable))

#####

#plot frequency bins proportion
test1Unique$Species <- factor(test1Unique$Species, levels = c("Pa", "Sa"),labels = c('P. aeruginosa','S. aureus'))
test1Unique$ConditionNew <- factor(test1Unique$ConditionNew, levels = c("Mono", "Co"))
PlotFreqLogBinProp<-function(strain){
  df <-test1Unique%>% filter(Strain == strain)
  ggplot()+
    geom_col(data = df, aes(x=LogBin,y=MeanDensityLogBin*100,  fill =ConditionNew ),size=4,position = position_dodge( width = .9))+
    geom_errorbar(data = df,aes(x=LogBin,ymin=(MeanDensityLogBin-SEDensityLogBin)*100, ymax = (MeanDensityLogBin+SEDensityLogBin)*100, group = ConditionNew),width = 0, size= .5,position = position_dodge( width = .9))+
    facet_grid(.~Species)+
    labs(fill = "",y = "Aggregates per bin (% of total)",x = bquote(paste("Aggregate Volume (", mu*"m"^3*")")))+
    guides(color = FALSE)+
    scale_y_continuous(expand = expand_scale(mult = c(0, 0.2)))+
    scale_fill_grey(labels = c("Mono-culture", "Co-culture"))+
    theme_half_open()+
    theme(plot.title = element_text(hjust = 0.5),
          strip.text = element_text(size = 9, face = "italic",margin = margin(.1,0,.1,0, "cm")),#this is for the facets
          strip.background = element_rect(color="black", fill="white", size=.5, linetype="solid"),
          plot.margin = unit(c(0,.5,0,.5), "cm"),
          axis.title.x = element_text(margin = margin(0,0,0,0),size=13),axis.text.x = element_text(margin = margin(1,0,0,0),size=11),
          axis.title.y = element_text(margin = margin(0,4,0,0),size=13),axis.text.y = element_text(margin = margin(0,2,2,0),size=11),
          legend.title = element_text(size=13),legend.text = element_text(size = 11),
          legend.position = c(0.79, 0.60))
  }
figure1F<-PlotFreqLogBinProp("PA14wt")
figure2F<-PlotFreqLogBinProp("PA14mut")

figure1EF<-plot_grid(figure1E,figure1F,rel_widths = c(1,1.2),align='vh',labels = c("D", "E"),hjust = -1,nrow = 1,label_size= 20, label_x = 0, label_y = .95)
figure2EF<-plot_grid(figure2E,figure2F,rel_widths = c(1,1.2),align='vh',labels = c("D", "E"),hjust = -1,nrow = 1,label_size= 20, label_x = 0, label_y = .95)


```

```{Make full figures 1 and 2}
top_Row1<-plot_grid(figure1AB,figure1CD,align='vh',nrow = 1, rel_widths = c(2,1))
plot_grid(top_Row1,figure1EF, align='v',nrow = 2, rel_heights = c(1,1.5))

top_Row2<-plot_grid(figure2AB,figure2CD,align='vh',nrow = 1, rel_widths = c(2,1))
plot_grid(top_Row2,figure2EF, align='v',nrow = 2, rel_heights = c(1,1.5))

```
```{r figure 3}
MixedAggregateBiomassPlot<-ggplot()+
  #geom_point(data = combinedMixedAggData,aes(x=Strain.x,y=PercentTotalBiomass ),size=1)+
  geom_point(data = combinedMixedAggData,aes(x=Strain.x,y=MeanTotalBiomass),shape = 1, size=4)+
  geom_errorbar(data = combinedMixedAggData,aes(x=Strain.x,ymin=MeanTotalBiomass-SETotalBiomass, ymax =MeanTotalBiomass+SETotalBiomass),size=.2, width = 0)+
  scale_shape_manual(values = c(1,2),name = "", limits=c("PA14wt","PA14mut"))+
  scale_x_discrete(breaks=c("PA14wt","PA14mut"), 
                   labels = c(bquote(paste(italic("P. aeruginosa"), " wt")), bquote(paste(italic(Delta*"pqsL")))))+
    labs(y = "Mixed aggregates biomass (%)", x = "")+
  theme_cowplot()+
  theme(plot.title = element_text(hjust = 0.5),legend.position="none")

MixedAggregateFrequencyPlot<-  ggplot()+
  #geom_point(data = combinedMixedAggData,aes(x=Strain.x,y=PercentAggs ),size=1)+
  geom_point(data = combinedMixedAggData,aes(x=Strain.x,y=MeanAggs),size=4, shape = 1)+
  geom_errorbar(data = combinedMixedAggData,aes(x=Strain.x,ymin=MeanAggs-SEAggs, ymax =MeanAggs+SEAggs),size=.2, width = 0)+
  scale_shape_manual(values = c(1,2),name = "", limits=c("PA14wt","PA14mut"))+
  scale_x_discrete(name =expression(italic("P. aeruginosa")), breaks=c("PA14wt","PA14mut"), 
                     labels = c("wt",bquote(paste(italic(Delta*"pqsL")))))+
  labs(y = "Mixed aggregates (% frequency)", x = "")+
  ylim(0,10)+
  theme_cowplot()+
  theme(plot.title = element_text(hjust = 0.5),legend.position="none")

#the enrichment data is on "propOc Data 3D.Rmd" but I changed the distance for Sa Sa to 1 because this is just the range
enrichmentDataSpreadsheet<-read.csv("/Users/jupabago/Documents/Whiteley/PROJECTS/PaSaProject/Spatial paper Data/Prop Oc Final Data/Enrichment distance.csv",header = TRUE)
enrichmentDataSpreadsheet$Strain<-as.factor(enrichmentDataSpreadsheet$Strain)
enrichmentDataSpreadsheet$Strain <- factor(enrichmentDataSpreadsheet$Strain, levels = c("wt","mut"))

sa.paPlot<-
  ggplot()+
  geom_point(data = enrichmentDataSpreadsheet %>% filter(Relation == "Sa->Pa"),aes(y=meanEnrichment, x = Strain),size=4, shape = 1)+
  geom_errorbar(data = enrichmentDataSpreadsheet %>% filter(Relation == "Sa->Pa"),
                aes(ymin = meanEnrichment-sdEnrichment,ymax = meanEnrichment+sdEnrichment, x = Strain),size=.2, width = 0)+
  #labs( y = bquote(paste("Enrichment distance\n", italic("S. aureus") %->% italic("P. aeruginosa "),"("*mu*"m)")), x = "" ) +
  labs(y = expression(atop("Enrichment distance ("*mu*"m)",paste(italic("S. aureus") %->% italic("P. aeruginosa "))))) +
  scale_shape_manual(values = c(1,2),name = "", limits=c("wt","mut"),
                     labels = c(bquote(paste(italic('P. aeruginosa'), " wild-type")),
                                bquote(paste(italic('P. aeruginosa '), Delta*"pqsL"))))+
  scale_x_discrete(name =expression(italic("P. aeruginosa")), breaks = c("wt","mut"), 
                   labels = c("wt", bquote(paste(italic(Delta*"pqsL")))))+
  ylim(0, 10)+
  theme_cowplot()+
  theme(plot.title = element_text(hjust = 0.5),legend.position="none")

sa.saPlot<-
  ggplot()+
  geom_point(data = enrichmentDataSpreadsheet %>% filter(Relation == "Sa->Sa"),aes(y=meanEnrichment, x = Strain),size=4, shape = 1)+
  geom_errorbar(data = enrichmentDataSpreadsheet %>% filter(Relation == "Sa->Sa"),
                aes(ymin = meanEnrichment-sdEnrichment,ymax = meanEnrichment+sdEnrichment, x = Strain),size=.2, width = 0)+
  labs(y = expression(atop("Enrichment distance ("*mu*"m)",paste(italic("S. aureus") %->% italic("S. aureus ")))), x = "" ) +
  scale_shape_manual(values = c(1,2),name = "", limits=c("wt","mut"),labels = c(bquote(paste(italic('P. aeruginosa'), " wild-type")),
                                bquote(paste(italic('P. aeruginosa '), Delta*"pqsL"))))+
  scale_x_discrete(name =expression(italic("P. aeruginosa")), breaks = c("wt","mut"), 
                   labels = c("wt", bquote(paste(italic(Delta*"pqsL")))))+
  ylim(0, 10)+
  theme_cowplot()+
  theme(plot.title = element_text(hjust = 0.5),legend.position="none")


figure7 <- plot_grid(MixedAggregateFrequencyPlot,sa.saPlot,sa.paPlot,align='vh',labels = c("A","B", "C"),hjust = -1,nrow = 1)
figure7
```
```{r biomass per bin}
PlotDensityLogBin<-function(strain,titulo){
  df <-hist.5.LogBinSummarize%>% filter(Strain == strain)
  ggplot()+
    geom_col(data = df, aes(x=LogBin,y=MeanBiomassLogBin*100, fill =ConditionNew),size=4,position = position_dodge( width = .9))+
    geom_errorbar(data = df,aes(x=LogBin,ymin=(MeanBiomassLogBin-SEBiomassLogBin)*100, ymax = (MeanBiomassLogBin+SEBiomassLogBin)*100, group =ConditionNew ),width = 0, size=.5,position = position_dodge(width = 1))+
    #labs(title = titulo)+
    #scale_y_log10(breaks = scales::trans_breaks("log10", function(x) 10^x), labels = scales::trans_format("log10", scales::math_format(10^.x)))+
    facet_grid(.~Species)+
    labs(fill = "Condition",y = "% biomass contribution per bin",x = bquote(paste("Aggregate Volume (", mu*"m"^3*")")))+
    guides(color = FALSE)+
    scale_fill_grey()+
    theme_cowplot(12)+
    theme(plot.title = element_text(hjust = 0.5),strip.text = element_text(face = "italic"))
}
PlotDensityLogBin("PA14wt", "WT")
PlotDensityLogBin("PA14mut", "pqsL")

```
```{r Tobramycin}
#data is on "SaPa TOB growth curves.Rmd"
#End point bar graph with std error
tobCFUPlot<- 
  ggplot() +
  geom_col(data = wilcoxDataGood, aes (x = culture, y = meanLog, fill = antibiotic, group = antibiotic), position = position_dodge( ))+
  geom_linerange(data = wilcoxDataGood, aes(x = culture, ymin = meanLog - seLog, ymax = meanLog + seLog,group = antibiotic),position = position_dodge(width = .9))+
  scale_y_continuous(expand = expand_scale(mult = c(0, 0.05)), breaks = c(0,2,4,6,8,10), labels =c(0,2,4,6,8,10))+
  scale_x_discrete(name ="", breaks = c("mono","wt","mut"), 
                   labels = c(expression(atop(italic("S. aureus"), paste("mono-culture"))), 
                              expression(atop(italic("S. aureus +"), paste(italic("P. aeruginosa"), " wt"))), 
                              expression(atop(italic("S. aureus +"), paste(italic("P. aeruginosa "*Delta*"pqsL"))))))+
  labs(y = expression(paste(italic("S. aureus ("), Log[10]," CFU)")), x = "", fill = "") +
  scale_fill_grey()+
  theme_cowplot()+
  theme_half_open()+
  background_grid()

tobPercentChangePlot<-
  ggplot() +
  geom_col(data = percentChange %>% filter(sample == "1-25-20"), aes (x = culture, y = 10^(MeanLogKill)))+
  geom_linerange(data = percentChange, aes(x = culture, ymin = 10^(MeanLogKill - SeLogKill/2), ymax = 10^(MeanLogKill + SeLogKill/2)))+
  scale_y_log10(expand = expand_scale(mult = c(0, 0.05)))+
  scale_x_discrete(name ="", breaks = c("mono","wt","mut"), 
                   labels = c(expression(atop(italic("S. aureus"), paste("mono-culture"))), 
                              expression(atop(italic("S. aureus +"), paste(italic("P. aeruginosa"), " wt"))), 
                              expression(atop(italic("S. aureus +"), paste(italic("P. aeruginosa "*Delta*"pqsL"))))))+
  #labs(y = expression(atop("Enrichment distance ",paste(italic("S. aureus") %->% italic("S. aureus "),"("*mu*"m)"))), x = "" ) +
  labs(y = expression(paste("Fold killing ", italic("S. aureus"))), x = "") +
  scale_fill_grey()+
  theme_cowplot()+
  theme_half_open()+
  background_grid()

prow <- plot_grid(tobCFUPlot+theme(legend.position="none"),tobPercentChangePlot+theme(legend.position="none"),align='vh',labels = c("A", "B"),hjust = -1,nrow = 1)
legend <- get_legend(tobCFUPlot + theme(legend.box.margin = margin(0, 0, 0, -6)))
plot_grid(prow,legend,rel_widths = c(3, .4))
#this is the winner
plot_grid(tobCFUPlot+theme(legend.position="none"),legend,tobPercentChangePlot+theme(legend.position="none"),align='vh',labels = c("A", "","B"),hjust = -1,nrow = 1,rel_widths = c(1,.15,1))
```
```{r biomass}
GraphGrowthCurvesExpClean(cleanResults1 %>% filter(TimePoint<10),cleanResultsStats1%>% filter(TimePoint<10), "Sa")

countsFinal1<-countsFinal %>% mutate(logCounts = log10(cellCount)) %>% group_by(bug, condition) %>% mutate(meanLog = mean(logCounts), sdcounts = std.error(logCounts))

ggplot()+
  geom_jitter(data= countsFinal1, aes(x=condition, y= logCounts,  shape= condition),height = 0, width = .2, size = 1)+
  #geom_text(fontface = "bold",position=position_jitter(width=.5,height=0))+
  geom_point(data= countsFinal1, aes(x=condition, y= meanLog,shape= condition), size = 3)+
  geom_errorbar(data=countsFinal1,aes(x=condition,ymin = meanLog - sdcounts, ymax = meanLog + sdcounts), size=.5, width = 0.2)+
  #scale_y_log10(name="Mouse Wound CFU/mL", limits= c(1,1e8),breaks = scales::trans_breaks("log10", function(x) 10^x), labels = scales::trans_format("log10", scales::math_format(10^.x)))+
  ylim(2,8)+ 
  labs(x = "",  y = expression(paste(Log[10], " CFU")), shape="Strain")+
  facet_grid(.~bug)+
  theme_cowplot(12)

```
```{r invasion ratios graphs}
#functions to get data
GetResults<-function(sample, samplename){
  folder<- paste0('/Users/jupabago/Documents/Whiteley/PROJECTS/PaSaProject/Spatial paper Data/Microscopy Data/Other Data1/',sample,'/results')
  #the path just needs to be changed to"Other Data1"
  fileList<-list.files(path = folder, full.names = TRUE)
  growthDf<-data.frame()
  for (position in 0:5){
    currentPosition<-fileList[grep(paste0("p",position,"."),fileList)]
    for (timepoint in 0:17){
      currentTimePoint<-currentPosition[grep(paste0("t",GetNumber(timepoint),"_"),currentPosition)]
      growthDf<-rbind(growthDf,ReadResultsFile(currentTimePoint, position, timepoint))}}
  growthDf<-growthDf %>% mutate(Sample = samplename)
return(growthDf)
}
ReadResultsFile<-function(file, position, timepoint){
  datos <-read.csv(file, header = FALSE)
  colnames(datos)<-c('Red', 'Green', 'Slice')
  datos<-datos %>% mutate(Position = position)
  datos<-datos %>% mutate(TimePoint = timepoint)
  return(datos)
}
MapResults<- function(listSamples, reps){
  blah <-deparse(substitute(listSamples))
  mappedData<-map2(listSamples, reps, GetResults)
  boundData<-bind_rows(mappedData)
  boundData<-boundData %>% mutate(Strain = blah)
  boundData<-gather(boundData,"Color","Value",-Slice,-Position,-Sample,-TimePoint,-Strain) %>% mutate(LogValue=ifelse(Value>0,log10(Value),0))
  boundData<-boundData %>% mutate(Condition = recode(Position, "0" = "Sa Mono", "1" = "Pa Mono", "2" = "Pa:Sa 1:1", "3" = "Pa:Sa 10:1", "4" = "Pa:Sa 1:100", "5" = "Pa:Sa 1:10" )) %>% mutate(Species = recode(Color, "Red" = "Sa", "Green" = "Pa")) %>% mutate(ZDistance = Slice *0.44)
  boundData$Condition<-as.factor(boundData$Condition)
  boundData$Condition<-factor(boundData$Condition, levels = c("Sa Mono", "Pa Mono", "Pa:Sa 1:1", "Pa:Sa 1:10", "Pa:Sa 1:100","Pa:Sa 10:1"))
  boundData$Species<-as.factor(boundData$Species)
  boundData$Strain<-as.factor(boundData$Strain)
  return(boundData)
  }
PA14wt<- c('3-13-19', '3-19-19', '4-17-19')
PA14mut<- c('4-24-19', '4-25-19', '5-8-19')
names3<-c('rep1','rep2','rep3')
wtBiomassResults<-MapResults(PA14wt, names3)
mutBiomassResults<-MapResults(PA14mut, names3)

biomassData<-rbind(wtBiomassResults,mutBiomassResults)#combine data
#Add up all the data on each slice and then get the log of that total
biomassDataClean<-biomassData %>% 
  group_by(TimePoint,Sample,Strain,Condition,Species) %>% 
  summarise(Totals = sum (Value))%>% 
  mutate(LogTotals = ifelse(Totals>0, log10(Totals), 0))
#Get stats
biomassStats<-biomassDataClean %>% 
  group_by(TimePoint,Strain,Condition,Species) %>% 
  summarise(MeanTotals = mean(Totals), SDTotals = sd(Totals), MeanLogTotals = mean(LogTotals), SDLogTotals = sd(LogTotals)) %>%
  mutate(MeanLogTotalsRevd = 10^MeanLogTotals, SDLogTotalsRevd =10^(SDLogTotals))

biomassDataCleantEST <-biomassDataClean %>%filter(!Condition%in%c("Sa Mono", "Pa Mono")) %>% filter(TimePoint<7) %>% group_by(TimePoint, Sample, Strain, Condition) %>% mutate(RatioTotals = Totals[Species == "Pa"]/Totals[Species == "Sa"],LogDiff = LogTotals[Species == "Pa"]-LogTotals[Species == "Sa"]) %>% ungroup() %>% group_by(TimePoint,Strain,Condition,Species) %>% mutate(meanRatio = mean(RatioTotals), meanLogDiff = mean(LogDiff)) %>% ungroup()

ggplot()+#graph all data
  geom_point(data = biomassDataCleantEST,aes(x=TimePoint,y=LogDiff, color = Condition, shape = Strain ), size=4)+
  geom_smooth(data = biomassDataCleantEST,aes(x=TimePoint,y=LogDiff, color = Condition, linetype = Strain ), size=1)+
  labs(title ="title")+
  #scale_y_log10(breaks = scales::trans_breaks("log10", function(x) 10^x), labels = scales::trans_format("log10", scales::math_format(10^.x)))+
  theme_cowplot()+
  theme(plot.title = element_text(hjust = 0.5))

ggplot()+#graph means
  geom_point(data = biomassDataCleantEST,aes(x=TimePoint,y=meanLogDiff, color = Condition, shape = Strain ), size=4)+
  #geom_smooth(data = biomassDataCleantEST,aes(x=TimePoint,y=LogDiff, color = Condition, linetype = Strain ), size=1)+
  #labs(title ="title")+
  labs(y = "ratio Pa / Sa")+
  #scale_y_log10(breaks = scales::trans_breaks("log10", function(x) 10^x), labels = scales::trans_format("log10", scales::math_format(10^.x)))+
  theme_cowplot()+
  theme(plot.title = element_text(hjust = 0.5))

tenToOneData<-biomassDataCleantEST %>% filter(Condition %in% c("Pa:Sa 1:1","Pa:Sa 10:1")) %>% group_by(Species, Condition, Strain, TimePoint) %>% mutate(logMean = mean(LogTotals))
ggplot()+#graph means
  geom_point(data = tenToOneData,aes(x=TimePoint,y=logMean, color = Condition, shape = Strain ), size=4)+
  geom_line(data = tenToOneData,aes(x=TimePoint,y=logMean, color = Condition, linetype = Strain ), size=4)+
  #geom_smooth(data = biomassDataCleantEST,aes(x=TimePoint,y=LogDiff, color = Condition, linetype = Strain ), size=1)+
  #labs(title ="title")+
  labs(y = "ratio Pa / Sa")+
  #scale_y_log10(breaks = scales::trans_breaks("log10", function(x) 10^x), labels = scales::trans_format("log10", scales::math_format(10^.x)))+
  facet_grid(~Species)+
  theme_cowplot()+
  theme(plot.title = element_text(hjust = 0.5))
```